### PR TITLE
chore(deps): update package dependencies

### PR DESCRIPTION
**Pull request by FungusHumungus**
There is a [security advisory](https://rustsec.org/advisories/RUSTSEC-2021-0023) on `rand_core`.

I have run `cargo update` on the project to update the dependencies to a patched version (0.6.2).

Note, a number of other crates have been updated too. I'm not particularly sure if this is a problem or not, so have decided to keep these updates.

```
╰─$ cargo update
    Updating git repository `https://github.com/hyperium/hyper`
    Updating crates.io index
    Updating git repository `https://github.com/bytecodealliance/lucet.git`
    Updating git repository `https://github.com/kyren/rlua`
    Updating git repository `https://github.com/tower-rs/tower`
    Updating git repository `https://github.com/tokio-rs/tracing`
    Updating async-graphql-parser v2.4.6 -> v2.5.4
    Updating bson v1.1.0 -> v1.2.0
    Updating env_logger v0.8.2 -> v0.8.3
    Updating lexical-core v0.7.4 -> v0.7.5
    Updating lru v0.6.4 -> v0.6.5
    Updating maxminddb v0.17.1 -> v0.17.2
    Updating nb-connect v1.0.2 -> v1.0.3
    Removing nom v5.1.2
    Removing nom v6.1.0
      Adding nom v6.1.2
    Updating parking_lot_core v0.8.2 -> v0.8.3
    Updating pem v0.8.2 -> v0.8.3
      Adding prost v0.7.0
      Adding prost-build v0.7.0
      Adding prost-derive v0.7.0
      Adding prost-types v0.7.0
    Updating pulsar v1.0.1 -> v1.1.0
    Updating quote v1.0.8 -> v1.0.9
    Updating rand_core v0.6.1 -> v0.6.2
    Updating redox_syscall v0.2.4 -> v0.2.5
    Updating serde_yaml v0.8.16 -> v0.8.17
    Updating tap v1.0.0 -> v1.0.1
      Adding which v4.0.2
```

### CODE REVIEW

**Comment by binarylogic** [comment]
It's fine, note how @fanatid has previously updated dependencies:https://github.com/timberio/vector/pull/6217

**Review by ktff — APPROVED** [review]
The failing test is unrelated, and one bench needs to be updated but it seams to be unrelated to this PR, so nothing blocking, but it would be nice to update the bench and confirm that there aren't any performance regressions.

**Comment by lucperkins** [comment]
FYI #6449 should fix that unrelated failure

**Review by jszwedko — APPROVED** [review]

**Comment by jszwedko** [comment]
I merged master to run benches.

**Pull request merged**
