### PR TITLE
fix(json_parser transform): only drop source field if JSON parse succeeds (#1861)

### LINKED ISSUE #1861: The `json_parser` `drop_field` option should only drop the field on successful parsing
From our chat:

> I have another quick question - the json_parser transform seems to always remove the source field when drop_field is true. This seems inconsistent with the behavior of e.g. grok_parser, which only removes it when the parse succeeds. Is that behavior intentional?

We should not be dropping the field is parsing fails.

Related https://github.com/timberio/vector/pull/1172

### PR DESCRIPTION
**Pull request by sciyoshi**
Fixes #1861.

### CODE REVIEW

**Comment by binarylogic** [comment]
Thanks! I’d like to see a test for this before merging.

**Comment by sciyoshi** [comment]
Of course @binarylogic - just updated the PR with a test for this case.

**Comment by sciyoshi** [comment]
Pushed an update to clarify this in the `drop_field` documentation as well.

**Comment by bruceg** [comment]
I think this just needs a `make generate` and it should be good to go, assuming the rest of the tests still pass.

**Comment by sciyoshi** [comment]
@bruceg done.

**Comment by bruceg** [comment]
Thanks @sciyoshi

**Pull request merged**
