### PR TITLE
fix(http source): lower handle http req log to debug

### PR DESCRIPTION
**Pull request by spencergilbert**
Closes: #5704 

@jszwedko

### CODE REVIEW

**Comment by fanatid** [comment]
I think we can remove `rate_limit_secs` since this log on `debug!`.

**Review by jszwedko — APPROVED** [review]
Thanks @spencergilbert !

I agree with @fanatid that we could drop the rate limit on this one since it was lowered to the debug level.

**Comment by spencergilbert** [comment]
> Thanks @spencergilbert !
> 
> I agree with @fanatid that we could drop the rate limit on this one since it was lowered to the debug level.

Sounds good, I'll do that today

**Review by jszwedko — APPROVED** [review]

**Comment by jszwedko** [comment]
I'll merge whenever CI is done.

**Pull request merged**
