### PR TITLE
fix(cli): Use temporary `wasm` artifact_cache directory during `validate` command

### LINKED ISSUE #3930: validate command creates files, which sometimes leads to permission isuses
### Vector Version

```
vector 0.10.0 (g0f0311a x86_64-unknown-linux-gnu 2020-07-22)
```

### Vector Configuration File

```
[sources.test_logs]
type = "file"
include = ["/var/log/*.log"]
```

### Expected Behavior

We're running `vector validate /tmp/vector-new.toml` before installing the new configuration file. This is done through Ansible, which always runs these commands as root, as opposed to the `vector` user

We were expecting that this wouldn't be a problem.

### Actual Behavior

When running `vector validate`, files in `/var/lib/vector` get messed with:

```
root@7351cdd950a9:/# vector validate
√ Loaded "/etc/vector/vector.toml"

Topology errors
---------------
x No sinks defined in the config.

√ Component configuration
root@7351cdd950a9:/# ls -l /var/lib/vector/
total 4
drwxr-xr-x 2 root root 4096 Sep 16 12:50 test_logs
```

This causes vector to not be able to start. So far I found this behaviour with the `file` and `journald` sources, but there might be others.

### PR DESCRIPTION
**Pull request by ktff**
Ref #3930 

To avoid creating directories and caches in runtime directory we:
* create them in a tmp directory
* manually check original path

### Open questions

- [ ] Is there a better way to modify `wasm` transform configuration than passing `BuildMode` around?

### CODE REVIEW

**Comment by ktff** [comment]
cc @Hoverbear

**Review by Hoverbear — COMMENTED** [review]
So, I'm worried this work will be for nothing as we plan to migrate to wasmtime in the future which does not have the concept of an artifact cache (it's a JIT with a store like https://docs.rs/wasmtime/0.20.0/wasmtime/struct.Store.html, instead).

Do you think if we remove the artifact cache these new features in validate will be a worthwhile maintenance burden?

**Comment by ktff** [comment]
I was already on the edge if this fix is worth it, so if the issue will be resolved on it's own later, yea, this isn't worthy of maintenance. I'll see if there is some lighter fix, if not, I think we can leave it as it is since it has specific conditions of validate + different access group + `wasm` transform.

**Comment by ktff** [comment]
I don't see a lighter way to fix this than this PR, so I'll add a description/reasoning in the issue and close this.

**Pull request closed without merging**
