### PR TITLE
fix(splunk_hec source): Default `host` to remote address

### PR DESCRIPTION
**Pull request by ktff**
Ref #7097 

Adds support on our side. See https://github.com/timberio/vector/issues/7097#issuecomment-830676486

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
Should we note this in the `splunk_hec` docs?

**Review by bruceg — COMMENTED** [review]
The change looks reasonable to me, but I agree with @jszwedko we should look at updating the reference documentation to match this change.

**Comment by ktff** [comment]
We should maybe remove/comment out completely it's docs until it can actually be set. Like when either `warp` fixes it, or when we start using X-Forwarded-For` header.

**Comment by jszwedko** [comment]
> ~We should maybe remove/comment out completely it's docs until it can actually be set. Like when either `warp` fixes it, or when we start using X-Forwarded-For` header.~
> 
> EDIT: So there is no mention of this feature in the `splunk_hec` docs and I think it should be like that until either `warp` fixes the support, or when we start using X-Forwarded-For` header, since otherwise we will never set the field.

:+1: agreed. If we aren't setting it right now, which it seems like we are not, then we can leave it out of the docs.

**Pull request merged**
