### PR TITLE
chore(operations): Template the CI file

### PR DESCRIPTION
**Pull request by Hoverbear**
Template out the CI file with data from our meta.

### CODE REVIEW

**Comment by Hoverbear** [comment]
It seems we have some inconsistencies with our features, if I read the transforms etc we list, we see errors: 

* First one is that the feature is `sinks-datadog`
* Second one is that the feature is `sinks-gcp`

image

**Comment by Hoverbear** [comment]
Need to test out tradeoffs around incremental and the cache.

**Comment by Hoverbear** [comment]
Bumped into #2393

**Comment by binarylogic** [comment]
Going to close this in favor of https://github.com/timberio/vector/pull/2440#issuecomment-619206191

**Pull request closed without merging**
