### PR TITLE
chore(vrl): Remove skipped coalesce test as it's duplicated by unnecessary_error_coalesce.vrl

### PR DESCRIPTION
**Pull request by spencergilbert**
Signed-off-by: Spencer Gilbert <spencer.gilbert@datadoghq.com>

Was unsure if we needed to move the issue to the `tests/issues` directory since the test was actually already present.

Duplicating test introduced: #6471

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
👍 thanks for the clean-up

**Comment by spencergilbert** [comment]
> 👍 thanks for the clean-up

NP, got curious why it was skipped when I was testing my rebuilt build server. I'll let one of Jean or Stephen decide on the delete vs move

**Review by StephenWakely — APPROVED** [review]
Nice.

**Comment by StephenWakely** [comment]
>  I'll let one of Jean or Stephen decide on the delete vs move

As you point out it's duplicated in another test, so there's no point keeping this around.

**Pull request merged**
