### PR TITLE
chore(ci): Added clippy to all source changes

### PR DESCRIPTION
**Pull request by jamtur01**
Signed-off-by: James Turnbull <james@lovedthanlost.net>

### CODE REVIEW

**Comment by MOZGIII** [comment]
I wonder if we should also add `make check` there? Afaik, `clippy` will cover that as well, but we have slightly different flags set at `Makefile` for `make check` and `make clippy`

**Review by MOZGIII — APPROVED** [review]

**Comment by jamtur01** [comment]
I'm actually going to close this in favor of refactoring how changes are tested so we're testing for them all in one place and not between two jobs.

**Pull request closed without merging**
