### PR TITLE
docs: fix typos

### PR DESCRIPTION
**Pull request by anton-ryzhov**
I'm not sure how does it work, but I tried to fix this filter on https://vector.dev/docs/reference/transforms/ page:
image

And some search&replace

### CODE REVIEW

**Comment by anton-ryzhov** [comment]
(After one hour of fighting with ruby) `make generate` reverts it back, seems it doesn't work as I expected

**Comment by binarylogic** [comment]
Thanks @anton-ryzhov, I'll get this fixed. Appreciate the help. And yes, `make generate` needs some UX improvement. We'll spend some time documenting that and improving the error messages when that is run.

**Comment by binarylogic** [comment]
Thanks again for this @anton-ryzhov. Also, we've since updated `make generate` to run through a Docker container to avoid having to install any local dependencies.

**Comment by anton-ryzhov** [comment]
Thank you for taking care of that

**Pull request merged**
