### PR TITLE
fix(prometheus_exporter sink): Fix Metrics not Updating

### LINKED ISSUE #5916: Prometheus Sink Not Updating
### Vector Version

```
Current master 19a90e8f1cba1642cfc9b97e8598c6a9ef310372
```

### Bug Report

The prometheus_sink is not updating with new metrics, new metric _samples_ (set of name and labels) appear but the values never update again.

### PR DESCRIPTION
**Pull request by tustvold**
This reverts commit 91f77ef44a4dfa182c27cf3483a878ad576d8757 as discussed on Discord

Fixes #5916

### CODE REVIEW

**Review by bruceg — COMMENTED** [review]
Thanks for taking the time to pinpoint this. I have verified that 928d8fc is a clean revert of 91f77ef. However, that change was introduced to fix another issue (#5258). Is there any chance you could add an integration test to this PR that demonstrates the failure?

**Comment by tustvold** [comment]
I'm similarly confused by this, I don't understand how this change would result in the behavior I observed... I will continue to investigate

**Comment by tustvold** [comment]
I think this might a case of PEBCAC, and I might have accidentally been testing on nodes with no actual traffic :facepalm:. This combined with inaccurate global reporting due to #5914 led me to miss-attribute this. I'll leave some tests running overnight and close this and the connected issue if they come up clean. Sorry for potentially wasting your time

**Comment by tustvold** [comment]
Simple steps to reproduce the issue

vector.toml
```
[sources.internal_metrics]
  type = "internal_metrics"

[sinks.prometheus]
  type = "prometheus_exporter"
  inputs = ["internal_metrics"]
  address = "0.0.0.0:8080"
```

```
watch -n 1 http :8080/metrics
```

On the current master `vector_uptime_seconds` will remain the same with neither the timestamp field nor the value field updating.

Now that I have a way to reproduce the issue locally I'll spend some time digging into what is causing it, I suspected it might have been caused by the use of std::sync::RwLock instead of tokio::sync::RwLock but changing this doesn't appear to help

**Comment by tustvold** [comment]
```
match item.kind {
                MetricKind::Incremental => {
                    let mut new = MetricEntry(item.to_absolute());
                    if let Some((MetricEntry(mut existing), _)) = metrics.map.remove_entry(&new) {
                        existing.add(&item);
                        new = MetricEntry(existing);
                    }
                    metrics.map.insert(new, item.value.is_set());
                }
                MetricKind::Absolute => {
                    let new = MetricEntry(item);
                    metrics.map.insert(new, false);
                }
            };
```

The problem is this code, in particular metrics.map.insert will not update the existing key if it finds one, only the value.

Previously this used `metrics.replace` which has the desired behaviour. The dumbest fix is to do the following

```
            match item.kind {
                MetricKind::Incremental => {
                    let mut new = MetricEntry(item.to_absolute());
                    if let Some((MetricEntry(mut existing), _)) = metrics.map.remove_entry(&new) {
                        existing.add(&item);
                        new = MetricEntry(existing);
                    }
                    metrics.map.insert(new, item.value.is_set());
                }
                MetricKind::Absolute => {
                    let new = MetricEntry(item);
                    metrics.map.remove(&new);
                    metrics.map.insert(new, false);
                }
            };
```

However, I'm somewhat inclined to revert to using an IndexSet (or possibly HashSet as I don't believe the order is important) with a tuple as opposed to using IndexMap as is done here. What do you think?

**Comment by bruceg** [comment]
> Previously this used `metrics.replace` which has the desired behaviour. The dumbest fix is to do the following

@tustvold if you do up a PR with the "dumbest fix", we'll be sure to push that through quick, especially if it is accompanied by a reproducer test case. I'll be writing up a separate issue to discuss some of the metric data model issues we chatted about.

**Comment by tustvold** [comment]
Clippy failures seem unrelated to my change

**Comment by jszwedko** [comment]
> Clippy failures seem unrelated to my change

:+1: this is fixed on master now if you want to merge it in.

**Review by bruceg — APPROVED** [review]

**Comment by tustvold** [comment]
Rebased on to current master

**Pull request merged**
