### PR TITLE
improvement(coercer transform): add a second chrono format option to convert from datetime to string

### LINKED ISSUE #867: Add another chrono format to convert timestamp to string
The current https://docs.vector.dev/usage/configuration/transforms/coercer support to convert string to timestamp,  would be better if we can add a second option to convert string to timestamp like:

```
localtime = "timestamp|%+|%F"
```

this situation is common like nginx produces [iso 8601 timestamp](http://nginx.org/en/docs/http/ngx_http_log_module.html#var_time_iso8601) but the storage(like clickhouse) would prefer a local time, so would be better to format timestamp to string again

### PR DESCRIPTION
**Pull request by xcaptain**
This is an attempt to fix #867 feel free to close if it's inappropriate

### CODE REVIEW

**Comment by binarylogic** [comment]
Thanks @xcaptain. I think the format is a little confusing given that the user is producing a string, not a timestamp. If I understand correctly, you basically want to re-format a `string` timestamp, but converting it to a timestamp and the converting it back to a string in a different format?

**Comment by xcaptain** [comment]
Yes, the first format convert a string to datetime and the second format convert datetime to another string. I will give my case as an example:

I'm using vector to collect nginx access log and then store to clickhouse. nginx uses `$time_iso8601` which produces datetime like `2019-09-16T18:17:54+08:00` but by default clickhouse only accept datetime like `2019-09-16 18:17:54`, to accept iso 8601 datetime, I have to modify clickhouse settings https://clickhouse.yandex/docs/en/operations/settings/settings/#settings-date_time_input_format  I think it's better to let vector do this datetime conversion

**Comment by binarylogic** [comment]
That makes sense. If you wouldn't mind, give us this week to discuss. I think there is a clearer more user-friendly approach to this. The fact that `timestamp` is used as the explicit type, but then produces a `string` is confusing. The alternatives I'm considering is improving how users can successively transform data. Ex: coercing to a timestamp and then coercing back to a string. This is being discussed in https://github.com/timberio/vector/issues/750.

**Comment by xcaptain** [comment]
@binarylogic Is there any methods to convert a timestamp from `2019-09-16T18:17:54+08:00` to `2019-09-16 18:17:54` currently?

**Pull request closed without merging**
