### PR TITLE
chore(deps): Unpin evmap from fork

### PR DESCRIPTION
**Pull request by jszwedko**
This required aliasing `Bytes` in the `aws_ec2_metadata` transform
because `Bytes` no longer saisfies `ShallowCopy` (and the `bytes`
feature of `evmap` was removed) as of
https://github.com/jonhoo/evmap/commit/416ccef

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Review by bruceg — COMMENTED** [review]
I'm not sure what to make of this. On one hand, we have already been using this for a while with no ill effects. On the other, there is a reason why this impl was removed from evmap, and it adds an `unsafe` to our code. I'd prefer to be convinced this is actually sound, though.

**Review by blt — CHANGES_REQUESTED** [review]
Oh geez. So that `ShallowCopy` implementation will only be valid if the layout of evmap internals happens to correspond to the layout of Bytes internals, which is not guaranteed. While it does accidentally work today consider what happens when, say, specialization lands in Rust and parameterized types start varying their internal layout depending on the parameter. 

I'm not overly familiar with this transform. Is there a reason why we can't get away with a `HashMap` in a mutex situation?

**Comment by spencergilbert** [comment]
I know `kubernetes_logs` source also ends up using evmap - I'm not sure if it could be affected as well.

**Comment by lukesteensen** [comment]
> I'm not overly familiar with this transform. Is there a reason why we can't get away with a `HashMap` in a mutex situation?

This transform essentially maintains a table against which incoming events are joined to add metadata. It spawns a task that periodically makes EC2 metadata API calls and updates an `evmap` write handle with that data, while the primary transform holds a read handle for doing lookups per incoming event. We chose `evmap` since the use case is very heavily read-dominant, with only occasional updates from a single writer.

We could try a `Mutex<HashMap>`, or maybe an `ArcSwap` (there is a lot of overlap with enrichment tables here and long term this could become one). Or we could store something other than `Bytes` that doesn't have this issue.

**Comment by blt** [comment]
Yeah, if we're read-mostly here I'd vote we pop in a `RwLock` and move on, absent a compelling, indicative perf read that we must have evmap or some other fancy atomic structure here.

**Comment by jszwedko** [comment]
Yeah, good call @blt @bruceg  and others. I dropped the `evmap` for a simple `Arc<RwLock<HashMap<_,_>>>` in d0eae98.

**Review by blt — APPROVED** [review]

**Pull request merged**
