### PR TITLE
chore: Check that all blog articles are signed in CI

### PR DESCRIPTION
**Pull request by a-rodin**
Closes https://github.com/timberio/vector/issues/1339.

This PR adds a new CI check called `check-blog` which verifies that all blog articles in [website/blog](https://github.com/timberio/vector/tree/master/website/blog) are signed using GPG by their authors.

It assumes that for each Markdown file containing a blog article there is a corresponding `.sig` file with [detached GPG signature](https://www.gnupg.org/gph/en/manual/x135.html#AEN160) for it.

Such signatures can be created by running

```bash
gpg --detach-sign <blog-article-file.md>
```

The author's GitHub URL has to be present in the front matter of each article. This GitHub URL can be used to extract the GitHub username and [get public GPG keys associated with the author's account](https://developer.github.com/v3/users/gpg_keys/#list-gpg-keys-for-a-user). Then these public GPG keys can be used by anyone to verify validity of the corresponding signature by running

```bash
gpg --verify <blog-article-file.md>.sig
```

Because `author_github` is necessary for such verification (as the file `.meta/team.toml` cannot be signed in the same way because it contains information about all authors), and it identifies the author unambiguously, I've removed the `author_id` field from the front matter and updated the related code to use `author_github`.

The CI check is failing now because the already present blog articles are not signed.

### CODE REVIEW

**Comment by a-rodin** [comment]
Now we need to persuade the authors of already added articles to sign them 😁

**Comment by Jeffail** [comment]
@a-rodin can you check on your end that my sig is correct?

**Comment by a-rodin** [comment]
@Jeffail I've checked the signature locally, it is correct.

**Comment by a-rodin** [comment]
@binarylogic @lukesteensen Do you mind adding your signatures for the corresponding articles too?

**Comment by binarylogic** [comment]
@a-rodin done. Might not be a bad idea to make this a make target as well, if you agree.

**Comment by a-rodin** [comment]
I've added a simple `make sign-blog` target, which creates signatures for all Markdown files without signatures in `website/blog`.

It doesn't check the author front matter, because making something more complex would require using Ruby, for example I normally run the Ruby scripts such as `scripts/generate.rb` in Docker, and Docker doesn't have access to the GPG keys in the user's home directory. The idea is that if someone signs other's blog article, it would be caught by the CI check.

**Comment by lukesteensen** [comment]
Sorry, had to go learn `gpg` :smile: 

Let me know if I did anything wrong, but I believe mine should be good now.

**Comment by a-rodin** [comment]
I've merged in the `master` branch. @Jeffail could you please sign the newly added blog articles? Then we would be able to merge this.

**Pull request merged**
