### PR TITLE
Do not merge, CI wip (minikube update)

### PR DESCRIPTION
**Pull request by MOZGIII**
https://github.com/kubernetes/minikube/issues/9304

### CODE REVIEW

**Comment by jamtur01** [comment]
@MOZGIII What's the status of this?

**Comment by MOZGIII** [comment]
I tried to revisit this yesterday, but without K8s E2Es in CI runs it's blocked :(

**Comment by jamtur01** [comment]
What's the status of this @MOZGIII ?

**Comment by MOZGIII** [comment]
Fix was merged at upstream yesterday, waiting for the next minikube release and we should be good to go.

Closing this issue as it's only for bug illustration.

**Pull request closed without merging**
