### PR TITLE
enhancement(vrl): Split VRL functions into Wasm compatible and incompatible

### PR DESCRIPTION
**Pull request by lucperkins**
This PR splits the VRL standard lib into Wasm-compatible and -incompatible functions. Although this isn't *yet* useful, it will be in the future when we begin running VRL in environments outside of Vector itself.

Two VRL functions, `get_hostname` and `parse_grok`, have dependencies that make them incompatible with the `wasm32-unknown-unknown` target. The `uuid_v4` function has a dependency (the `uuid` library) with an optional `wasm-bindgen` feature that makes it Wasm friendly. The approach here relies heavily on Rust's feature system to make the `default` feature of `vrl-stdlib` behave exactly as it currently does while also providing a `wasm` feature. I can't way I *love* this approach from a cognitive clarity perspective, but it definitely "works" just fine. I'm amenable to suggestions.

To verify that this division works as expected:

```bash
cd lib/vrl/stdlib
cargo check --target wasm32-unknown-unknown --no-default-features --features wasm_compatible # SUCCESS
cargo check --target wasm32-unknown-unknown #FAILURE
```

An alternative possibility here would be adding versions of the two incompatible functions that remain technically part of the stdlib but error when called, like so:

```bash
$ get_hostname()
the get_hostname function isn't available in this environment

# Or alternatively something fun:
"your_browser"
```

That could work something like this:

```toml
# Cargo.toml
wasm_compatible = ["default"]
```

```rust
// get_hostname.rs
#[cfg(not(feature = "wasm_compatible"))]
fn resolve(&self, _: &mut Context) -> Resolved {
    Ok(hostname::get()
        .map_err(|error| format!("failed to get hostname: {}", error))?
        .to_string_lossy()
        .into())
}

#[cfg(feature = "wasm_compatible")]
fn resolve(&self, _: &mut Context) -> Resolved {
    Err("the get_hostname function isn't available in this environment")
}
```

I have no strong feelings about the choice between excluding incompatible functions and the include-but-error approach. I do lean, however, toward simply excluding incompatible functions for the sake of Least Surprise.

### CODE REVIEW

**Review by JeanMertz — COMMENTED** [review]
Since I briefly mentioned this to @lucperkins on Discord, I wanted to add it here for context as well:

I think it's awesome that we're moving forward to making VRL work on the web 🎉. I do have some reservations on some of the changes being made in the Wasm-related PRs, and would like to defer merging these until after we've shipped 0.12, the Wasm-related RFC is merged, and there is a bit more bandwidth to move this work forward.

I'm not sure how much of this work was planned vs "hey this is cool and easy to do", but if it was planned, and we don't want to hold up the work, I'm also happy to see this merged sooner and us revisiting/refactoring the changes at a later date.

But I'll leave that up to @binarylogic and @lucperkins to decide.

**Comment by lucperkins** [comment]
@JeanMertz @binarylogic For the record, this work should be considered completely separate from the 0.12 effort and doesn't need to detain us right now. Some light-hearted experimentation yielded results more quickly than I expected, and I submitted PRs mostly to alert others to the existence of these efforts. I'll mark them as drafts for now just to make their non-urgent status more clear.

**Comment by jszwedko** [comment]
I'm personally a fan of returning having all functions defined in the "playground". For `get_hostname()` I think returning a static string is fine.

For `parse_grok` that is unfortunate. I'd prefer to return an error that the function is unsupported for now, but it might be nice to see if we can add support to the `grok` crate for wasm.

I guess the alternative is we don't go the WASM route and just execute the programs in a lambda somewhere.

**Comment by lucperkins** [comment]
@jszwedko I'm not sure we'd able to get grok parsing to work without writing our own. I looked into it and the `grok` library is based on `onig` which is a Rust wrapper over `oniguruma`, a C regex library to which it makes unsafe FFI calls. I can't quite decipher where in the chain Wasm support breaks down but it's a real thicket.

In terms of a Lambda function, I have written a web server for VRL that works fine for stateless ops. As I lay out in the RFC, though, the real barrier to functionality there is VRL state, which we'd have to implement SerDe for. That could be trivial or tricky; I haven't tried yet.

**Comment by jszwedko** [comment]
> In terms of a Lambda function, I have written a web server for VRL that works fine for ops that don't take compiler state as an input. But it's tricky because we'd need to also support passing state back and forth to the client as JSON. It might be fairly trivial to implement SerDe for VRL state or it might be thorny; I haven't tried. I do mention this in the RFC. I suspect it might be tricky given that `Compiler` is a [recursive](https://github.com/timberio/vector/blob/master/lib/vrl/compiler/src/state.rs#L27) type.

I was actually thinking about a stateless implementation where the inputs would be:

* Log event (probably JSON)
* Remap script

And the output would be the modified event.

I realize your prototype had an interactive element to it, but I think that the stateless approach would suffice for now.

**Comment by lucperkins** [comment]
@jszwedko Yep, that's what the server I wrote does. I can PR that at any time if people feel like the suggestions in the RFC are worth pursuing.

**Comment by lucperkins** [comment]
Closing this until we re-open discussion around "interactive VRL."

**Pull request closed without merging**
