### PR TITLE
fix(kubernetes platform): Fix reflector desync handling

### LINKED ISSUE #5877: Kubernetes Reflector Silently Drops Errors
Whilst investigating #5846 I realised that watch stream errors are silently dropped as `Reflector::process_stream_item` silently ignores any watch event without a resource version. This would have made it significantly easier to diagnose the incorrect desync detection in #5846 as the logs would have been filled with too old resource version errors

### PR DESCRIPTION
**Pull request by tustvold**
Closes #5877, #5846

Creating as draft whilst I test

### CODE REVIEW

**Comment by tustvold** [comment]
The metrics appear to be broken with this version but everything appears to be healthy based on the logs. I'll leave it to soak overnight in some test clusters and potentially test the changes rebased onto v0.11.1 in case there has been a regression in something on master.

**Comment by MOZGIII** [comment]
Thank you @tustvold! We've discussed the issue internally, and we'll likely be going with our own PR. Thanks a lot for reporting this issue and your PR!

**Comment by eeyun** [comment]
For some added context. This approach breaks an intentional abstraction between the watcher and reflector. The issue ultimately is a mismatch between http response code from the API and the response code embedded in the body. Our preferred path on this will be to maintain the separation between the watcher and reflector facilities and to parse out those different responses. PR will be inbound shortly.

**Comment by tustvold** [comment]
@eeyun @MOZGIII Understood and perfectly justified, this was a quick fix. I haven't observed a recurrence of vector getting stuck not detecting new log files when running a set of changes based on this PR, and so I am fairly confident that the incorrect status code handling is responsible for that issue, but I'm perfectly happy for you to fix it some other way :grinning:

**Comment by tustvold** [comment]
It is worth noting as this isn't clear from the very docs, and tbh I'm still a little unclear on the whole thing. The status payload indicating a desync is not necessarily the first or only payload sent over a watch stream, kubernetes rotates out watches every 295 seconds and on doing so notifies the client. This timeout is configurable and whilst testing this feature I have seen this packet get through to vector a couple of times. This is why I downgraded the desync log message to info from warn - as you will see it in production.

The result of this is that a successful watch request with an HTTP status code of 200 can occur and stream legitimate responses before becoming invalid at a later date. I imagine that kubernetes will close the connection on sending a desync, in which case not correctly handling this event just results in a redundant request with a stale resource version, but I don't know this to be the case.

I don't know enough about your proposed solution but it isn't so much that the API and the embedded response code mismatch as they represent different things.

**Pull request closed without merging**
