### PR TITLE
fix(website): small fixes for testing post

### PR DESCRIPTION
**Pull request by lukesteensen**
Two last small fixes.

### CODE REVIEW

**Comment by lukesteensen** [comment]
`make generate` is blowing up on something that seems unrelated, so I'm hoping it did enough to pass here.

```
Error:                            
                                                                                               
  Method `source` does not exist on:
                                                                                               
  AccessibleHash<{"title"=>"Daemon", "name"=>"daemon"}>
                                                                                               
  /home/luke/code/vector/scripts/util/core_ext/accessible_hash.rb:17:in `method_missing'
```

Seems like the relevant part.

**Comment by binarylogic** [comment]
I really don't understand that error. It was fixed in https://github.com/timberio/vector/pull/2205. :/

**Comment by lukesteensen** [comment]
Here's the full error output:

```
Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                                                                                                                                                                 [54/669]
        16: from scripts/generate.rb:372:in `<main>'                                                                      
        15: from scripts/generate.rb:372:in `each'                                                                        
        14: from scripts/generate.rb:375:in `block in <main>'                                                             
        13: from /home/luke/code/vector/scripts/generate/templates.rb:513:in `render'                                     
        12: from /usr/local/lib/ruby/2.7.0/erb.rb:905:in `result'                                                         
        11: from /usr/local/lib/ruby/2.7.0/erb.rb:905:in `eval'                                                           
        10: from (erb):54:in `render'                                                                                     
         9: from /home/luke/code/vector/scripts/generate/templates.rb:279:in `installation_tutorial'                                                                                                                                                 
         8: from /home/luke/code/vector/scripts/generate/templates.rb:513:in `render'                                     
         7: from /usr/local/lib/ruby/2.7.0/erb.rb:905:in `result'                                                         
         6: from /usr/local/lib/ruby/2.7.0/erb.rb:905:in `eval'                                                           
         5: from (erb):5:in `installation_tutorial'                                                                       
         4: from (erb):5:in `each'                                                                                        
         3: from (erb):23:in `block in installation_tutorial'                                                             
         2: from (erb):23:in `each'                                                                                                                                                                                                                  
         1: from (erb):26:in `block (2 levels) in installation_tutorial'                                                  
/home/luke/code/vector/scripts/util/core_ext/accessible_hash.rb:17:in `method_missing': Method `source` does not exist on: (NoMethodError)                                                                                                           
                                                                                                                          
  AccessibleHash<{"title"=>"Daemon", "name"=>"daemon"}>                                                                   
        9: from scripts/generate.rb:372:in `<main>'                                                                       
        8: from scripts/generate.rb:372:in `each'                                                                         
        7: from scripts/generate.rb:375:in `block in <main>'                                                              
        6: from /home/luke/code/vector/scripts/generate/templates.rb:513:in `render'                                      
        5: from /usr/local/lib/ruby/2.7.0/erb.rb:905:in `result'                                                          
        4: from /usr/local/lib/ruby/2.7.0/erb.rb:905:in `eval'                                                            
        3: from (erb):54:in `render'                                                                                      
        2: from /home/luke/code/vector/scripts/generate/templates.rb:279:in `installation_tutorial'                                                                                                                                                  
        1: from /home/luke/code/vector/scripts/generate/templates.rb:514:in `render'                                      
/home/luke/code/vector/scripts/generate/templates.rb:515:in `rescue in render': Error rendering template! (RuntimeError)                                                                                                                             
                                                                                                                          
  /scripts/generate/templates/_partials/_installation_tutorial.md.erb                                                     
                                                                                                                          
Error:                                                                                                                    
                                                                                                                          
  Method `source` does not exist on:                                                                                      
                                                                                                                          
  AccessibleHash<{"title"=>"Daemon", "name"=>"daemon"}>                                                                   
                                                                                                                          
  /home/luke/code/vector/scripts/util/core_ext/accessible_hash.rb:17:in `method_missing'                                  
  (erb):26:in `block (2 levels) in installation_tutorial'                                                                 
  (erb):23:in `each'                                                                                                      
  (erb):23:in `block in installation_tutorial'                                                                            
  (erb):5:in `each'                                                                                                       
  (erb):5:in `installation_tutorial'                                                                                      
  /usr/local/lib/ruby/2.7.0/erb.rb:905:in `eval'                                                                          
  /usr/local/lib/ruby/2.7.0/erb.rb:905:in `result'                                                                        
  /home/luke/code/vector/scripts/generate/templates.rb:513:in `render'                                                    
  /home/luke/code/vector/scripts/generate/templates.rb:279:in `installation_tutorial'                                     
  (erb):54:in `render'                                                                                                    
  /usr/local/lib/ruby/2.7.0/erb.rb:905:in `eval'                                                                          
  /usr/local/lib/ruby/2.7.0/erb.rb:905:in `result'                                                                        
  /home/luke/code/vector/scripts/generate/templates.rb:513:in `render'                                                    
  scripts/generate.rb:375:in `block in <main>'                                                                            
  scripts/generate.rb:372:in `each'                                                                                       
  scripts/generate.rb:372:in `<main>'                                                                                     
        4: from scripts/generate.rb:372:in `<main>'                                                                       
        3: from scripts/generate.rb:372:in `each'                                                                         
        2: from scripts/generate.rb:375:in `block in <main>'                                                              
        1: from /home/luke/code/vector/scripts/generate/templates.rb:514:in `render'                                      
/home/luke/code/vector/scripts/generate/templates.rb:515:in `rescue in render': Error rendering template! (RuntimeError)                                                                                                                             

  /website/guides/getting-started/deploying.md.erb                                                                        

Error:                                                                                                                    

  Error rendering template!                                                                                               

  /scripts/generate/templates/_partials/_installation_tutorial.md.erb                                                     

Error:                                                                                                                    

  Method `source` does not exist on:                                                                                      

  AccessibleHash<{"title"=>"Daemon", "name"=>"daemon"}>                                                                   

  /home/luke/code/vector/scripts/util/core_ext/accessible_hash.rb:17:in `method_missing'                                  
  (erb):26:in `block (2 levels) in installation_tutorial'                                                                 
  (erb):23:in `each'                                                                                                      
  (erb):23:in `block in installation_tutorial'                                                                            
  (erb):5:in `each'                                                                                                       
  (erb):5:in `installation_tutorial'                                                                                      
  /usr/local/lib/ruby/2.7.0/erb.rb:905:in `eval'                                                                          
  /usr/local/lib/ruby/2.7.0/erb.rb:905:in `result'                                                                        
  /home/luke/code/vector/scripts/generate/templates.rb:513:in `render'                                                    
  /home/luke/code/vector/scripts/generate/templates.rb:279:in `installation_tutorial'                                     
  (erb):54:in `render'                                                                                                    
  /usr/local/lib/ruby/2.7.0/erb.rb:905:in `eval'                                                                          
  /usr/local/lib/ruby/2.7.0/erb.rb:905:in `result'                                                                        
  /home/luke/code/vector/scripts/generate/templates.rb:513:in `render'                                                    
  scripts/generate.rb:375:in `block in <main>'                                                                            
  scripts/generate.rb:372:in `each'                                                                                       
  scripts/generate.rb:372:in `<main>'                                                                                     


  /home/luke/code/vector/scripts/generate/templates.rb:515:in `rescue in render'                                          
  /home/luke/code/vector/scripts/generate/templates.rb:514:in `render'                                                    
  /home/luke/code/vector/scripts/generate/templates.rb:279:in `installation_tutorial'                                     
  (erb):54:in `render'                                                                                                    
  /usr/local/lib/ruby/2.7.0/erb.rb:905:in `eval'                                                                          
  /usr/local/lib/ruby/2.7.0/erb.rb:905:in `result'                                                                        
  /home/luke/code/vector/scripts/generate/templates.rb:513:in `render'                                                    
  scripts/generate.rb:375:in `block in <main>'                                                                            
  scripts/generate.rb:372:in `each'                                                                                       
  scripts/generate.rb:372:in `<main>'                                                                                     
make: *** [Makefile:65: generate] Error 1                                                                                 
```

**Comment by binarylogic** [comment]
Ok, I believe I fixed where it is happening. It's still odd that it doesn't happen to me.

**Pull request merged**
