### PR TITLE
chore(operations): Build .deb packages for all musl targets

### PR DESCRIPTION
**Pull request by a-rodin**
Closes https://github.com/timberio/vector/issues/1213, closes https://github.com/timberio/vector/issues/860.

### CODE REVIEW

**Comment by binarylogic** [comment]
Nice! We'll need to update the `dpkg` instructions to handle the new archs, correct?

**Comment by a-rodin** [comment]
@binarylogic I think we could change the first two installation steps [here](https://vector.dev/docs/setup/installation/package-managers/dpkg) to

```bash
curl -O https://packages.timber.io/vector/latest/vector-$(dpkg --print-architecture).deb
```

and

```bash
sudo dpkg -i vector-$(dpkg --print-architecture).deb
```

to make them invariant with respect to machine architecture.

**Comment by binarylogic** [comment]
Sounds good. I'd like to make the documentation changes in this PR before merging.

**Comment by a-rodin** [comment]
@binarylogic I've updated the documentation for DPKG packages: https://deploy-preview-1247--vector-project.netlify.com/docs/setup/installation/package-managers/dpkg. Besides documentation I think it is ready for merging.

**Comment by binarylogic** [comment]
Looks great!

> Besides documentation I think it is ready for merging.

What else in the documentation needs to change?

**Comment by a-rodin** [comment]
> What else in the documentation needs to change?

I changed everything related to Deb package that I found in the documentation, just was not sure if I missed something or not.

**Pull request merged**
