### PR TITLE
enhancement(remap): Update VRL CLI behavior

### PR DESCRIPTION
**Pull request by lucperkins**
I'd like to get feedback on the general direction before I go further. Here are the basic changes:

* All references to "programs" in user-facing text have been changed to "script," for the sake of consistency with the docs. Other wording has been changed in some of the user-facing descriptions as well.
* The REPL is entered if no script or script file is specified. `vector vrl` by itself now opens the REPL; without this change, `vector vrl` by itself basically just hangs. Another option might be that `vector vrl` on its own throws an error and a `--repl` flag is required to use the REPL.
* You can still specify an `--input` for the REPL. But if you don't, a default `{"foo":"bar"}` object is provided. This means that the default behavior for `vector vrl` is to open the REPL with a default object, which I think is more intuitive. I'm fully open to suggestion on what the default object(s) could be. This may be a good avenue for giving users realistic event objects to play with.

Otherwise, the behavior is unchanged. Personally, I find this behavior more intuitive but I'm fully open to suggestion.

The modest goal of this PR is to get the CLI to a place where we're comfortable releasing it in 0.12.

### CODE REVIEW

**Review by JeanMertz — COMMENTED** [review]
> All references to "programs" in user-facing text have been changed to "script," for the sake of consistency with the docs. Other wording has been changed in some of the user-facing descriptions as well.

I believe we decided to use "program" in the docs, so this is no longer relevant.

>     * The REPL is entered if no script or script file is specified. `vector vrl` by itself now opens the REPL; without this change, `vector vrl` by itself basically just hangs.

👍 

One thing that should continue to work is the ability to do:

```
echo '{ "foo": "bar" }' | cargo run .foo
"bar"
```

If that still works, then I'm happy with your proposal.

>     * You can still specify an `--input` for the REPL. But if you don't, a default `{"foo":"bar"}` object is provided.

👍 

>     * This may be a good avenue for giving users realistic event objects to play with.

👍

**Comment by lucperkins** [comment]
@JeanMertz Okay, I've undone the s/program/script and yes, the previous stdin behavior still works, so I think we're good to go here

**Review by JeanMertz — APPROVED** [review]

**Comment by jszwedko** [comment]
> You can still specify an --input for the REPL. But if you don't, a default {"foo":"bar"} object is provided.

My preference is actually for `{}` to be provided. That is: an empty object.

:+1: on making the default to open the REPL though.

**Comment by lucperkins** [comment]
@jszwedko Okay, let's go with an empty object for now and reconsider later. Eventually I'd like a guided tutorial for the REPL with more realistic examples but that can wait.

**Pull request merged**
