### PR TITLE
feat(azure_monitor_logs sink): Add support for dedicated Azure region

### LINKED ISSUE #4464: Support for Country Specific Azure Cloud Endpoints
Hi Team,

- Thank you for providing Azure Monitor Sink.

- It would be nice, if an optional "endpoint" parameter can be provided, which will let user specify different Azure Clouds (e.g. Azure China Cloud, Azure US Gov Cloud).

- Currrently, the link is hardcoded in this [file](https://github.com/timberio/vector/blob/master/src/sinks/azure_monitor_logs.rs), line number 181. `"https://{}.ods.opinsights.azure.com{}?api-version={}",`

- For e.g. Azure China Cloud would use `ods.opinsights.azure.cn`. Found it [here](https://docs.azure.cn/en-us/articles/guidance/developerdifferences#check-endpoints-in-azure)

- Found this idea on [rclone page](https://rclone.org/azureblob/#azureblob-endpoint)

Thanks,
Specterz

### PR DESCRIPTION
**Pull request by nazar554**
Closes #4464

### CODE REVIEW

**Comment by nazar554** [comment]
It seems that `azure_monitor_logs sink` is missing in [`semantic.yml`](https://github.com/timberio/vector/blob/master/.github/semantic.yml), not sure how to add it though.

**Comment by binarylogic** [comment]
Thanks for this! I'll add it.

**Comment by nazar554** [comment]
Should pass CI when #4508 is merged in master & this branch

**Comment by binarylogic** [comment]
@jszwedko @ktff should this be named `host` or `endpoint` given the usage here?

**Review by jszwedko — COMMENTED** [review]
Thanks for this!

Do you think we could pull up the `https://` into the required config for `endpoint`? Such that users would write something like: `endpoint = "https://ods.opinsights.azure.com~`? I think that would:

* Align this with other usages of `endpoint` in `vector` which require the scheme
* Allow users to more easily point this at mock implementations which may not be running HTTPS

I do see that the customer ID is later encoded into the URL though, which makes this a bit different than how AWS treats them, but I see that `anything.localhost` still resolves to localhost so it should still suffice for supporting local mock services.

Alternatively, we could require the user to configure the full endpoint including the customer ID, but this feels redundant with the `customer_id` field (also used for authentication).

If we choose not to encode the scheme, I do think `host` would better match as a name for this config option to better match other usages of domains, as opposed to URIs, in vector.

**Comment by nazar554** [comment]
@jszwedko Done, renamed it to `host`

**Review by jszwedko — APPROVED** [review]
This looks good to me. Thanks! I'll let @ktff chime in too.

**Review by ktff — APPROVED** [review]
Looks good, and I agree that name `host` is a better fit.

**Pull request merged**
