### PR TITLE
chore(performance): Consider dropping jemalloc

### PR DESCRIPTION
**Pull request by jszwedko**
Pushing this up just to see what the benchmarks look like now.

This was prompted because we ran into a bug that only occurs in release
builds using jemalloc:
https://github.com/timberio/vector/issues/6726#issuecomment-800410163

@FungusHumungus is still looking into the bug, but in parallel, I think
we should consider dropping the jemallocator crate,
https://github.com/gnzlbg/jemallocator, and just using the system
allocator as:

* It doesn't seem well-maintained now given that the last release was
  almost two years ago, issues/PRs are stale, and it is behind on
  jemalloc versions (5.1 vs. 5.2.1)
* The original benchmarks for its introduction,
  https://github.com/timberio/vector/pull/310, aren't dramatically
  different. They are improved, for sure, but I'm unsure that it's worth
  the trade-offs of using the non-standard allocator and I have the
  feeling there are much lower hanging fruit for us to pick first. Granted
  that jemalloc's goal of reducing memory fragmentation might not be
  as noticeable in the short-lived benches we have here.

cc/ @lukesteensen @blt I assume you might have thoughts here.

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Review by blt — APPROVED** [review]
I am very, very pro using the system allocator. This combined with #6181 strikes me as a pretty ideal state.

**Comment by jszwedko** [comment]
I found more benches: https://github.com/timberio/vector/issues/1985#issuecomment-670667972

Again, there is an improvement over the system allocator, but not a very large one.

**Comment by bruceg** [comment]
> I found more benches: [#1985 (comment)](https://github.com/timberio/vector/issues/1985#issuecomment-670667972)
> 
> Again, there is an improvement over the system allocator, but not a very large one.

I'm not sure I would agree with "not a very large improvement". Assuming I'm reading the numbers right, both lines_per_sec and bytes_per_sec on tcp_to_tcp with 2 threads is ~66% faster with jemalloc than the system malloc. That's huge. Granted, many of the other numbers are just ~10% improvement, and that's not large, but there are some very large differences.

**Comment by jszwedko** [comment]
> > I found more benches: [#1985 (comment)](https://github.com/timberio/vector/issues/1985#issuecomment-670667972)
> > Again, there is an improvement over the system allocator, but not a very large one.
> 
> I'm not sure I would agree with "not a very large improvement". Assuming I'm reading the numbers right, both lines_per_sec and bytes_per_sec on tcp_to_tcp with 2 threads is ~66% faster with jemalloc than the system malloc. That's huge. Granted, many of the other numbers are just ~10% improvement, and that's not large, but there are some very large differences.

Ah, you are right, I glossed over those ones. Those are more substantial at high thread counts. I'll try to rerun similar benches now and see if they still reflect that difference.

**Comment by jszwedko** [comment]
Luke sent me the code he used to run those benchmarks and I think I was able to run an equivalent one just for tcp_to_tcp/gnu/8 threads with malloc vs jemalloc on `x86_64-unknown-linux-gnu`.

I saw a roughly 10% improvement with jemalloc compared with the 56% shown in the previous benches:

```
gnu/8 threads

system:
lines per sec: 52720 (1) 
bytes per sec: 11652827 (1)

jemalloc:

lines per sec: 57888 (1.09)
bytes per sec: 12795261 (1.09)
```

It warrants some more testing, but it seems the gap _may_ have closed due to other changes.

**Comment by jszwedko** [comment]
Update on this:

I was originally going to table this after some discussion with Luke about the poor performance of musl's liballoc in multi-threaded environment, however, I had some more discussion with Brian (thank you!) that convinced me that defaulting to the system allocator may still be a better default. An argument follows:

The primary motivator for using musl, and thus greatly benefiting from jemalloc in multi-threaded environments, is with alpine docker images. Users typically choose alpine images for size reasons; however, we also publish distroless images that include libc that are only 5MB larger (which, coincidentally is also bump in size that results from including jemalloc; https://github.com/timberio/vector/pull/310).

0.12.1 images:

```
timberio/vector                               0.12.1-distroless-libc     a01c8409bacb   4 days ago      93MB
timberio/vector                               0.12.1-distroless-static   b61e0880d16c   4 days ago      82.4MB
timberio/vector                               0.12.1-alpine              ef029e56b5ee   4 days ago      88MB
timberio/vector                               0.12.1-debian              2ccea0b5ffdb   4 days ago      164MB
```

Given this, it seems like we can encourage users to install the `0.12.1-distroless-libc` image as the image of choice for size conscious installs. Distroless also has the security advantage by providing less in the container itself .

Additionally, jemalloc is preferred for certain workloads but it doesn't seem like we have an understanding of vector's allocation profile yet and which strategies will result in the best performance. Until we have a very strong reason to, just defaulting to the system allocator seems like a good default.

Thus the proposal is to:

* Default to the system allocator
* Make it easy to swap the allocator to test out different allocators in the future
* Strongly highlight this change with the 0.13 release and encourage anyone using a musl-based build to consider whether the glibc build would be usable for them.

**Comment by lukesteensen** [comment]
That sounds reasonable to me! I suspect there will still be some users who want alpine for organizational or other reasons, but as long as we document the change and provide something that's roughly equivalent then I think that's fine.

**Review by ktff — APPROVED** [review]

**Comment by jszwedko** [comment]
@blt I was thinking of merging this after the release next Tuesday to give it some time to bake before it'd be released.

**Comment by blt** [comment]
@jszwedko I'm for it.

**Pull request merged**
