### PR TITLE
chore: add clippy rule trivially_copy_pass_by_ref

### PR DESCRIPTION
**Pull request by fanatid**
While checked [needless_lifetime](https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes) rule in https://github.com/timberio/vector/pull/5771#discussion_r550790780 found that [trivially_copy_pass_by_ref](https://rust-lang.github.io/rust-clippy/master/#trivially_copy_pass_by_ref) can be useful.

### CODE REVIEW

**Review by JeanMertz — APPROVED** [review]

**Review by bruceg — COMMENTED** [review]
This should probably also set `trivial-copy-size-limit` to something more reasonable than `None` so it doesn't accidentally force copying something that can't reasonably be fit into registers.

**Comment by binarylogic** [comment]
@bruceg can you open an issue for that and/or submit a PR?

**Comment by fanatid** [comment]
@bruceg if I understand correctly from the docs `None` will be good for us because the limit is target size dependent in this case.

**Comment by bruceg** [comment]
Hmm, the docs just say the limit is `None`, which I took to mean there is no limit, ie the lint will apply to all objects with the `Copy` trait. I am relieved to know it will only apply to small objects by default, so that's good enough.

**Pull request merged**
