### PR TITLE
enhancement(syslog source): Improve best effort support for Syslog formats (5424, 3164, nginx style, etc)

### LINKED ISSUE #741: Support syslog rfc 3164
My use case : I want to use vector to parse & ship my json (custom)-formatted nginx logs.

Sadly vector support RFC 5424 and nginx only RFC 3164.
Are there plans to add support for the older RFC 3164 ?

### LINKED ISSUE #1454: Parse nginx style syslog messages
The `syslog` source conforms for the Syslog5424 spec, but not all tools follow it strictly. We should make a best effort to parse common Syslog formats, even if they deviate from the spec. An example of this is Nginx logs:

```
<190>Dec 28 16:49:07 plertrood-thinkpad-x220 nginx: 127.0.0.1 - - [28/Dec/2019:16:49:07 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
```

The `syslog` source should parse this.

### PR DESCRIPTION
**Pull request by FungusHumungus**
This uses the syslog_loose library for parsing syslog messages. The library aims to parse both RFC 5424 and RFC 3164 messages to extract as much useful information as possible rather than sticking strictly to the standard. No message is invalid, at worse the whole message becomes the message text, and the current time and default_host are taken.

Closes #741
Closes #1454

Signed-off-by: Stephen Wakely <fungus.humungus@gmail.com>

### CODE REVIEW

**Comment by binarylogic** [comment]
Nice! Thank you for this. I'll update our docs to clarify the changes here.

**Comment by FungusHumungus** [comment]
Ah, yes, apologies, I neglected to go through the docs. I'm happy to go through this if you would prefer. Let me know..

**Comment by binarylogic** [comment]
You're right. I'll fix.

**Comment by FungusHumungus** [comment]
Awesome, thanks for merging! That was a lot of fun. If you do come across any messages that aren't parsed correctly, please feel free to raise an issue here https://github.com/FungusHumungus/syslog-loose and i'll see what I can do.

**Comment by binarylogic** [comment]
Absolutely! We'll do that. And if you find a burning desire to contribute more to Vector please feel free. We have a lot of interesting issues, we'd be happy to discuss any of them.

**Comment by FungusHumungus** [comment]
Cool, yeah I'd be happy to grab another issue. Is gitter the best place to discuss?

**Comment by binarylogic** [comment]
Yep! I wish Gitter was actually nice to use, but it's the easiest community platform we've seen so far. We can also invite you to our Slack channel if you want to collaborate more on things.

**Pull request merged**
