### PR TITLE
enhancement(observability): emit component utilization as a metric

### LINKED ISSUE #7982: Export 'utilization' numbers as telemetry
We have the concept of 'utilization' that appears in our logs but not in vector's telemetry stream. We'd like to change this. Success here is a utilization metric that can be graphed in our soak boards, tagged by component in the manner of our `component_name`, `component_kind` concept.

### PR DESCRIPTION
**Pull request by lukesteensen**
Closes #7982 

Pretty darn simple, but gets the job done. I opted to leave the existing debug logs for now, but don't feel strongly about it.

### CODE REVIEW

**Review by blt — APPROVED** [review]
Short and sweet. I'm pro the debug log.

**Review by jszwedko — APPROVED** [review]
I'd be down with dropping the debug log. They can always log it via piping `internal_metrics` to `console`.

**Comment by binarylogic** [comment]
Just curious, any reason we didn't follow the event pattern here? Performance?

**Comment by lukesteensen** [comment]
@binarylogic there isn't a meaningful event happening when we emit this, so I didn't think it fit the pattern. It's also already happening in a dedicated module, so I didn't see a benefit to extracting it further.

**Pull request merged**
