### PR TITLE
enhancement(config): Document `vector top` CLI

### PR DESCRIPTION
**Pull request by lucperkins**
This PR complements #4886 by adding Cue sources for the CLI.

### CODE REVIEW

**Comment by leebenson** [comment]
@lucperkins, sorry for the delay in reviewing this. I was waiting for #4945 to land, which cements the `-h` feature and can now be added to the docs.

**Comment by lucperkins** [comment]
No worries! I'll update this to reflect that.

**Comment by lucperkins** [comment]
@leebenson This has now been updated to reflect #4945

**Review by leebenson — APPROVED** [review]
LGTM 👍

**Pull request merged**
