### PR TITLE
chore: Small host of clippy fixes

### PR DESCRIPTION
**Pull request by blt**
This commit wraps up a small batch of fixes suggested by clippy. Most are either
removal of code that will break in Rust 2021 or are small optimizations, like
the move to use `flatten` and `&Path` instead of `&PathBuf`.

Signed-off-by: Brian L. Troutwine <brian@troutwine.us>

### CODE REVIEW

**Review by FungusHumungus — APPROVED** [review]
Nice, I don't know why it hadn't occured to me to use flatten before!

**Review by jszwedko — APPROVED** [review]
👍 I dig it. I also wouldn't have thought to use `flatten()` like that.

**Comment by jszwedko** [comment]
@blt how did you run clippy to get those warnings? Should we be getting them in CI?

**Comment by blt** [comment]
@FungusHumungus @jszwedko Yep! If clippy hadn't suggested it I wouldn't have considered using flatten that way either. TIL.

As to how I ran this, I run clippy like so locally: `cargo +nightly clippy -Z unstable-options`. The `unstable-options` ensures that clippy runs itself over every file in the project, compiled or not. Otherwise clippy'll only lint what's fresh. I run `+nightly` to get new lints but that can be noisy if there's changes in nightly but not stable. 

I can take a peak at how we run clippy in CI. Haven't looked at it.

**Pull request merged**
