### PR TITLE
chore: Fix fix_retry_until_after_timeout by adding panic message

### PR DESCRIPTION
**Pull request by jamtur01**
Signed-off-by: James Turnbull <james@lovedthanlost.net>

### CODE REVIEW

**Review by JeanMertz — APPROVED** [review]
I'm happy to merge this, but I'm not sure how this fixes anything.

From what I understand, the `expected` parameter _narrows_ the accepted panics, so any test using this function would fail more often, if this function panic'ed with any message that doesn't contain `Timeout`, correct?

**Comment by leebenson** [comment]
I'm confused by this too. I'm also not clear why this only shows up on macOS tests, and doesn't happen locally for me on macOS.

**Comment by jamtur01** [comment]
Yeah I am unclear too. :(

**Comment by jamtur01** [comment]
And I try and run it again this morning and it fails. 😂

**Pull request closed without merging**
