### PR TITLE
chore: Split up event

### PR DESCRIPTION
**Pull request by Hoverbear**
Part of #2841, continues in the spirit of #3601.

This splits up the `event.rs` file into `log_event.rs`, `event.rs`, and `log_schema.rs`.

This also migrates `log_schema` into `crate::config::log_schema`.

This doesn't actually change any behavior, just reorganization.

### CODE REVIEW

**Comment by Hoverbear** [comment]
@bruceg Great idea. :) I'm going to leave that task for monday me!

**Comment by Hoverbear** [comment]
Okay I feel like that's a good push that way.

**Comment by bruceg** [comment]
Yes, that looks better. :+1:

**Review by ktff — APPROVED** [review]

**Review by fanatid — APPROVED** [review]

**Comment by Hoverbear** [comment]
Waiting for CI....

**Pull request merged**
