### PR TITLE
chore(metrics): switch to upstream Registry impl for metrics

### PR DESCRIPTION
**Pull request by tobz**
This PR switches to the upstream `Registry` from `metrics_util`, since it was recently reworked to replace `dashmap` with per-metric-kind sharded maps, as well as `HashMap` performance optimizations that, ultimately, provide better performance.

Early numbers are promising for overall throughput:
```
metrics/on/topology/tcp_socket/01_writer                                                                            
        time:   [52.070 ms 53.784 ms 55.978 ms]
        thrpt:  [17.036 MiB/s 17.732 MiB/s 18.315 MiB/s]
    change:
        time:   [-20.737% -17.826% -14.166%] (p = 0.00 < 0.05)
        thrpt:  [+16.504% +21.693% +26.162%]
        Performance has improved.
```

Still a work-in-progress as we haven't run the change through the gauntlet of benchmarks to make sure there's no regressions.

### CODE REVIEW

**Comment by blt** [comment]
Neat. To get a sense of how this affects all-up vector take a look at [this](https://github.com/timberio/vector-test-harness/blob/d1d44a573c6f70a83c3beb16ee733555d0c28d95/cases/performance/klog_remap_to_blackhole/vector.sh). In bits and pieces we've started putting what we'd like to see for integrated vector performance testing, limitation being it has to run on a Linux host and it only works for vector configs that terminate, which is not most vector configs.

**Comment by tobz** [comment]
Top-line numbers for this change look solid:

```
PROCESSING: remap-multihop.toml
Benchmark #1: zcat baked.log.gz | /home/toby/src/vector-test-harness/cases/performance/klog_remap_to_blackhole/bin/vector-206876830474100d6f23a9c498bcf9deccccc104 -qq --config /home/toby/src/vector-test-harness/cases/performance/klog_remap_to_blackhole/configs/remap-multihop.toml
  Time (mean ± σ):     17.715 s ±  0.406 s    [User: 81.271 s, System: 9.137 s]
  Range (min … max):   17.208 s … 18.553 s    10 runs
 
Benchmark #2: zcat baked.log.gz | /home/toby/src/vector-test-harness/cases/performance/klog_remap_to_blackhole/bin/vector-746a8d22c22763ab9533e880974cdf41b60bedc1 -qq --config /home/toby/src/vector-test-harness/cases/performance/klog_remap_to_blackhole/configs/remap-multihop.toml
  Time (mean ± σ):     16.866 s ±  0.639 s    [User: 76.627 s, System: 9.996 s]
  Range (min … max):   15.947 s … 17.732 s    10 runs
 
Summary
  'zcat baked.log.gz | /home/toby/src/vector-test-harness/cases/performance/klog_remap_to_blackhole/bin/vector-746a8d22c22763ab9533e880974cdf41b60bedc1 -qq --config /home/toby/src/vector-test-harness/cases/performance/klog_remap_to_blackhole/configs/remap-multihop.toml' ran
    1.05 ± 0.05 times faster than 'zcat baked.log.gz | /home/toby/src/vector-test-harness/cases/performance/klog_remap_to_blackhole/bin/vector-206876830474100d6f23a9c498bcf9deccccc104 -qq --config /home/toby/src/vector-test-harness/cases/performance/klog_remap_to_blackhole/configs/remap-multihop.toml'
PROCESSING: remap-nohop.toml
Benchmark #1: zcat baked.log.gz | /home/toby/src/vector-test-harness/cases/performance/klog_remap_to_blackhole/bin/vector-206876830474100d6f23a9c498bcf9deccccc104 -qq --config /home/toby/src/vector-test-harness/cases/performance/klog_remap_to_blackhole/configs/remap-nohop.toml
  Time (mean ± σ):     26.889 s ±  0.688 s    [User: 70.222 s, System: 11.223 s]
  Range (min … max):   25.823 s … 27.807 s    10 runs
 
Benchmark #2: zcat baked.log.gz | /home/toby/src/vector-test-harness/cases/performance/klog_remap_to_blackhole/bin/vector-746a8d22c22763ab9533e880974cdf41b60bedc1 -qq --config /home/toby/src/vector-test-harness/cases/performance/klog_remap_to_blackhole/configs/remap-nohop.toml
  Time (mean ± σ):     26.076 s ±  0.581 s    [User: 66.476 s, System: 11.309 s]
  Range (min … max):   25.114 s … 27.107 s    10 runs
 
Summary
  'zcat baked.log.gz | /home/toby/src/vector-test-harness/cases/performance/klog_remap_to_blackhole/bin/vector-746a8d22c22763ab9533e880974cdf41b60bedc1 -qq --config /home/toby/src/vector-test-harness/cases/performance/klog_remap_to_blackhole/configs/remap-nohop.toml' ran
    1.03 ± 0.04 times faster than 'zcat baked.log.gz | /home/toby/src/vector-test-harness/cases/performance/klog_remap_to_blackhole/bin/vector-206876830474100d6f23a9c498bcf9deccccc104 -qq --config /home/toby/src/vector-test-harness/cases/performance/klog_remap_to_blackhole/configs/remap-nohop.toml'
PROCESSING: stdin_to_blackhole.toml
Benchmark #1: zcat baked.log.gz | /home/toby/src/vector-test-harness/cases/performance/klog_remap_to_blackhole/bin/vector-206876830474100d6f23a9c498bcf9deccccc104 -qq --config /home/toby/src/vector-test-harness/cases/performance/klog_remap_to_blackhole/configs/stdin_to_blackhole.toml
  Time (mean ± σ):      6.688 s ±  0.212 s    [User: 12.925 s, System: 2.277 s]
  Range (min … max):    6.367 s …  7.036 s    10 runs
 
Benchmark #2: zcat baked.log.gz | /home/toby/src/vector-test-harness/cases/performance/klog_remap_to_blackhole/bin/vector-746a8d22c22763ab9533e880974cdf41b60bedc1 -qq --config /home/toby/src/vector-test-harness/cases/performance/klog_remap_to_blackhole/configs/stdin_to_blackhole.toml
  Time (mean ± σ):      5.313 s ±  0.097 s    [User: 10.322 s, System: 2.141 s]
  Range (min … max):    5.153 s …  5.453 s    10 runs
 
Summary
  'zcat baked.log.gz | /home/toby/src/vector-test-harness/cases/performance/klog_remap_to_blackhole/bin/vector-746a8d22c22763ab9533e880974cdf41b60bedc1 -qq --config /home/toby/src/vector-test-harness/cases/performance/klog_remap_to_blackhole/configs/stdin_to_blackhole.toml' ran
    1.26 ± 0.05 times faster than 'zcat baked.log.gz | /home/toby/src/vector-test-harness/cases/performance/klog_remap_to_blackhole/bin/vector-206876830474100d6f23a9c498bcf9deccccc104 -qq --config /home/toby/src/vector-test-harness/cases/performance/klog_remap_to_blackhole/configs/stdin_to_blackhole.toml'
```

`746a8d22c22763ab9533e880974cdf41b60bedc1` is this PR, `746a8d22c22763ab9533e880974cdf41b60bedc1` was `master` as of a little while ago.

Gonna press forward and actually get this pointed at real crate versions, etc.

**Comment by tobz** [comment]
Just pulling out the comparisons from the benchmarks to highlight the wins:

```
topology/pipe/simple                                                        47.456 ms  -13.329%     20.096 MiB/s    +15.379%           0.00  none
topology/pipe/small_lines                                                   38.240 ms  -17.782%     255.38 KiB/s    +21.627%           0.00  none
topology/pipe/big_lines                                                     177.16 ms  +7.0651%     107.66 MiB/s    -6.5989%           0.00  none
topology/pipe/multiple_writers                                              49.011 ms  -13.463%     1.9458 MiB/s    +15.558%           0.00  none
topology/interconnected                                                     123.05 ms  -15.136%     15.500 MiB/s    +17.835%           0.00  none
topology/transforms                                                         80.880 ms  -14.377%     12.970 MiB/s    +16.791%           0.00  none
topology/complex                                                            2.8046 s   -14.005%     unknown         unknown            0.00  none
topology/real_world_1                                                       3.3701 s   -8.7427%     29.672 Kelem/s  +9.5802%           0.00  none
metrics/no_tracing_integration/topology/tcp_socket/01_writer                32.972 ms  -21.240%     28.924 MiB/s    +26.968%           0.00  improved
metrics/no_tracing_integration/topology/tcp_socket/02_writers               67.527 ms  -22.183%     28.246 MiB/s    +28.507%           0.00  improved
metrics/no_tracing_integration/topology/tcp_socket/04_writers               135.75 ms  -22.518%     28.102 MiB/s    +29.062%           0.00  improved
metrics/no_tracing_integration/topology/tcp_socket/08_writers               276.92 ms  -21.728%     27.551 MiB/s    +27.759%           0.00  improved
metrics/no_tracing_integration/topology/tcp_socket/16_writers               588.63 ms  -20.805%     25.923 MiB/s    +26.271%           0.00  improved
metrics/no_tracing_integration/micro/bare_counter                           30.060 ns  -80.664%     unknown         unknown            0.00  improved
metrics/no_tracing_integration/micro/bare_counter_with_static_labels        34.776 ns  -84.230%     unknown         unknown            0.00  improved
metrics/no_tracing_integration/micro/bare_counter_with_dynamic_labels       148.43 ns  -60.275%     unknown         unknown            0.00  improved
metrics/no_tracing_integration/micro/ununsed_span                           30.145 ns  -80.663%     unknown         unknown            0.00  improved
metrics/no_tracing_integration/micro/span_enter_without_counter             202.33 ns  -0.4991%     unknown         unknown            0.00  none
metrics/no_tracing_integration/micro/span_no_labels                         229.67 ns  -36.193%     unknown         unknown            0.00  improved
metrics/no_tracing_integration/micro/span_with_1_static_label               231.10 ns  -36.078%     unknown         unknown            0.00  improved
metrics/no_tracing_integration/micro/span_with_2_static_labels              231.82 ns  -36.392%     unknown         unknown            0.00  improved
metrics/no_tracing_integration/micro/span_with_1_dynamic_label              229.97 ns  -36.628%     unknown         unknown            0.00  improved
metrics/no_tracing_integration/micro/span_with_2_dynamic_labels             232.76 ns  -37.376%     unknown         unknown            0.00  improved
metrics/off/topology/tcp_socket/01_writer                                   32.630 ms  -2.9888%     29.226 MiB/s    +3.0809%           0.00  none
metrics/off/topology/tcp_socket/02_writers                                  65.839 ms  -3.6122%     28.970 MiB/s    +3.7476%           0.00  none
metrics/off/topology/tcp_socket/04_writers                                  133.97 ms  -3.5501%     28.475 MiB/s    +3.6807%           0.00  none
metrics/off/topology/tcp_socket/08_writers                                  267.86 ms  -4.6311%     28.482 MiB/s    +4.8560%           0.00  none
metrics/off/topology/tcp_socket/16_writers                                  570.73 ms  -1.5402%     26.736 MiB/s    +1.5643%           0.00  none
metrics/off/micro/bare_counter                                              2.6523 ns  -9.9994%     unknown         unknown            0.00  improved
metrics/off/micro/bare_counter_with_static_labels                           2.6523 ns  -9.8846%     unknown         unknown            0.00  improved
metrics/off/micro/bare_counter_with_dynamic_labels                          114.85 ns  -8.1420%     unknown         unknown            0.00  improved
metrics/off/micro/ununsed_span                                              2.6852 ns  -9.9840%     unknown         unknown            0.00  improved
metrics/off/micro/span_enter_without_counter                                200.27 ns  +1.5878%     unknown         unknown            0.00  none
metrics/off/micro/span_no_labels                                            203.15 ns  +1.4784%     unknown         unknown            0.00  none
metrics/off/micro/span_with_1_static_label                                  203.38 ns  +1.0034%     unknown         unknown            0.00  none
metrics/off/micro/span_with_2_static_labels                                 205.02 ns  +1.7166%     unknown         unknown            0.00  none
metrics/off/micro/span_with_1_dynamic_label                                 204.07 ns  +1.0636%     unknown         unknown            0.00  none
metrics/off/micro/span_with_2_dynamic_labels                                205.10 ns  +1.3042%     unknown         unknown            0.00  none
metrics/on/topology/tcp_socket/01_writer                                    43.209 ms  -19.475%     22.071 MiB/s    +24.185%           0.00  improved
metrics/on/topology/tcp_socket/02_writers                                   88.034 ms  -19.535%     21.666 MiB/s    +24.278%           0.00  improved
metrics/on/topology/tcp_socket/04_writers                                   178.64 ms  -19.908%     21.354 MiB/s    +24.857%           0.00  improved
metrics/on/topology/tcp_socket/08_writers                                   361.16 ms  -19.543%     21.125 MiB/s    +24.290%           0.00  improved
metrics/on/topology/tcp_socket/16_writers                                   745.86 ms  -19.407%     20.458 MiB/s    +24.080%           0.00  improved
metrics/on/micro/bare_counter                                               102.72 ns  -58.125%     unknown         unknown            0.00  improved
metrics/on/micro/bare_counter_with_static_labels                            159.81 ns  -57.569%     unknown         unknown            0.00  improved
metrics/on/micro/bare_counter_with_dynamic_labels                           279.90 ns  -46.632%     unknown         unknown            0.00  improved
metrics/on/micro/ununsed_span                                               103.43 ns  -57.783%     unknown         unknown            0.00  improved
metrics/on/micro/span_enter_without_counter                                 214.18 ns  +2.8706%     unknown         unknown            0.00  none
metrics/on/micro/span_no_labels                                             585.11 ns  -19.963%     unknown         unknown            0.00  improved
metrics/on/micro/span_with_1_static_label                                   563.68 ns  -20.530%     unknown         unknown            0.00  improved
metrics/on/micro/span_with_2_static_labels                                  565.47 ns  -20.636%     unknown         unknown            0.00  improved
```

Scanning briefly, I don't think there were any performance _regressions_ in areas related to this, or any numbers big enough to be outside of the acceptable noise window. I might be wrong, though: please double check my work. 😂

**Comment by tobz** [comment]
Regarding `dashmap`, I had forgotten to see if we can actually drop it now.  I'll check that now.

As far as the upstream registry, and expiration, etc... `Registry` itself has never expired keys, only been updated to _support_ tracking idle/active keys, which `metrics-exporter-prometheus` utilizes.  I believe Vector originally switched to avoid paying that cost in atomics to track the generation of metrics, since you don't expire.

All of that said, the reason that Vector switched has been addressed: `Registry` now supports, at the type level, being configured to track or not track the generation of a key.  As seen in the diff, this PR uses the "not tracked" variant.

**Comment by blt** [comment]
> Regarding `dashmap`, I had forgotten to see if we can actually drop it now. I'll check that now.

Makes me think, we might consider adding a workflow that runs https://crates.io/crates/cargo-udeps on the project. 

> As far as the upstream registry, and expiration, etc... `Registry` itself has never expired keys, only been updated to _support_ tracking idle/active keys, which `metrics-exporter-prometheus` utilizes. I believe Vector originally switched to avoid paying that cost in atomics to track the generation of metrics, since you don't expire.
> 
> All of that said, the reason that Vector switched has been addressed: `Registry` now supports, at the type level, being configured to track or not track the generation of a key. As seen in the diff, this PR uses the "not tracked" variant.

Rad, I'd misremembered some. I'm currently in-progress on duplicating the benchmark run on my machine just to be sure, but this looks good and I'll approve assuming the numbers are good for me too.

**Comment by tobz** [comment]
_Yeehaw!_

**Pull request merged**
