### PR TITLE
chore(operations): Add shellcheck to CI and correct scripts

### LINKED ISSUE #1533: Use shellcheck to lint shell scripts
[ShellCheck](https://github.com/koalaman/shellcheck) is a great tool, we could use it to prevent common shell script bugs.

### PR DESCRIPTION
**Pull request by MOZGIII**
Closes #1533.

There are a lot of offenses, this corresponds to the state I see locally in my editor that has `shellcheck` enabled everywhere.

We should reach a consensus on the team-wide adoption of `shellcheck` and fix the errors before merging this.

### CODE REVIEW

**Comment by binarylogic** [comment]
I like this, but someone needs to clean up the issues 😄 . I won't have time to do this any time soon.

**Comment by MOZGIII** [comment]
I can do it :smile:

**Comment by binarylogic** [comment]
Sounds good, feel free to perform other cleanup if you'd like.

**Comment by binarylogic** [comment]
@MOZGIII this looks good. If you can correct the issues we can merge.

**Comment by MOZGIII** [comment]
I reapproached the integration to via `make check-scripts` command, so it's usable for everyone.

**Comment by MOZGIII** [comment]
I added some workarounds to make the CI pass. It's currently at the semi-working state, to fix we need to properly configure jobs to use or not use docker.

**Pull request merged**
