### PR TITLE
fix(dnstap source): Increase timeout for receiving events

### LINKED ISSUE #8240: Dnstap integration test is failing on CI
For example [here](https://github.com/timberio/vector/runs/3047993826). We are seeing:

```
failures:

---- sources::dnstap::integration_tests::test_dnstap_raw_event stdout ----
Jul 12 15:24:59.565  INFO vector::sources::util::framestream: Unix socket receive buffer size modified to 425984.
Jul 12 15:24:59.565  INFO vector::sources::util::framestream: Unix socket buffer send size modified to 425984.
Jul 12 15:24:59.565  INFO vector::sources::util::framestream: Socket permissions updated to 0o777.
Jul 12 15:24:59.566  INFO vector::sources::util::framestream: Listening... path="/home/runner/work/vector/vector/tests/data/dnstap/socket/dnstap.sock1" type="unix"
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `2`', src/sources/dnstap/mod.rs:331:13
```

According to @jszwedko it is possible this test has been more flakey since #7788.

@j-bai do you have any ideas what could be causing this?

### PR DESCRIPTION
**Pull request by yunkunzhu**
Signed-off-by: Yunkun Zhu <yzhu@bluecatnetworks.com>

Closes #8240.
This changeset is to fix dnstap source flaky IT. It includes the following:
* change the timeout value for receiving second event to `1s`
* make sure start BIND after Vector gets started
* avoid sending extra queries
* remove `rndc reconfig`
* set `multithreaded` option to `false`
* add `println!` for error cases

### CODE REVIEW

**Comment by jszwedko** [comment]
Thanks @yhpark ! The code change make sense.

I am seeing some failures running this in a loop locally though:

```
$ while cargo test --no-fail-fast --no-default-features --features dnstap-integration-tests --lib ::dnstap:: ; do : ; done
    Finished test [unoptimized + debuginfo] target(s) in 0.71s
     Running unittests (target/debug/deps/vector-dd8270d4e947ffa6)

running 8 tests
test sources::dnstap::parser::tests::test_get_socket_family_name ... ok
test sources::dnstap::parser::tests::test_get_socket_protocol_name ... ok
test sources::dnstap::parser::tests::test_parse_dnstap_data_with_invalid_data ... ok
test sources::dnstap::parser::tests::test_parse_dnstap_data_with_update_message ... ok
test sources::dnstap::parser::tests::test_parse_dnstap_data_with_query_message ... ok
test sources::dnstap::integration_tests::test_dnstap_update_event ... FAILED
test sources::dnstap::integration_tests::test_dnstap_raw_event ... FAILED
test sources::dnstap::integration_tests::test_dnstap_query_event ... FAILED
---- sources::dnstap::integration_tests::test_dnstap_update_event stdout ----

failures:

Error: deadline has elapsed
thread 'sources::dnstap::integration_tests::test_dnstap_update_event' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `4`', src/sources/dnstap/mod.rs:354:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- sources::dnstap::integration_tests::test_dnstap_raw_event stdout ----
thread 'sources::dnstap::integration_tests::test_dnstap_raw_event' panicked at 'fetch dnstap source event timeout: Elapsed(())', src/sources/dnstap/mod.rs:284:14

---- sources::dnstap::integration_tests::test_dnstap_query_event stdout ----
thread 'sources::dnstap::integration_tests::test_dnstap_query_event' panicked at 'fetch dnstap source event timeout: Elapsed(())', src/sources/dnstap/mod.rs:284:14


failures:
    sources::dnstap::integration_tests::test_dnstap_query_event
    sources::dnstap::integration_tests::test_dnstap_raw_event
    sources::dnstap::integration_tests::test_dnstap_update_event
```

Would you expect those? Maybe I'm running them too close together? I'll try with a sleep.

**Comment by jszwedko** [comment]
Actually, I see, now those are failing every time. I'm guessing it needs a clean starting state.

**Comment by jszwedko** [comment]
Yeah, running repeatedly with the setup/teardown looks good. It'd be nice if the tests didn't depend on it starting with a clean docker container, but we can leave that aside for now.

**Review by jszwedko — APPROVED** [review]
Thanks @yunkunzhu !

**Comment by yunkunzhu** [comment]
> Yeah, running repeatedly with the setup/teardown looks good. It'd be nice if the tests didn't depend on it starting with a clean docker container, but we can leave that aside for now.

Yes it's a good point. We can definitely improve it. Thank you Jesse.

**Pull request merged**
