### PR TITLE
chore(metrics): Upgrade metrics crate and crates that transitively depend on it

### LINKED ISSUE #6412: Update metrics crate and investigate performance degradation
Our benchmarks show that upgrading the `metrics` crate to `v0.13.1` causes a significant performance regression (>20%). We need to investigate and resolve the performance problem before we can upgrade.

PR with an attempted update: https://github.com/timberio/vector/pull/6217#issuecomment-766435360

### PR DESCRIPTION
**Pull request by pablosichert**
Closes #6412.

Need to watching closesly if this introduces a performance regression.

### CODE REVIEW

**Comment by juchiast** [comment]
There are some regressions:
```
2021-02-14T05:08:37.5070766Z metrics_snapshot/cardinality/1                                                                       519.45 ns  +8.3179%     unknown         unknown            0.00  regressed
2021-02-14T05:08:37.5071474Z metrics_snapshot/cardinality/10                                                                      3.4979 us  +13.927%     unknown         unknown            0.00  regressed
2021-02-14T05:08:37.5072182Z metrics_snapshot/cardinality/100                                                                     40.773 us  +20.232%     unknown         unknown            0.00  regressed
2021-02-14T05:08:37.5072873Z metrics_snapshot/cardinality/1000                                                                    457.13 us  +13.004%     unknown         unknown            0.00  regressed
2021-02-14T05:08:37.5073642Z metrics_snapshot/cardinality/10000                                                                   5.1152 ms  +10.216%     unknown         unknown            0.00  regressed
2021-02-14T05:08:37.5111392Z metrics_off/micro/bare_counter                                                                       4.5637 ns  +15.296%     unknown         unknown            0.00  regressed
2021-02-14T05:08:37.5112101Z metrics_off/micro/bare_counter_with_static_labels                                                    4.4224 ns  +36.372%     unknown         unknown            0.00  regressed
2021-02-14T05:08:37.5113733Z metrics_off/micro/ununsed_span                                                                       4.7463 ns  +44.293%     unknown         unknown            0.00  regressed
```

**Comment by binarylogic** [comment]
@jszwedko any reason this did not fail the CI check?

**Comment by binarylogic** [comment]
@pablosichert could you open an issue on the metrics repo regarding the performance regression? Assuming it is on their end.

**Comment by jszwedko** [comment]
@binarylogic failing the check is still disabled to make sure there aren't too many false positives. We have enough data (CI runs) to analyze now, I just have to do it :smile:

**Comment by pablosichert** [comment]
@binarylogic opened https://github.com/metrics-rs/metrics/issues/179 for further investigation.

**Comment by jszwedko** [comment]
Closing since https://github.com/timberio/vector/pull/7031 did this upgrade.

**Pull request closed without merging**
