### PR TITLE
feat(elasticsearch sink): handle events

### PR DESCRIPTION
**Pull request by jdrouet**
Can be tested with the following docker-compose file
```yml
version: '3'

services:
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
        container_name: elastic
        environment:
            - "discovery.type=single-node"
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - backend

    kibana:
        image: docker.elastic.co/kibana/kibana:7.13.1
        container_name: kibana
        environment:
            - ELASTICSEARCH_HOSTS=http://elastic:9200
        ports:
            - 5601:5601
        networks:
            - backend

networks:
    backend: {}
```

and the following vector configuration

```toml
[sources.metrics]
type = "host_metrics"
collectors = ["cpu", "memory", "network"]

[sinks.elastic]
type = "elasticsearch"
inputs = ["metrics"]
endpoint = "http://localhost:9200"
index = "host-metrics"
```

Signed-off-by: Jérémie Drouet <jeremie.drouet@datadoghq.com>

### CODE REVIEW

**Comment by binarylogic** [comment]
Nice! A few questions on this:

1. How does our metrics JSON schema align with Elastic's metrics schema (ECS)? This might be something to follow up with.
2. This is exactly the same as `host_metrics` -> `metric_to_log` -> `elasticsearch`, right?

**Review by vladimir-dd — APPROVED** [review]
LGTM 👍

**Comment by spencergilbert** [comment]
> Nice! A couple of questions on this:
> 
> 1. How does our metrics JSON schema align with Elastic's metrics schema (ECS)? This might be something to follow up with.
> 2. This is exactly the same as `host_metrics` -> `metric_to_log` -> `elasticsearch`, right?

Was this answered?

**Comment by jdrouet** [comment]
> Was this answered?

No. Or maybe during the standup.

> How does our metrics JSON schema align with Elastic's metrics schema (ECS)? This might be something to follow up with.

From what I saw, the requirements are those given by Kibana which allows to do whatever we want, more or less. We "just" need the timestamp field to be in `@timestamp`.

> This is exactly the same as host_metrics -> metric_to_log -> elasticsearch, right?

It is now 😄

**Pull request closed without merging**
