### PR TITLE
fix(vrl): Return VRL functions to alphabetical order

### PR DESCRIPTION
**Pull request by lucperkins**
This is a tiny nit, but when you list VRL functions in the REPL using `help functions` the names are slightly out of order. There are also a few duplicates (the `match*` functions).

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]

**Comment by lucperkins** [comment]
@spencergilbert These failures _seem_ spurious to me but I'm not in a good position to know. Could you take a quick look?

**Comment by spencergilbert** [comment]
> @spencergilbert These failures _seem_ spurious to me but I'm not in a good position to know. Could you take a quick look?

I've not seen that fail flakily before... but I don't see how this change could influence it. My instinct is to merge it, but @jszwedko should confirm tomorrow.

**Review by jszwedko — APPROVED** [review]
Thanks! I'm assuming CI was rerun as I'm not seeing any failures currently.

**Comment by spencergilbert** [comment]
> Thanks! I'm assuming CI was rerun as I'm not seeing any failures currently.

Yep, over here @jszwedko https://github.com/timberio/vector/runs/3539522073

**Comment by lucperkins** [comment]
@spencergilbert @jszwedko Seems all clear now. Will merge and then monitor.

**Pull request merged**
