### PR TITLE
fix(http source)!: don't dedot keys 

### LINKED ISSUE #3697: Parsing JSON in dotted notation can silently overwrite existing key values
### Vector Version

```
vector 0.10.0 (g0f0311a x86_64-apple-darwin 2020-07-22)
```

### Vector Configuration File

```toml
[sources.app_log]
  type = "http"
  address = "0.0.0.0:9091"
  encoding = "json"

[sinks.to_file]
  type = "file"
  inputs = ["app_log"]
  path = "/tmp/vector.log"
  encoding.codec = "ndjson"
```

### Debug Output

https://gist.github.com/awangc/c09cd11f75a3ed17bcf201e2bad580e0

### Expected Behavior

A warning/log line that `test` and `test2.child` fields have been overwritten (see the gist above)

### Actual Behavior

The fields `test` and `test2.child` were silently overwritten

### Example Data

See the `curl` command from the gist above

### PR DESCRIPTION
**Pull request by drunkirishcoder**
This fixes #3697. However it would be breaking if anyone is relying on this unpredictable of dedotting of keys. The dedot behavior is better implemented as a separate transform, and looks like there's already #3588 open for that.

### CODE REVIEW

**Review by Hoverbear — APPROVED** [review]
This looks good, @drunkirishcoder . I tagged this as a breaking change (`!` in the title) so when we release we'll make a highlight around this.

**Comment by Hoverbear** [comment]
Looks like one of the tests is failing? I restarted it just in case, but you might be able to get it fixed by just merging master.

**Comment by drunkirishcoder** [comment]
rebased against master. not sure why there are still checks failing.

**Comment by binarylogic** [comment]
@Hoverbear @jamtur01 any idea why CI didn't run here? I assume it was while we were trying our Bors? Can we trigger a re-run?

**Pull request merged**
