### PR TITLE
chore(operations): Build multi-arch Docker images

### PR DESCRIPTION
**Pull request by a-rodin**
Closes https://github.com/timberio/vector/issues/1196.

This uses the new `docker buildx` command to build images for all architectures at once. However, I haven't found a way to run images built with `docker buildx` locally to verify them yet. It looks like it is caused by multi-arch builders using `docker-container` engine, while `docker run` supports only `docker` engine.

### CODE REVIEW

**Comment by binarylogic** [comment]
Nice! How will the docs change as a result, if at all?

**Comment by a-rodin** [comment]
@binarylogic I've expanded Docker documentation a bit, in particular added pinned versions to example commands.

I'm thinking would it makes sense to add Docker as second installation method for all operating systems (maybe except Windows) or not.

**Comment by a-rodin** [comment]
I've merged it to see how would it work on nightly build.

**Comment by binarylogic** [comment]
> I'm thinking would it makes sense to add Docker as second installation method for all operating systems (maybe except Windows) or not.

That makes sense, I'll add it. And why not Windows? Isn't Docker supported on there?

**Comment by binarylogic** [comment]
Docs look great 👍

**Comment by a-rodin** [comment]
> That makes sense, I'll add it. And why not Windows? Isn't Docker supported on there?

Hmm, yeah, as it is supported there I think we can add Docker as an installation method for Windows too. But I haven't tried docker for Windows, so I'm not sure would it be possible to use commands like

```bash
docker run -v $PWD/vector.toml:/etc/vector/vector.toml:ro timberio/vector:0.5.0-alpine
```

from the current documentation in unmodified form or would we need to change them.

**Comment by binarylogic** [comment]
True. I wouldn't worry about it right now unless it's simple. Otherwise we can wait for demand.

**Pull request merged**
