### PR TITLE
chore(dev): remove 'built' dep and stop needlessly rebuilding on unrelated changes

### PR DESCRIPTION
**Pull request by tobz**
As discovered in #7582, we often needlessly rebuild benchmark binaries in CI runs due to unrelated changes in code.  This could also happen locally if any code within the "package" changed -- which, for most things, is anything in the repository at all -- as we have a build script, and build script default behavior involves rerunning itself when any file in the package changes.  As the build script would run, values in the output would often change, leading then to a legitimate change that necessitated a rebuild.  Ergo, if we can pare down what the build script spits out, and inform Cargo when it should rerun the build script, we can often avoid these binary rebuilds.

With that said, this PR introduces changes that remove `built` and add in our own, pared-down code for collecting and emitting build-time constants.  While most of the information can be pulled natively from Cargo-provided environment variables, there is information we've given up, namely Git information and build time.

As a concession, we've introduced a new environment variable -- `VECTOR_BUILD_DESC` -- which can be overridden at any time, and allows any custom information to be provided, which ultimately is included as a sort of build ID in version strings.  This could be set when building debug-friendly binaries if needed for support purposes, or overridden during versioned release builds to include compiler information, build time, and more.

### CODE REVIEW

**Review by bruceg — APPROVED** [review]

**Comment by jszwedko** [comment]
Nice! I'll give this a closer look tomorrow, but we should make sure the nightly builds still have the git sha in them as that's the only way to differentiate them at the moment. It's nice to have the build date in them too for quick reference.

**Comment by tobz** [comment]
I can tell you off the bat I didn't add that back, but I can fix that quickly. :)

**Review by jszwedko — COMMENTED** [review]
Awesome, thanks! This looks good to me. My only additional suggestion would be to maybe ensure the expected build info is set in the verify steps of the nightly/release workflows: 

https://github.com/timberio/vector/blob/7c16aa0057e41aa2ddba64489109e5c396d77549/.github/workflows/nightly.yml#L250-L255

Not a big deal though since we weren't currently verifying that anyway with `built`.

**Comment by tobz** [comment]
That's a good idea. 👍🏻

**Comment by jszwedko** [comment]
@tobz sounds good. For reference, you can actually trigger the nightly flow manually; which it seems like you already discovered 😄

**Pull request merged**
