### PR TITLE
feat(aws service): Add support for `use_eks_web_identity` to all AWS sinks

### LINKED ISSUE #2881: Support IAM Roles for Service Accounts
If you're looking to extend what sort of AWS auth you support, it might be useful to allow "IAM Roles for Service Accounts" which is an AWS EKS (Elastic Kubernetes Service) way of giving K8s daemonsets roles.   You have the necessary version of rusoto (0.44.0) but you might need to call different credential source, see https://github.com/rusoto/rusoto/issues/1497 & https://github.com/rusoto/rusoto/pull/1577.

Not necessary for my own use case (I'm running Vector as a Systemd unit on EKS hosts), but I believe K8s is a focus for the 0.10.0 release, using a daemonset by default...

_Originally posted by @tyrken in https://github.com/timberio/vector/pull/2859#issuecomment-646510586_

### PR DESCRIPTION
**Pull request by VJftw**
Hopefully closes #2881 

Hi! I've taken a little stab at fixing #2881 as it would be really useful for us. 

This is my first time writing any Rust, so I've tried to base off of #1772 which seems to be a similar feature and looking at rusoto/rusoto#1497, rusoto/rusoto#1577 as recommended in #2881.

### CODE REVIEW

**Comment by tustvold** [comment]
This may also be relevant context - https://github.com/rusoto/rusoto/issues/1781

**Review by MOZGIII — COMMENTED** [review]
The code looks good! I'd like to test this on an actual EKS cluster before we proceed though.

One thing to think about is how do we test this in CI. The chance this causes issues is not high, so the initial manual test should be enough, however we should cover this in perspective.

I'll get back to it later in sprint.

In the meantime, would you mind resolving the merge conflicts?

**Comment by VJftw** [comment]
Thanks! I agree this should be tested on an EKS cluster before! I'll try to spare some time to test it out and let you know :)

> This may also be relevant context - [rusoto/rusoto#1781](https://github.com/rusoto/rusoto/issues/1781)

The last comment in this looks useful, do you prefer the way they've done it there? From an end-user perspective, I reckon it's better as EKS would just work without any extra configuration. I'm happy to change/update this PR if you agree :)

**Comment by MOZGIII** [comment]
Well, including this as part of the default chain seems to be reasonable, given the referenced Java code. It is a very good point that it would be less configuration, and vector would "just work". We strive for offering good defaults, so I definitely welcome the change to just include in the default chain. I was a bit worried about the security concerns of this, but if it's fine for the official Java code it should be fine for us too.

Did you consider making a PR to the `rusoto` crate? Implementing this on our end is definitely possible, but I'd consider doing this as part of the upstream to be a much better way.

**Comment by tustvold** [comment]
@MOZGIII So I did have a look at implementing it in rusoto, however, it is complicated by the fact the WebIdentityProvider is part of the rusoto_sts crate which depends on rusuto_core which depends on rusoto_credential which is where the default credential chain is defined. I'm not sure that it is possible to address this without making breaking changes to rusoto, but someone smarter than I may know how. I have now commented on that PR, but it would be good imo to get EKS support into vector, even if future changes to rusoto allow it to be removed at some point.

If it is helpful I'm currently running an updated a lightly modified version of this in EKS which can be found [here](https://github.com/tustvold/vector/tree/aws-eks-web-identity-support) and it seems to be working correctly so far. 

I do get the below on startup, but it seems to be harmless...

```
ERROR vector::topology::builder: Healthcheck: Failed Reason: Invalid credentials
```

**Comment by VJftw** [comment]
Thanks both! @MOZGIII I agree it does make sense for doing upstream, but given what @tustvold has said, I agree that it would be great to support EKS in vector with a workaround like this and remove it once the upstream rusoto crate supports it. 

@tustvold I'm more than happy to close this PR if you'd like to open one from your fork (and save me having to test manually myself too) :)

**Comment by tustvold** [comment]
Will deploy and test today, and if all goes well raise a PR

**Comment by MOZGIII** [comment]
So, should this be closed now in favor of #4049?

**Comment by VJftw** [comment]
Yup, thanks @tustvold!

**Pull request closed without merging**
