### PR TITLE
chore(operations): Allow running all tests locally

### PR DESCRIPTION
**Pull request by a-rodin**
Closes https://github.com/timberio/vector/issues/1663.

No tests which depend on external services are implemented yet.

### CODE REVIEW

**Comment by binarylogic** [comment]
This looks great! What's left to merge this? Implementation of external service tests?

**Comment by a-rodin** [comment]
@binarylogic It is ready for merging now. The implementation if external services tests is there (`test-docker` target), as like as packaging for ARM targets.

I also considered https://github.com/timberio/vector/issues/1700, but as you see from the discussions there are some complications with it.

**Comment by binarylogic** [comment]
Sounds good. We can address #1700 in a follow-up PR.  It's likely we'll need to move off of CircleCI before doing that anyway.

Let's :shipit: .

**Comment by binarylogic** [comment]
Actually, it looks like `make generate` has been dropped?

**Comment by binarylogic** [comment]
Looks good to me. Feel free to merge when ready.

**Comment by a-rodin** [comment]
> Actually, it looks like `make generate` has been dropped?

Yeah, it was. I restored it.

> Looks good to me. Feel free to merge when ready.

I'm going to merge this after the tests pass. I also did https://github.com/timberio/vector/issues/1727 as part of this PR because it is tightly coupled to this, so making it a separate PR would only produce merge conflicts

**Comment by binarylogic** [comment]
Sounds good.

**Pull request merged**
