### PR TITLE
chore(deps): Update prost to 0.8.0

### PR DESCRIPTION
**Pull request by jszwedko**
Fixes: #8208
Fixes: #8184

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Comment by jszwedko** [comment]
Kicked off integration tests to verify: https://github.com/timberio/vector/actions/runs/1028414208

**Review by bruceg — APPROVED** [review]
Not happy about dragging in another version of `nom`, but we need to do this.

**Comment by KannarFr** [comment]
@jszwedko can we expect a release with this PR soon?

**Review by spencergilbert — APPROVED** [review]

**Comment by jszwedko** [comment]
> @jszwedko can we expect a release with this PR soon?

It appears to have started causing one of our integration tests to hang. I still have to dig into it, but hopefully it'll be merged soon and appear in the next release, 0.16.0, on August 24th.

**Comment by jszwedko** [comment]
Merged master and kicked off integration tests again: https://github.com/timberio/vector/actions/runs/1079463904

I think the integration tests were actually fixed on master.

**Review by spencergilbert — APPROVED** [review]
PROST! 🍻

**Comment by jszwedko** [comment]
@JeanMertz would you be able to take a look at this next week when you are back. As far as I can tell, the test is failing because the test server isn't responding with a valid gRPC message. I'm unsure why this wasn't failing prior to the prost upgrade though. It must have handled empty responses differently previously.

**Comment by jszwedko** [comment]
Covered by #8401

**Pull request closed without merging**
