### PR TITLE
feat: Add rate limit notice when it starts

### LINKED ISSUE #687: Output rate limited notice when rate limiting begins
Following up on https://github.com/timberio/vector/issues/628#issuecomment-515648373, we should output a log message at the start of rate limiting. In other words, if we only allow 2 messages every 30 seconds, then we would output a rate limited log message immediately after message 3.

> Regex failed for `Hello world`
> Regex failed for `Hello world`
> ... 3rd message is received but not logged ....
> Limiting the output of "Regex failed for `Hello world`" for the next 30 seconds
> ... 30 seconds passes ...
> Rate limited 1 message for "Regex failed for `Hello world`" (or whatever the current message is)

Additionally, I'm open to dropping the summary log message entirely since both messages seem noisy. Or, we could only log the initial message if the window is >= X.

### PR DESCRIPTION
**Pull request by LucioFranco**
Closes #687 

Signed-off-by: Lucio Franco <luciofranco14@gmail.com>

### CODE REVIEW

**Comment by LucioFranco** [comment]
Here is a screenshot of the example running with logs being outputed every 5 seconds and rate limited at 1 log per 5 seconds.

image

**Comment by binarylogic** [comment]
Interesting, I didn't realize we were exposing the `count` and `rate_limit` attributes. A few things here:

1. The `rate_limit` attribute is super ambiguous. I have no idea what that means. Is that the window or the total count?
2. I wasn't aware we were exposing attributes about the window, so I'm wondering if we can just communicate all of this in the attributes and avoid this message entirely.

For example:

```
INFO: base: hello, world! count=25 rate_window=5 rate_left=0
```

I'm open to better naming, but `rate_left` would represent how many items are left before rate limiting begins. `0` means that this is the last log line, avoiding the needs to log a "limiting ... for the next 5 seconds".

**Comment by LucioFranco** [comment]
@binarylogic I've actually come around to really liking the limiting the output message. During my testing, it makes it clear what is going on.

As for the `rate_limit` attribute I will change this to `rate_limit_secs` since it better describes what its doing. The `count` attribute is actually just one I added so you could see which messages are being limited or not. Normal logs would not contain a count.

**Comment by binarylogic** [comment]
If you find it to be useful then that's more important. Just to clarify, `rate_limit_secs` implies a window of X seconds will only allow 1 message?

**Comment by LucioFranco** [comment]
@binarylogic correct, it works the first message in the window is let through, the second message instead of being printed will show the `message` attribute and the window duration. Then the next log will be after the window is over.

**Comment by binarylogic** [comment]
Cool, let's merge then. I'll open a new issue for the attribute rename.

**Pull request merged**
