### PR TITLE
chore(observability): Filter events

### LINKED ISSUE #3394: Define events for the `filter` transform
As part of finishing https://github.com/timberio/vector-product/issues/14, we need to define internal events for the `filter` transform.

## Defining events

* If you have not already, please read [RFC 2064](https://github.com/timberio/vector/blob/master/rfcs/2020-03-17-2064-event-driven-observability.md).
  * ***Be sure to read the [Guide-level Proposal section](https://github.com/timberio/vector/blob/master/rfcs/2020-03-17-2064-event-driven-observability.md#guide-level-proposal) and the implementation details that affect performance.***
* You can also look at the [currently defined events](https://github.com/timberio/vector/tree/master/src/internal_events) for precedence.
* Events should be named properly: `<ComponentName><Noun><Verb>`. For example, the `syslog` source defines the [`SyslogEventReceived` struct](https://github.com/timberio/vector/blob/fb71f5ad76266d9a44164e6804723376353e4ff0/src/internal_events/syslog.rs#L9).

## Requirements

- [x] Add a `FilterEventProcessed` event.
  - [x] Derive an `events_processed` metric via the `emit_metrics` method. ([example](https://github.com/timberio/vector/blob/a391434e97a078f6ea92691bba76f9af91ad1866/src/internal_events/add_fields.rs#L8))
- [x] Add a `FilterEventDiscarded` event. This event only occurs if the event does not match the filter.
  - [x] Derive an `events_discarded` metric via the `emit_metrics` method. ([example](https://github.com/timberio/vector/blob/b8403c5eea29ff51df572f7a8c2085d682768744/src/internal_events/sampler.rs#L21))
- [x] Audit and add events for all possible errors. ([example](https://github.com/timberio/vector/blob/a391434e97a078f6ea92691bba76f9af91ad1866/src/internal_events/lua.rs#L36))
  - [x] Derive a `processing_errors` metrics via the `emit_metrics` method. ([example](https://github.com/timberio/vector/blob/a391434e97a078f6ea92691bba76f9af91ad1866/src/internal_events/lua.rs#L43))
  - [x] Emit a log message that ends with `; discarding event` _only_ if the error results in dropping the event. ([example](https://github.com/timberio/vector/blob/a391434e97a078f6ea92691bba76f9af91ad1866/src/internal_events/lua.rs#L39).
- [x] Audit and add events for all component-specific behavior. ([example](https://github.com/timberio/vector/blob/a391434e97a078f6ea92691bba76f9af91ad1866/src/internal_events/lua.rs#L24))
- [x] Ensure that logs in the hot path are rate limited via the `rate_limit_secs` parameter. ([example](https://github.com/timberio/vector/blob/fb71f5ad76266d9a44164e6804723376353e4ff0/src/internal_events/tcp.rs#L83)).
- [x] Ensure that all log messages start with a capital letter and end with a `.`. ([example](https://github.com/timberio/vector/blob/master/src/internal_events/tcp.rs#L83))

### PR DESCRIPTION
**Pull request by leebenson**
Adds filter events. Closes #3394.

The spec in #3394 requires error handling for discarded events, where appropriate.

I couldn't see any code paths (outside of config) that would fail. The only implementation that seemed relevant is:

```rust
impl FunctionTransform for Filter {
    fn transform(&mut self, output: &mut Vec<Event>, event: Event) {
        if self.condition.check(&event) {
            output.push(event);
        }
    }
}
```

I added `FilterEventProcessed` and `FilterEventDiscarded` events accordingly per `self.condition.check`'s bool result, but couldn't see anywhere an error might occur.

Please advise if I'm missing something obvious.

### CODE REVIEW

**Comment by binarylogic** [comment]
@lucperkins does this require any changes to the telemetry data in the docs?

**Comment by lucperkins** [comment]
@binarylogic @leebenson Yeah, it looks like `events_discarded` will need to be added to the `filter` transform docs:

```
components: transforms: filter: {
    // other stuff

    telemetry: metrics: {
        components.sources.internal_metrics.output.events_discarded
    }
}
```

**Comment by leebenson** [comment]
I updated filter events to use the `_total` suffix. I also added the telemetry block for `events_discarded_total`.

Should `processed_events_total` be added too? I see a reference in `internal_metrics.cue` but, for example, the swimlanes cue doesn't contain it.

**Review by jszwedko — APPROVED** [review]
Looks good to me!

**Comment by leebenson** [comment]
@binarylogic @lucperkins - any thoughts on https://github.com/timberio/vector/pull/5428#issuecomment-740529039 ?

Is this good to merge?

**Review by bruceg — APPROVED** [review]

**Pull request merged**
