### PR TITLE
enhancement(syslog source): Add drop_invalid option

### LINKED ISSUE #746: Add `drop_invalid` option to `syslog` source
Follow up to https://github.com/timberio/vector/issues/741#issuecomment-520463684

The `syslog` source should have a `drop_invalid` option (default `true`). This allows users to opt-out of this behavior, allowing invalid messages to proceed through the pipeline.

### PR DESCRIPTION
**Pull request by FungusHumungus**
Fixes #746 

I've added a new option to the syslog source - drop_invalid, default true.

When this option is false, if the message fails to parse, it doesn't drop the event - instead it creates an event with the message field populated, timestamp set to the current time.

### CODE REVIEW

**Comment by binarylogic** [comment]
Thanks! This looks good to me from a docs standpoint. I'm curious, was there a specific log line you encountered that failed our parsing?

**Comment by FungusHumungus** [comment]
Honestly, I'm mainly fixing this as it was tagged as a 'good first issue'.
The problem can be replicated with nginx:

**Comment by binarylogic** [comment]
Got it. Thanks!

**Comment by FungusHumungus** [comment]
Darn it, sorry, I've messed things up a little rebasing from master..

**Comment by binarylogic** [comment]
Weird, you could undo the last merge commit and then retry. I'd recommend a _rebasing_ with master if you can, but merging should also work fine.

**Comment by FungusHumungus** [comment]
I think the problem was rebasing with master seems to have pulled in everyone elses commits which has caused the problem. I clearly didnt rebase before creating the pull request which is my mistake.

I think I might kill this pull request and start again...

**Pull request closed without merging**
