### PR TITLE
fix(observability): Switch from topology to components terminology

### PR DESCRIPTION
**Pull request by lucperkins**
This PR updates the terminology (and *only* the terminology) in the GraphQL API, favoring "components" over "topology," which has a more specific meaning.

### CODE REVIEW

**Comment by binarylogic** [comment]
Just to be on the same page with terminology:

* Topology is the entire DAG.
* Pipeline is a single source -> sink path on the DAG.
* Components are all of the nodes.

So querying the "topology" isn't technically wrong. But the queries would return components and so on.

**Comment by lucperkins** [comment]
@binarylogic The core issue here is that `Source`, `Sink`, and `Transform` are currently implementing a `Topology` interface in GraphQL. With the changes I'm proposing here, you would run `query { components { ... } }` to see your entire Vector "graph," i.e. your entire topology. I'd actually be fine with going back to the `topology` query as long as that query returns `Component`s. Right now it returns `Topology`s which strikes me as confusing. Happy to chat further 1:1 if this is unclear.

**Comment by binarylogic** [comment]
👍 I agree with your suggestions/reasoning.

**Comment by lucperkins** [comment]
@binarylogic Sounds good. The naming on the queries is something that's very easy to change later once the underlying naming is where we want it (the goal of this PR).

**Comment by leebenson** [comment]
FYI, merged this into #4702 since most of the work in `src/top` touches it. Updated `vector top` to use components.

If further changes are required, I'll grab the latest. Otherwise, LGTM.

**Pull request merged**
