### PR TITLE
chore(testing): Add ability to verify RPM artifacts locally 

### PR DESCRIPTION
**Pull request by a-rodin**
I wanted to have an ability to have checks that CircleCI does, but which can all be executed locally. This experiment went a bit too far, but I decided that it would be nice to share what I got, as some of the ideas from here might be reused in #1637 and #1613. 

The basic idea is the following:
* Describe execution of each build step as a service in `docker-compose.test.yml`.
* Describe dependencies between these build steps in `Makefile.test`.

Then, for example, full verification of RPM packages can be executed just by running

```sh
make -f Makefile.test verify-rpm -j4
```

which would automatically build Vector, build RPM packages, and then verify them. Note the `-j4` flag, which tells `make` to execute at most 4 jobs in parallel if possible.

Then logs of each of these jobs can be inspected by running

```sh
docker-compose -f docker-compose.test.yml logs <job name>
```

Example:

```
$ docker-compose -f docker-compose.test.yml logs package-rpm
Attaching to vector-rpm_package-rpm_1
package-rpm_1                    | 'distribution/init.d/./vector' -> '/root/rpmbuild/SOURCES/init.d/./vector'
...
package-rpm_1                    | vector-0.8.0-1.x86_64.rpm
package-rpm_1                    | '/root/rpmbuild/RPMS/x86_64/vector-0.8.0-1.x86_64.rpm' -> 'target/artifacts/vector-x86_64.rpm'
package-rpm_1                    | removed '/root/rpmbuild/RPMS/x86_64/vector-0.8.0-1.x86_64.rpm'
```

There is also a possibility to visualize the dependency graph between Makefile targets:

```sh
$ make -f Makefile.test target-graph TARGET=verify-rpm
                                 ┌──────────────────────────┐
                                 │      build-archive       │
                                 └──────────────────────────┘
                                   │
                                   │
                                   ▼
┌──────────────────────────┐     ┌──────────────────────────┐     ┌─────────────────────┐
│ verify-rpm-amazonlinux-2 │ ◀── │       package-rpm        │ ──▶ │ verify-rpm-centos-7 │
└──────────────────────────┘     └──────────────────────────┘     └─────────────────────┘
  │                                │                                │
  │                                │                                │
  │                                ▼                                │
  │                              ┌──────────────────────────┐       │
  │                              │ verify-rpm-amazonlinux-1 │       │
  │                              └──────────────────────────┘       │
  │                                │                                │
  │                                │                                │
  │                                ▼                                │
  │                              ┌──────────────────────────┐       │
  └────────────────────────────▶ │        verify-rpm        │ ◀─────┘
                                 └──────────────────────────┘
```

I'm thinking does it make sense to slowly move configuration of checks in CI to something like this, alongside other checks that we are going to add, but probably don't want to run in CI each time (one example coming to mind is #825)? It would allow us to unlock from any particular CI provider and enable contributors to easily run all checks locally before submitting a PR.

Caveats: currently everything is running under the root user.

This PR is submitted more for discussion, but is not necessarily meant to be merged.

### CODE REVIEW

**Comment by binarylogic** [comment]
I like this! 👍 from me.

@LucioFranco any opinions?

**Comment by LucioFranco** [comment]
I like this :+1:, is there a way to get rid of the sudo caveat? But beyond that this seems good to me.

**Comment by binarylogic** [comment]
@a-rodin let's proceed with this. What's left to get this merged?

**Comment by a-rodin** [comment]
@LucioFranco Now it is possible to add `user: $USER` to `docker-compose.test.yml` in order to start the corresponding as the current user. However, currently it was possible to enable only for `build-archive` target, because such `package-rpm` and `package-deb` do require root access. It is possible to work around this and make them work without root access, but it would be necessary to change the corresponding Dockerfiles and `package-*.sh` scripts, so it is probably better to do this as separate issues.

@binarylogic It is ready to be merged now.

**Comment by lukesteensen** [comment]
This is a great idea. The less coupled to CircleCI and the easier it is to run checks locally, the better.

**Comment by binarylogic** [comment]
Cool! My only gripe would be the `Makefile.test` and `Dockercompose.test.yml`. I'd prefer that we move both to the `scripts` directory if you're ok with that?

**Comment by a-rodin** [comment]
It is not possible to make `docker-compose.test.yml` to a subdirectory because `docker-compose` doesn't allow compose files to access parent directory for security reasons. However, we can unify it. I've opened issue https://github.com/timberio/vector/issues/1663 about this.

**Pull request merged**
