### PR TITLE
chore(ci): Only check for diffs in the docs for `make check-docs`

### PR DESCRIPTION
**Pull request by jszwedko**
The check previously picking up changes to `Cargo.toml` and `.cargo/config` that happen as part of `make slim-builds` in CI.

Example: https://github.com/timberio/vector/pull/4101/checks?check_run_id=1226461323#step:9:15

### CODE REVIEW

**Review by jamtur01 — APPROVED** [review]
LGTM

**Comment by MOZGIII** [comment]
We can apply a more accurate check, so it's not disrupted by any other changes. I'll try to hack together a PR over the weekend.

**Comment by jszwedko** [comment]
@MOZGIII that would be great :smile: . It'd be ideal if `cue` just had a way to exit non-zero if files needed to be formatted.

**Comment by MOZGIII** [comment]
We could help with pushing https://github.com/cuelang/cue/pull/247

**Comment by jszwedko** [comment]
I'd be a fan of both: solving the immediate need better, but also pushing forward https://github.com/cuelang/cue/pull/247. It looks like the latter is just waiting on review comments to be resolved. I could try to poke at it next week.

**Pull request merged**
