### PR TITLE
fix(vrl): Handle quotes in path segments

### LINKED ISSUE #8590: No way to access keys with quotes in them in VRL
There doesn't _appear_ to be a way to access keys that literally have `"`s in them in VRL.

```
vector 0.15.0 (x86_64-apple-darwin 994d812 2021-07-16)
```

```
$ . = { "event": {"\"log\"": 1 }}
$ .event
{ ""log"": 1 }
$ .event."\"log\""
null
```

### PR DESCRIPTION
**Pull request by spencergilbert**
Signed-off-by: Spencer Gilbert <spencer.gilbert@datadoghq.com>

Closes #8590

@StephenWakely's first guess at a fix seems to work locally - though `make test-vrl` fails for me (timezones!)

### CODE REVIEW

**Comment by jszwedko** [comment]
Nice, that seems sensible. We should probably add a test though. And I’m curious if `Display` needs to be updated too

**Comment by spencergilbert** [comment]
> Nice, that seems sensible. We should probably add a test though. And I’m curious if `Display` needs to be updated too

Indeed - mostly sanity checking since I was going cross-eyed trying to see if the vrl tests failed due to timezones :/

**Comment by jszwedko** [comment]
> > Nice, that seems sensible. We should probably add a test though. And I’m curious if `Display` needs to be updated too
> 
> Indeed - mostly sanity checking since I was going cross-eyed trying to see if the vrl tests failed due to timezones :/

Yeah, it'd be nice to fix that so they pass with non-UTC local timezone. You can do `TZ=UTC ...` locally to work around it.

**Comment by spencergilbert** [comment]
NOTE: This PR _doesnt_ fix the issue right now

**Comment by jszwedko** [comment]
@spencergilbert should we close this? Just looking over our PRs.

**Comment by spencergilbert** [comment]
Yeah, probably fine - this PR doesn't resolve the issue and I'm not likely to come back to it soon.

**Pull request closed without merging**
