### PR TITLE
chore: Adjust remap transform to be task, not function

### PR DESCRIPTION
**Pull request by blt**
This commit adjusts the remap transform to be a task and not a function. Our
goal is to introduce many parallel remap processors in order to cut down on
overhead that slows down the pipeline when we go through remap.

Interesting results here. When I make the stream filter_map a simple identity --
just pass things through -- here's the overhead inherent in a single run:

```
> perf stat --repeat=1 bash -c "zcat ~/baked.log.gz | ./target/release/vector -qq --config ~/vector-nohop.toml"

 Performance counter stats for 'bash -c zcat ~/baked.log.gz | ./target/release/vector -qq --config ~/vector-nohop.toml':

         34,827.42 msec task-clock                #    3.674 CPUs utilized
           710,140      context-switches          #    0.020 M/sec
               821      cpu-migrations            #    0.024 K/sec
             8,613      page-faults               #    0.247 K/sec
    99,155,486,492      cycles                    #    2.847 GHz                      (83.34%)
     4,446,623,871      stalled-cycles-frontend   #    4.48% frontend cycles idle     (83.25%)
    47,034,495,443      stalled-cycles-backend    #   47.44% backend cycles idle      (83.38%)
   121,304,034,853      instructions              #    1.22  insn per cycle
                                                  #    0.39  stalled cycles per insn  (83.29%)
    23,038,285,171      branches                  #  661.499 M/sec                    (83.43%)
        68,915,321      branch-misses             #    0.30% of all branches          (83.30%)

       9.478569055 seconds time elapsed

      27.269502000 seconds user
       7.385255000 seconds sys
```

So, call it 9 seconds. Here's the current commit:

```
> perf stat --repeat=1 bash -c "zcat ~/baked.log.gz | ./target/release/vector -qq --config ~/vector-nohop.toml"

 Performance counter stats for 'bash -c zcat ~/baked.log.gz | ./target/release/vector -qq --config ~/vector-nohop.toml':

         89,449.27 msec task-clock                #    3.142 CPUs utilized
         2,304,789      context-switches          #    0.026 M/sec
            16,775      cpu-migrations            #    0.188 K/sec
             6,936      page-faults               #    0.078 K/sec
   272,743,834,142      cycles                    #    3.049 GHz                      (83.35%)
    11,234,925,191      stalled-cycles-frontend   #    4.12% frontend cycles idle     (83.28%)
    80,432,308,439      stalled-cycles-backend    #   29.49% backend cycles idle      (83.32%)
   351,322,168,557      instructions              #    1.29  insn per cycle
                                                  #    0.23  stalled cycles per insn  (83.34%)
    66,846,126,854      branches                  #  747.308 M/sec                    (83.40%)
       510,121,615      branch-misses             #    0.76% of all branches          (83.31%)

      28.471103617 seconds time elapsed

      66.718430000 seconds user
      23.398695000 seconds sys
```

Call it +20 seconds. Notably if I change _almost anything else_ to do with how
the stream is processed the result is pessimized. Adding in a spawn_blocking
kicked the runtime up to 90s, so we're not CPU bound enough here to benefit from
the use of a background thread.

Signed-off-by: Brian L. Troutwine <brian@troutwine.us>

### CODE REVIEW

**Comment by jszwedko** [comment]
I'm a little confused, is the first perf output from master? Such that this change causes a significant slow down? Or is it vice-versa?

If needed, I'm ok with seeing this go in as a short-term fix, but remap maps closer to the model of a `FunctionTransform` which operate statelessly and can be run concurrently. Our aim with that was to push it up onto sources that have concurrency built in so that, for example, it could run N remap transforms for whatever level of concurrency the source has.

**Comment by blt** [comment]
> I'm a little confused, is the first perf output from master? Such that this change causes a significant slow down? Or is it vice-versa?

This commit but with the interior "transform" just turned into an identity, a baseline for the program.

> If needed, I'm ok with seeing this go in as a short-term fix, but remap maps closer to the model of a `FunctionTransform` which operate statelessly and can be run concurrently. Our aim with `FunctionTransform`s are to push it up onto sources that have concurrency built in so that, for example, it could run N remap transforms for whatever level of concurrency the source has. `TaskTransforms` are meant for stateful transforms that can not be run concurrently.

Yep, agreed. This is solely intended to be a short-term fix if it'll work at all. The big question here is can we introduce a little concurrency at the transform level to meet this near-term need? I see this kind of thing as being deprecated almost as soon as we release it for the approach you've just mentioned.

**Comment by jszwedko** [comment]
Gotcha, thanks for explaining 😄

**Comment by blt** [comment]
Going to close this out as it's an inappropriate solution for #6770 per most recent comment there.

**Pull request closed without merging**
