### PR TITLE
enhancement(statsd sink): Add supports for hostname and IPv6 address

### LINKED ISSUE #3277: The `statsd` sink should allow a  FQDN
It's likely this issue will overlap with the solution proposed in #3269 (wrapping the `socket` sink).

Currently, the `statsd` sink's `address` option takes an IP address. It should also support [fully qualified domain names](https://en.wikipedia.org/wiki/Fully_qualified_domain_name). Ex:

```toml
[sinks.my-statsd-sink]
type = "statsd"
address = "my.host.example:1234"
```

### PR DESCRIPTION
**Pull request by juchiast**
closes #3277

### CODE REVIEW

**Comment by binarylogic** [comment]
@juchiast what are your thoughts on wrapping the `socket` sink for this?

**Comment by juchiast** [comment]
@binarylogic I imagine it as adding a `mode = "tcp/udp"` option and build different clients, depending on the mode. So I don't think it will overlap or conflict with this PR a lot.

**Comment by binarylogic** [comment]
Sure, I just wanted to make sure you were aware that we can wrap other sinks. For example, the `papertrail` sink [wraps the `socket` sink (tcp mode) here](https://github.com/timberio/vector/blob/ce5b860aa7902c555cc3418b662cc490bc1b05e2/src/sinks/papertrail.rs#L40).

**Comment by juchiast** [comment]
Yeah I was not aware of that! Look like a better option.

**Comment by juchiast** [comment]
Let's close this, since I will address #3269 soon.

**Pull request closed without merging**
