### PR TITLE
enhancement(networking): Add support for systemd socket activation

### LINKED ISSUE #950: systemd.socket as source
Would be interesting to have a [`systemd.socket`](https://www.freedesktop.org/software/systemd/man/systemd.socket.html) as source to the vector.

The advantage of using it instead of listening directly a port is to it "queue" requests if the `vector.service` is being restarted in case of errors, updating the binary or updating the configurations.

### PR DESCRIPTION
**Pull request by bruceg**
This adds support for systemd socket activation to all the sources that use the `TcpSource` framework. That is, the syslog, tcp, and vector sources. It adds support for a new address type that indicates the socket is being passed in by systemd (or equivalent).

Closes #950 

I am not particularly comfortable with the `systemd#N` address syntax, but it was the best compromise I could think up. It is possible to autodetect when socket activation is in play, but since both Vector and systemd support multiple sockets, this creates an ambiguity with the order in which the sockets are used. I welcome alternate suggestions how to make it work better.

I have tested this on the command line using [systemfd](https://github.com/mitsuhiko/systemfd), but no automated tests are present other than address parsing.

### CODE REVIEW

**Comment by bruceg** [comment]
As this has impact on multiple sources, I was unclear what a proper semantic PR title would look like.

**Comment by binarylogic** [comment]
Yeah, I wish we could provide multiple, comma-separated scopes. Technically we could support that and deviate from the spec.

**Comment by binarylogic** [comment]
One thing I'd like to do address in the docs is the distinction between this and the `systemd` source, or at least a callout in the `systemd` source that systemd sockers can be used in the `tcp` and `vector` sources.

**Comment by bruceg** [comment]
> is the `udp` source not relevant here?

There is no reason why not, other than that I had limited my implementation to the common `TcpSource` framework. Extending it beyond should be straightforward now that those bits are working.

**Comment by bruceg** [comment]
> One thing I'd like to do address in the docs is the distinction between this and the `systemd` source, or at least a callout in the `systemd` source that systemd sockers can be used in the `tcp` and `vector` sources.

We don't actually have a `systemd` source, so I assume you're referring to the `journald` source. Is this still relevant there?

**Comment by binarylogic** [comment]
> We don't actually have a systemd source, so I assume you're referring to the journald source. Is this still relevant there?

Ha, you're right. It's somewhat relevant given that the 2 are tightly coupled, but less so now.

**Comment by bruceg** [comment]
> Small nitpick: should we give `"systemd"` as an example for all of the sources instead of just `"systemd#2"`? I feel like the basic version will likely be more common.

I was actually hoping for advice on that, or if the whole `"systemd"` bit was  the wrong approach to begin with. If you think the simple form is a better example, then simple it is.

**Comment by lukesteensen** [comment]
I like where you ended up with that! It seems relatively simple and unambiguous, and I would assume that in most cases users will only need the `systemd` version. The `#N` suffix also seems like a straighforward way to handle cases where they're passing multiple. I think it's good to give examples of both.

**Comment by bruceg** [comment]
@binarylogic to what do I need to change the title on this to make it a valid semantic PR title?

**Comment by binarylogic** [comment]
Hey @bruceg , you just need to pick a valid scope here:

https://github.com/timberio/vector/blob/b6a8778949d9fbb36637bec13bf9a9b03762663b/.github/semantic.yml#L12

I'd probably just use `networking` for now.

**Pull request merged**
