### PR TITLE
chore(operations): Update netlify to point to the latest version branch

### LINKED ISSUE #1594: Vector.dev should use the latest `v*` branch
Currently, vector.dev reflects the state of the `master` branch. This is problematic because our docs do not coincide with the latest version of Vector. It also does not reflect patch releases that are made on these branches (as is the case with `0.7.1`). I was aware of this caveat when we switched the website to Docusaurus 2.0 because the benefits outweighed the downsides. And at the time Docusaurus was working on versioned documentation. Unfortunately, their approach does not lean into git and instead implements [its own system of nested folders](https://v2.docusaurus.io/docs/versioning/). I thought this was odd and I think we're much better served to configure Netlify to deploy vector.dev from the latest `v*` branch.

This should be done ASAP given that the website does not reflect the latest release (0.7.1).

### PR DESCRIPTION
**Pull request by binarylogic**
Closes #1594

### CODE REVIEW

**Comment by a-rodin** [comment]
What would you think about an alternative approach:

* create a special tag `latest`, which would point to the latest release commit (in the version branch);
* set Netlify to use `latest` as the deployment branch.

The advantage is that no direct access to Netlify is needed when a new release is pushed.

**Comment by binarylogic** [comment]
Agree, I like that approach better.

**Comment by binarylogic** [comment]
I'll go with the branch strategy since Netlify cannot deploy tags. 

> But then we need do decide what would we do when a new minor version comes out: should we overwrite the latest branch to make it the same as the latest version branch or should we merge with the appropriate merging strategy option.

As long as we treat the branch as a reflect of the latest version then we should be safe to do either. We could even delete the branch and recreate it from the latest tag.

**Comment by binarylogic** [comment]
@a-rodin what do you think about this?

**Comment by a-rodin** [comment]
> I'll go with the branch strategy since Netlify cannot deploy tags.

It actually can, I tried it. It is possible to specify the tag name as the deployment branch (it's called "Production branch" in settings of the deploy contexts) and it would work, even if the given name is name of a tag and not of a branch.

The reason why it works is that Netlify's builder does something like

```
git clone https://github.com/timberio/vector
git checkout <Production branch name>
```

and this command works both with both branches and tags.

**Comment by binarylogic** [comment]
Hm. I updated the production branch to `v0.7.1`, which is a tag, and it failed with the following details:

```
7:03:23 PM: Starting to prepare the repo for build
7:03:24 PM: git ref refs/heads/v0.7.1 does not exist or you do not have permission
7:03:24 PM: Failing build: Failed to prepare repo
7:03:24 PM: failed during stage 'preparing repo': git ref refs/heads/v0.7.1 does not exist
```

You can see the deploy [here](https://app.netlify.com/sites/vector-project/deploys/5e2e28209448ed3c26f332c2).

**Comment by a-rodin** [comment]
I confirm this. It seems like they changed it just recently. Here is a build log from my successful deployment yesterday:

```
8:07:35 PM: Build ready to start
8:07:37 PM: build-image version: 9cade8af58c2cf3a17a1e9433d2e979149488837
8:07:37 PM: build-image tag: v3.3.5
8:07:37 PM: buildbot version: 036f37945d6de439a17a554b3ae02e2f8f0f1fb0
8:07:37 PM: Fetching cached dependencies
8:07:37 PM: Starting to download cache of 2.9KB
8:07:37 PM: Finished downloading cache in 68.796577ms
8:07:37 PM: Starting to extract cache
8:07:37 PM: Finished extracting cache in 7.69029ms
8:07:37 PM: Finished fetching cache in 76.943762ms
8:07:37 PM: Starting to prepare the repo for build
8:07:37 PM: Preparing Git Reference refs/tags/latest
8:07:38 PM: No build command found, continuing to publishing
8:07:38 PM: Starting to deploy site from '/'
8:07:38 PM: Creating deploy tree 
8:07:38 PM: 1 new files to upload
8:07:38 PM: 0 new functions to upload
8:07:39 PM: Starting post processing
8:07:39 PM: Post processing done
8:07:39 PM: Site is live
```

Note the that the reference is `refs/tags/latest`. However, when I tried to redeploy it today, I got the same error as you:

Today I tried to redeploy it and got the same error as you:

```
5:53:49 PM: Build ready to start
5:53:51 PM: build-image version: 9cade8af58c2cf3a17a1e9433d2e979149488837
5:53:51 PM: build-image tag: v3.3.5
5:53:51 PM: buildbot version: 036f37945d6de439a17a554b3ae02e2f8f0f1fb0
5:53:51 PM: Fetching cached dependencies
5:53:51 PM: Starting to download cache of 3.2KB
5:53:51 PM: Finished downloading cache in 122.217966ms
5:53:51 PM: Starting to extract cache
5:53:51 PM: Finished extracting cache in 7.878075ms
5:53:51 PM: Finished fetching cache in 130.423272ms
5:53:51 PM: Starting to prepare the repo for build
5:53:51 PM: git ref refs/heads/latest does not exist or you do not have permission
5:53:51 PM: Failing build: Failed to prepare repo
5:53:51 PM: failed during stage 'preparing repo': git ref refs/heads/latest does not exist
```

**Comment by a-rodin** [comment]
But setting the branch name explicitly to `refs/tags/latest` still works for me!

**Comment by Hoverbear** [comment]
I think this is done?

**Pull request closed without merging**
