### PR TITLE
fix(operations): Use rdkafka crate from the upstream Git repository

### PR DESCRIPTION
**Pull request by a-rodin**
Fixes `rdkafka` part of #1032.

Although it solves problem with compiling `rdkafka` crate, there are still linking issues with it unsolved yet.

### CODE REVIEW

**Comment by a-rodin** [comment]
The problem with CI is fede1024/rust-rdkafka#126. Newer versions of `rust-rdkafka` crate require `libclang` and `libllvm`. While the requirement might seem as too much, I generally like the reasoning behind switching to generation of bindings during build time implemented in fede1024/rust-rdkafka#119 because it simplifies compilation for new platforms. For example, without it #859 would be harder to do.

**Comment by benesch** [comment]
I just merged a change to rust-rdkafka that removes the build-time dependency on clang/libclang, if you want to give that a try! Details here: da77534c4cb72d8f5ce0b51fd20fc2a532f829a8

**Comment by LucioFranco** [comment]
@benesch would it be possible to get a release of this?

**Comment by benesch** [comment]
Sorry for the long delay here—but 0.23 is out and incorporates all the build system fixes.

**Pull request merged**
