### PR TITLE
fix(template website): Fix log output template

### LINKED ISSUE #8508: Component outputs are not correctly rendering in docs
Example: https://vector.dev/docs/reference/configuration/sources/file/#output

Screen Shot 2021-07-29 at 8 03 37 AM

The fields are missing and it seems to be using a description from another component?

### PR DESCRIPTION
**Pull request by lucperkins**
Fixes #8508

In general, the structured data templates could use some touching up, but this provides a decent-enough view layer for now.

Here's an example:

https://deploy-preview-8514--vector-project.netlify.app/docs/reference/configuration/sources/file/#output-logs

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]

**Comment by jszwedko** [comment]
Thanks for the quick fix on this @lucperkins !

Would it be possible to pull up the fields and remove `line` from:

Screen Shot 2021-07-29 at 12 47 52 PM

?

I'm actually not sure why we have the fields nested like that in the cue data, but I could see users being confused as there is no `line` field in the generated event from the `file` source.

**Comment by spencergilbert** [comment]
> I'm actually not sure why we have the fields nested like that in the cue data, but I could see users being confused as there is no `line` field in the generated event from the `file` source.

Oh mhmm... good catch

**Comment by jszwedko** [comment]
Actually, I guess I see why the data is modeled this way in case a component emits multiple types of logs though I don't think we have any components that do that right now.  I could still see the rendering here being slightly confusing, but I think this is ok as-is for now.

**Review by jszwedko — APPROVED** [review]

**Comment by lucperkins** [comment]
@jszwedko Actually, it turns out that there's at least one component with multiple log outputs: the [HTTP source](https://deploy-preview-8514--vector-project.netlify.app/docs/reference/configuration/sources/http/#output-logs).

**Comment by jszwedko** [comment]
> @jszwedko Actually, it turns out that there's at least one component with multiple log outputs: the [HTTP source](https://deploy-preview-8514--vector-project.netlify.app/docs/reference/configuration/sources/http/#output-logs). I just pushed up a solution that would convert the key (`line`, `text`, `structured`, etc.) into a heading and non-monospaced.

Aha! And so there is. 👍

**Comment by jszwedko** [comment]
Yeah, that looks better and less ambiguous that `line` is not a field. Thanks for thinking to make that adjustment @lucperkins

**Pull request merged**
