### PR TITLE
chore(deps): Reenable sasl

### LINKED ISSUE #3080: chore: Re-enable SASL in Kafka
Undo #2930 .

We'd like to release this stable. This can be in 0.11.0 or #2961 (0.10.0).

If left for 0.11.0, this will be a tracking issue for a highlight.

### PR DESCRIPTION
**Pull request by Hoverbear**
Closes #3080 :)

### CODE REVIEW

**Comment by Hoverbear** [comment]
Let's merge this for #2961

**Comment by fanatid** [comment]
Vendored build works on Windows?

`rdkafka-sys` depends from `sasl2-sys`
https://github.com/fede1024/rust-rdkafka/blob/0c02524ee95c509b8ec0de6c801016c2457ddf17/rdkafka-sys/Cargo.toml#L57

`sasl2-sys` depends from `krb5-src`
https://github.com/MaterializeInc/rust-sasl/blob/f54598c7e4815bc29852be7217f384e9b21b4966/sasl2-sys/Cargo.toml#L21

`rkb5-src` compile fail on windows
https://github.com/MaterializeInc/rust-krb5-src/pull/10

**Comment by Hoverbear** [comment]
Ah! I think I need to split up the vendor flags a bit better. :) Let's see...

**Comment by Hoverbear** [comment]
Need to disable sasl on MSVC for now.

**Comment by Hoverbear** [comment]
This looks good!

**Comment by fanatid** [comment]
So idea disable sasl for windows and enable for everything rest? Should `default` and `default-cmake` have `vendor-sasl` as `default-musl`?

**Comment by Hoverbear** [comment]
I think that's the easiest solution for now, yeah. :(

**Comment by MOZGIII** [comment]
Do we link sasl staticly now?

**Comment by fanatid** [comment]
Yes, `rdkafka/gssapi-vendored` feature should link the library statically.

**Comment by jszwedko** [comment]
Hi @smlgbl !

`sasl` is not enabled for the MUSL-based builds (aka alpine linux). It should work on the glibc-based builds though (`-debian` and `-distroless-libc`.

I can't remember why we don't enable it on MUSL builds though. I'll try to enable it and see what the build failure is.

**Pull request merged**
