### PR TITLE
chore(external docs): Extend with help about transparent gzip handling

### PR DESCRIPTION
**Pull request by danpalmer**
As discussed on Discord.

### CODE REVIEW

**Comment by danpalmer** [comment]
Not sure why the Semantic PR check thinks this isn't a correctly titled PR, my understanding is that `docs(compression): <title>` should be fine?

**Comment by binarylogic** [comment]
Thanks @danpalmer. Will look into the semantic failure. It should be fine for now.

**Comment by bruceg** [comment]
According to https://github.com/timberio/vector/blob/master/.github/semantic.yml, the best semantic tag for this would probably be `chore(external docs)` instead of `docs(compression)`.

**Comment by danpalmer** [comment]
@bruceg thanks for the tip! I'll update the Pull Request template too as that gives "docs" as a valid example.

**Review by jszwedko — APPROVED** [review]
Thanks @danpalmer !

**Pull request merged**
