### PR TITLE
fix(wasm transform): Fix parse_json Wasm function

### LINKED ISSUE #6397: WASM parse_json benchmark doesn't match the other parse_json implementations
The `benchmark_parse_json` function is intended to run the same operation in multiple scripting. https://github.com/timberio/vector/blob/9c0bdd3adca4fe9243cca75053c66d10ed2fe9eb/benches/languages.rs#L78

The source code for the WASM transform is missing a step: https://github.com/timberio/vector/blob/9c0bdd3adca4fe9243cca75053c66d10ed2fe9eb/tests/data/wasm/parse_json/src/lib.rs#L26

The JSON decoding it is doing in that function is the base decode needed by all WASM transforms to get at the event data. A second JSON decode is necessary, after accessing the `message` field of the source (log) event.

### PR DESCRIPTION
**Pull request by lucperkins**
Closes #6397

### CODE REVIEW

**Review by bruceg — APPROVED** [review]
LGTM

Incidentally, these sources made for a useful reference for describing how to write a WASM transform, as I couldn't find any examples in the docs. If I wasn't just missing the obvious again, that should probably be rectified as well.

**Comment by lucperkins** [comment]
@bruceg I'm not sure what specifically is on the agenda, but I do know that there are plans to do a Wasm improvement push sometime this year.

**Comment by jszwedko** [comment]
There are a couple of WASM guides that help with this:

https://vector.dev/guides/advanced/wasm-hello/
https://vector.dev/guides/advanced/wasm-multiline/

But agreed, it'd be nice to have additional documentation.

**Comment by lucperkins** [comment]
@jszwedko In addition to docs, I hope we get a chance to explore the growing universe of Wasm tools, because I think the dev experience is pretty subpar in general. Would love to be able to enable users to do something like this...

```rust
fn handle(event: Event) -> Result<Event, Error> {
    // logic here
}
```

...rather than needing all the boilerplate we currently require. Many be helper libs or templates for different languages.[]()

**Comment by jszwedko** [comment]
:thinking:  that would be nice; I think it'd require writing a library/framework for all "supported" languages though. We could do that while still allowing fallback to handling the data directly for languages where we haven't published the helpers.

**Comment by lucperkins** [comment]
@jszwedko Yeah, I think the story there would be much like language support in other domains: support the ones with the most traction and drawn wait and see on others. But in this case you'd essentially only be providing scaffolding to take an event in and emit an event back out, which is quite a different task from, say, building a REST API client.

**Pull request merged**
