### PR TITLE
chore: Remove unneeded remove clones

### PR DESCRIPTION
**Pull request by leshow**
When through to try and familiarize myself with the code, cleaned up a few things along the way.

- Removed unnecessary clones where I could find them
- In a few spots used closures to prevent `_or` param from being strictly evaluated
- simplified an if-else clause
- len() > 0 == !is_empty()
- &String -> &str (so the function can take both owned Strings and slices)
- redundant `into()` calls

Random question: I had some trouble building where I got a rustup error like `some components unavailable for download for channel 1.39.0: 'lldb-preview', 'miri'`. I don't get this error on `cargo build` in any other project. Am I not building the project correctly?

### CODE REVIEW

**Comment by binarylogic** [comment]
Thanks @leshow. We'll get someone to review and answer some of your questions.

**Comment by binarylogic** [comment]
@lukesteensen @LucioFranco I put both of you on this since it crosses into your domains.

**Comment by leshow** [comment]
Thanks! The build problem I mentioned is because my rustup profile is set to `complete` which includes things like `lldb-preview` and `miri`, in conjunction with the fact `vector` has toolchain `1.39.0` specified in it's `rust-toolchain` file. Any reason for targeting `1.39` explicitly instead of just `stable`?

To fix the build problem, setting the profile to `default` works, then it won't look for the extra rustup components.

**Comment by LucioFranco** [comment]
@leshow are you sure `lldb-preview` and `miri` work on stable at all? If not that sounds like a bug. The reason we pin to `1.39` is to make upgrading comlpiler versions very explicit and ensure that we are all using the same toolchian.

**Comment by LucioFranco** [comment]
Looks like there are a couple tests failing so once those are fixed this seems good to merge! Thanks for doing this!

**Comment by leshow** [comment]
Yes, apparently the complete profile is not design to work with stable. Those test should be fixed now, thanks!

**Comment by LucioFranco** [comment]
Thanks!

**Pull request merged**
