### PR TITLE
chore: Remove Docker nightly-date images and nightly-debian

### PR DESCRIPTION
**Pull request by jamtur01**
This will result in the following build in https://hub.docker.com/repository/docker/timberio/vecto

- timberio/vector:nightly-alpine

See also: https://github.com/timberio/vector-website/pull/104

Signed-off-by: James Turnbull <james@lovedthanlost.net>

### CODE REVIEW

**Review by Hoverbear — APPROVED** [review]

**Comment by binarylogic** [comment]
Is this a common pattern? It seems odd to shift nightlies to a separate repo. Vector is Vector 😄 . This seems like a hack for the unfortunate design decisions of Docker hub.

**Comment by jamtur01** [comment]
The user experience is Docker Hub's but our users have to live with it. :) Perhaps stop publishing the nightly-$DATE builds and stick with a single nightly image?

**Comment by binarylogic** [comment]
Yeah, I originally had it that way but added date-based nightlies due to feedback. I'd actually prefer that we remove nightlies entirely from Docker. I don't see any other popular projects doing this. If we start releasign more often it shouldn't be an issue.

**Comment by jamtur01** [comment]
Looks like Prometheus has a single nightly built from master. I feel like people do use Docker to get latest builds? I am less sure about a specific date. What was the reasoning?

**Comment by binarylogic** [comment]
The reasoning was to allow users to lock into a consistent nightly release so we wouldn't break things. But, again, they shouldn't feel the need to do that for long if we start releasing more often.

**Comment by jamtur01** [comment]
Then I recommend we go to the single nightly and up our release game. :)

**Comment by binarylogic** [comment]
Works for me.

**Pull request merged**
