### PR TITLE
enhancement(prometheus source): Adding extra configuration parameter

### PR DESCRIPTION
**Pull request by langecode**
Adding extra configuration parameter to Prometheus source to allow for customizing the metrics path (#3800)

### CODE REVIEW

**Comment by binarylogic** [comment]
Thanks @langecode, could this not be added to the `endpoints` configuration?

**Comment by jamtur01** [comment]
I think this works better as a separate option - https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config.

**Comment by binarylogic** [comment]
Sure. I guess I'm wondering what would stop someone from doing this?

```
endpoints = ["11.11.11.11:9100/path"]
```

And separating `path` will be shared across all provided endpoints, right? Is this better for service discovery?

**Comment by jszwedko** [comment]
I also think it'd be better to just encode it in the endpoint as this matches other usages of `endpoint` in vector, but this would break backwards compatibility. Maybe we could default to `/metrics` if no path is specified in the endpoint?

I see it is a separate option in the prometheus scraper, but then so is `scheme` which seems odd to me. I think that it would make sense to separate it if we access other resources based on the endpoint (like `/metrics` for metrics, `/logs` (doesn't exist) for logs), but I'm not aware of prometheus exporters exposing anything other than `/metrics`.

**Comment by jamtur01** [comment]
@jszwedko's comments make sense and I am swayed. :) I think the default to workaround the backwards compatibility.

**Comment by langecode** [comment]
Yeah, basically I introduced it as a separate option to allow it to be backwards compatible (and also inline with the Prometheus scrape configuration). However, there is kind of a semantic clash between the list of endpoints and the single metrics path configuration.

The use case here is to be able to use the Prometheus federation functionality. That is Prometheus is capable of exposing the metrics it has scraped for a federation scenario (https://prometheus.io/docs/prometheus/latest/federation/). The federate endpoint is not exposed as `/metrics` but `/federate` likewise some of the Kubernetes control plane components expose metrics with a hierarchical structure, like the kubelet exposes metrics on a paths `/metrics/cadvisor`, `/metrics/probes` etc.

Now why would I want to scrape the federate endpoint of Prometheus directly scraping? Well, to scrape endpoints inside of Kubernetes the kind of static configuration for Vector may fall short. I can scrape based on a Kubernetes Service resource however if that service is actually representing multiple Pods each scrape will only scrape metrics from one random Pod in the set. Alternative, if I configure Vector with the address of the individual Pods I would fail when Pods are restarted getting new IP addresses. Prometheus has logic to handle these cases doing discovery of endpoints to scrape through the Kubernetes APIs - hence I would like to use Prometheus for scraping my workloads and then use Vector to scrape Prometheus sending the data to a central place. Hence the need to specify another path.

Another solution would be to implement a source supporting the Prometheus `remote write` protocol having Prometheus push data into Vector (see #2058). But I would not be able to implement this in rust ;-)

**Comment by langecode** [comment]
If you would rather have the path as part of the URLs in the `endpoints` list I can do that. I do believe this would be hard to do in a backwards compatible way.

**Comment by langecode** [comment]
Found a workaround basically doing `endpoints = ["11.11.11.11:9090/federate?"]` which runtime will become `http://11.11.11.11:9090/federate?metrics` (because the current code will just append `metrics`). This solves my current usecase.

**Comment by jszwedko** [comment]
> If you would rather have the path as part of the URLs in the `endpoints` list I can do that. I do believe this would be hard to do in a backwards compatible way.

I think I'd prefer that, but I do agree that it'd be hard to do in a backwards compatible fashion. We can simply append it if there is no path to handle the simple case, but that wouldn't cover cases where people are doing something similar to what you mentioned: `endpoints = ["11.11.11.11:9090/something"]` where they still expect `/metrics` to be appended.

I'd personally be OK with breaking compatibility of appending an additional path (but still defaulting `/metrics` if there is no path to cover the general case).

Notably, `telegraf` also encodes it in the endpoint: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/prometheus.

**Comment by drunkirishcoder** [comment]
I agree that it's easier just make the path part of the url. I just ran into an issue where I need to scrape from Envoy which has the metrics exposed under `host:9000/stats/prometheus`.

One possible solution for the backwards compatibility may be keep the `hosts` as is, and add a new array `host_urls` where it expects the full paths? and two options can be mutually exclusive? maybe that's too complicated.

**Comment by drunkirishcoder** [comment]
another thought cross my mind... have the full path in the endpoints, but make appending `/metrics` behavior optional. you can toggle that off in the config and no `/metrics` will be appended to the urls.

**Comment by langecode** [comment]
Since most metrics are in fact exposed as `/metrics` I think that it makes sense to have this as the default path to scrape (seems to be similar behaviour in Prometheus itself). I think this is an argument to split of the specification of the path from the host in one way or another, either having the path as suggested by this PR or as @drunkirishcoder suggests a flag.

If the path is part of the URL together with the host I see no other way than requiring that `/metrics` is always explicitly added since in theory at least the metrics could also be expose on just the root path `/` automatically appending `/metrics` if there was no path given would break this.

However, as we have experimented more with our setup it turns out that we would probably not handle metrics through Prometheus `/federate` and Vector anyway. We tested as setup of:

```
service <- Prometheus <- Vector (local) -> Vector (remote) <- Prometheus
```

We want to scrape using Prometheus because of the support for service discovery within Kubernetes but we would like to use Vector to propagate this data elsewhere. However, with this setup a sampling is taking place in multiple places - first Prometheus, then Vector samples the `federate` endpoint, then Prometheus again samples Vector. This has a high risk introducing different levels of inaccuracies - so until support for the Prometheus `remote write` protocol might be available both for a source and a sink (#2058) I think we will have to do with another way of handling metric events.

**Comment by jszwedko** [comment]
> If the path is part of the URL together with the host I see no other way than requiring that /metrics is always explicitly added since in theory at least the metrics could also be expose on just the root path / automatically appending /metrics if there was no path given would break this.

I think we could only automatically add it if there was _no_ path. For example, if they provided an endpoint of `http://localhost:8080` we'd add `/metrics`, but if they provided `http;//localhost:8080/` we would not. I do agree that it is a bit tricky though, users that were previously using an endpoint ending with `/` and expecting it to be changed to `/metrics` would find the change incompatible. _Hopefully_ this would be a minority of cases, but it is difficult to say for sure. We could certainly highlight this as a "breaking change" in the release notes.

I agree that it'd be nice to support "remote write".

**Comment by drunkirishcoder** [comment]
wouldn't it be simpler and clearer if a new boolean option is introduced?

* if `true` then it will append `metrics` to all the paths in the array
* if `false` nothing is appended

I think that would be less confusing than if some paths in the array get appended and some don't all based on if there's a trailing `/` or not.

Also for backwards compatibility, can the boolean to `true`.

**Comment by langecode** [comment]
Yeah, we want the complete metrics event flow to avoid a resampling of the metrics.

However, just a comment to the configuration part. Imho, choosing between a boolean flag and the current proposal I would argue the current proposal to be the more clean approach. The “metrics” part already exists as a constant - non configurable - making this variable and configurable seems to me more clean the introducing a new parameter. It would be documented that this is appended to the endpoints and the default value would be documented as well. The impact of changing would be pretty clear. Basically making the postfix explicit with a default instead of implicit as it is now.

But this is just my opinion - even if we are not using the source anyway I guess I could find a bit of time to change the proposal, if you so wish.

**Comment by drunkirishcoder** [comment]
Unfortunately it doesn't work for my scenario where I need to scrape from endpoints with mixed suffixes without setting up multiple sources. I want to be able to do the following,

```
[sources.stats]
  type = "prometheus"
  hosts = ["http://localhost:9090/actuator/metrics", "http://localhost:9000/stats/prometheus?useonly"]
  append_metrics = false
  scrape_interval_secs = 15
```

So merely changing what's getting appended is not flexible enough. If I have multiple local endpoints all with varying suffixes, I will have to setup a separate scraper for each suffix. That feels a bit tedious.

**Comment by jszwedko** [comment]
Agreed, I'd still like to see the path simply encoded in each `endpoint`.

I agree that my suggestion of appending `/metrics` only if they provided no path could be surprising. We could opt to just make the backwards incompatible change of simply requiring `/metrics` be specified, if that is the correct path, as a breaking change in the release notes.

@binarylogic do you have an opinion?

**Comment by jszwedko** [comment]
I opened a PR to just remove the automatic appending of `/metrics` here: https://github.com/timberio/vector/pull/4276

**Comment by binarylogic** [comment]
@langecode thanks for your work here and bringing this to our attention. I'm going to close this in favor of https://github.com/timberio/vector/pull/4276.

**Pull request closed without merging**
