### PR TITLE
fix(prometheus source)!: Do not automatically append /metrics

### LINKED ISSUE #3800: Support custom path for Prometheus metrics
### Current Vector Version
```
0.10.0
```

### Use-cases

Currently the Prometheus source assumes Prometheus metrics to always be exposed on the given endpoint under a path `metrics`. While this is a good default it might not be the case - for instance to scrape the `federate` endpoint exposed by Prometheus itself it is necessary to be able to configure the URL.

### Attempted Solutions

One workaround would be to put a reverse proxy (e.g., nginx) in between Vector and the endpoint being scraped - however this is unnecessary complexity if the URL is fully configurable.

### Proposal

Add an extra configuration parameter to the Prometheus source allowing for configuring the path.

### PR DESCRIPTION
**Pull request by jszwedko**
This is a breaking change to just the configured endpoints as-is for the
`prometheus` source. Previously, `/metrics` was appended, but this
prohibited its use with prometheus exporters that do not use this path
(for example, a prometheus `federate` endpoint).

I added a couple of warning messages to help guide people that run into
issues when upgrading `vector` and depending on the current automatic
suffixing behavior of the `prometheus` source. If they fail to update,
I think they will commonly hit two types of errors:

* They will get a 404
* They will get a 200, but not prometheus output. For example, the
  `node_exporter` serves an HTML page on `/`.

Reference: #3801 discussion
Fixes #3800

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Review by jamtur01 — APPROVED** [review]
LGTM - This seems like less magical behavior.

**Comment by binarylogic** [comment]
@jszwedko I've noted this is in the new `prometheus` docs:

https://github.com/timberio/vector/blob/9b1eada50e8679bfe4f4e97660ef8cf6e2090dae/docs/reference/components/sources/prometheus.cue#L45

Is this good to merge then?

**Comment by jszwedko** [comment]
@binarylogic I think so. I'll rebase and get CI green.

**Comment by jszwedko** [comment]
I'll wait for a second approval given this is a breaking change (I tagged @Hoverbear), but I think it is good-to-go.

**Comment by jamtur01** [comment]
Ping @Hoverbear

**Pull request merged**
