### PR TITLE
enhancement(kubernetes_logs source): Expose `lines` option

### LINKED ISSUE #8070: Allow `fingerprint.lines` in kubernetes_logs too
hi,

in PR #7940 you added a new option `fingerprint.lines` so the fingerprinting now reads this number of lines. But in the `kubernetes_logs` module this value is hardcoded as 1. It would be great to make this configurable here too as we have k8s-logs with many zero-bytes at the beginning. it would be great to skip these zero's by setting the line value to a higher value.

### PR DESCRIPTION
**Pull request by ktff**
Closes #8070

I'm kinda reluctant to expose this for two reasons:
1. It exposes internal implementation.
2. It kinda isn't straightforward because of this sentence:
    `If the file has less than this amount of lines then it won't be read at all.` 
    Without knowing how the collection of logs from Kubernetes works users can shot them self in the foot by setting that value too high. That's because the logs are broken into several files, so the larger `lines` is the greater the chance is for the last logs of a container to be lost. So the way how collection works needs to be explained in the documentation. 

This should be fine as a quick fix, but considering how the problem of identifying files is difficult, it will probably be permanent. 

---
Ideally, we should only apply `lines` for the start of container logs. Which can be aproximated as the first logs we encounter for that container but this would require expanding `files` "source" with a concept of a group of files belonging to a same stream.

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]
I think the warning is fine, I think generally we shouldn't have too much of an issue with logs being split across files

**Comment by ktff** [comment]
It's just `dns::tests::resolve_vector` tests that are failling.

**Comment by jszwedko** [comment]
> This should be fine as a quick fix, but considering how the problem of identifying files is difficult, it will probably be permanent.

😅 very true.

This situation where multiple files start with the same line does seem like it'd be less likely to happen in the k8s world since (I believe?) the lines are guaranteed to have a timestamp. I think the warning you have is good though.

**Review by jszwedko — APPROVED** [review]

**Review by bruceg — APPROVED** [review]
LGTM

**Comment by bruceg** [comment]
I re-ran the tests to ensure they pass with DNS for vector.dev being restored.

**Pull request merged**
