### PR TITLE
fix(topology): It is now possible to reload a with a non-overlapping config

### PR DESCRIPTION
**Pull request by bittrance**
### Description

When rolling out a proper Chef recipe for Vector, I decided to change the naming in the config file, resulting in replacing all sources and sinks. When you remove the sink and the source, the output for a particular input will already have been removed, resulting in a panic when trying to notify the outputs of the removal for the respective input.
```
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::option::expect_failed
             at src/libcore/option.rs:1036
   9: core::option::Option<T>::expect
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/option.rs:314
  10: <std::collections::hash::map::HashMap<K,V,S> as core::ops::index::Index<&Q>>::index
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/collections/hash/map.rs:1041
  11: vector::topology::RunningTopology::remove_inputs
             at src/topology/mod.rs:391
  12: vector::topology::RunningTopology::spawn_all
             at src/topology/mod.rs:297
  13: vector::topology::RunningTopology::reload_config_and_respawn
             at src/topology/mod.rs:174
  14: vector::main::{{closure}}
             at src/main.rs:256
  15: tracing_core::dispatcher::with_default
             at /home/ec2-user/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-core-0.1.2/src/dispatcher.rs:205
  16: vector::main
             at src/main.rs:131
```
This PR fixes this particular case, but I suspect that might be other similar cases? The topology module is a bit dense, so I'm not sure. Whoever has detailed knowledge, feel free to co-opt this PR for a comprehensive solution.

### TODO

- [x] All commits are signedoff (See CONTRIBUTING.md). Forgot? `make signoff`.
- [x] CHANGELOG.md has been updated to reflect noteworthy changes.

### CODE REVIEW

**Comment by binarylogic** [comment]
@bittrance you're fantastic. Thanks for this. @lukesteensen or @LucioFranco should have enough knowledge on the topology module to help. We'll review and make sure we're not missing any other corner cases.

**Comment by LucioFranco** [comment]
@bittrance thanks for this! I pulled the changes down locally and actually found that the tests seem to fail sometimes. I've also added another test to ensure that this doesn't happen with a transform included. 

Here is my diff https://github.com/bittrance/vector/compare/fix-config-replace...timberio:lucio/fix-config-replace

If you don't get to it, I will take a look at this at some point between tomorrow and next week.

**Comment by bittrance** [comment]
> the tests seem to fail sometimes

Indeed, running on an AWS t2.medium node `topology::tests::topology_reload_healthchecks` fails on master on every run which includes all topology tests, but passes when run alone. Running `cargo test -- topology::tests --skip topology_reload_healthchecks` on this branch predictably fails `topology_replace_source_and_sink` while `cargo test -- topology::tests --skip topology_reload_healthchecks --skip topology_change_sink_no_gap` seems to predictably pass. Oh joy. I'll see what I can do.

As an aside, there are some other flaky tests I noted when running the whole test suite a repeatedly.
   
buffering test_max_size
crash test_source_error
crash test_source_panic

**Comment by LucioFranco** [comment]
@bittrance yeah the buffering max size test is a known one. We still have not gotten to the bottom of that one yet.

The other ones, do you by chance have a backtrace to that panic?

I think for the replace tests, the issue is that the sinks may not be driven all the way so the IO may hang and not complete thus the assert will fail. Im not sure its related to the change you are making.

**Comment by bittrance** [comment]
After a couple of hours of blindfold whack-a-mole (my favorite sport) I decided that it was time for some overkill instead. I ran the topology tests 10000 times (excluding topology_reload_healthchecks which fails predictably and topology_change_sink_no_gap which takes a minute to run). To be precise, I did
```
$ n=0; while [[ $n -lt 10000 ]] ; do RUST_BACKTRACE=1 cargo test -q -- tests::topology --skip topology_reload_healthchecks --skip topology_change_sink_no_gap ; n=$((n+1)) ; done | grep -vuE 'running [0-9]+ tests|test result: ok|^$' > run-1
```
The results are as follows:
```
$ grep -F stdout run-1 | sort | uniq -c
      1 ---- topology::tests::topology_add_sink stdout ----
     41 ---- topology::tests::topology_add_transform stdout ----
      1 ---- topology::tests::topology_change_transform stdout ----
     25 ---- topology::tests::topology_remove_sink stdout ----
     69 ---- topology::tests::topology_remove_source_add_source_with_same_port stdout ----
     10 ---- topology::tests::topology_replace_source_and_sink stdout ----
```
Nearly all these failures look something like this (see https://gist.github.com/bittrance/5d48b6ee090684af7f5a2f7012919132; note that topology_add_transform has been somewhat shortened, so the line numbers of tracebacks are not exactly as per this branch):
```
---- topology::tests::topology_remove_sink stdout ----
thread 'topology::tests::topology_remove_sink' panicked at 'assertion failed: `(left == right)`
  left: `100`,
 right: `0`', src/topology/mod.rs:645:9
```
That is, zero lines were received from the TCP sink. It is always binary: either all lines were received or all lines were lost. I first thought this was because of a socket lifecycle issue, but no amount of `wait_for_tcp` seems to affect test failure rates. The race condition is probably somewhere else, but I've not been able to come up with a verifiable theory.

These tests generally have too many moving parts. If I may make a suggestion, it would be to write a test-only source and sink, each based around a `std::sync::mpsc::channel` that the tests can directly read and write. That would do away with all the synchronization issues the current tests face and allows operating directly with events.

I'm running the same procedure on master to be sure the results are similar; will post an update tomorrow.

**Comment by bittrance** [comment]
topology_reload_healthchecks fails thusly:
```
---- topology::tests::topology_reload_healthchecks stdout ----
thread 'topology::tests::topology_reload_healthchecks' panicked at 'called `Result::unwrap()` on an `Err` value: Canceled', src/libcore/result.rs:999:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:208
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/macros.rs:18
   9: core::result::Result<T,E>::unwrap
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/result.rs:800
  10: tokio::runtime::threadpool::Runtime::block_on
             at /home/ec2-user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/mod.rs:269
  11: vector::test_util::block_on
             at src/test_util.rs:98
  12: vector::topology::tests::topology_reload_healthchecks
             at src/topology/mod.rs:1303
  13: vector::topology::tests::topology_reload_healthchecks::{{closure}}
             at src/topology/mod.rs:1212
  14: core::ops::function::FnOnce::call_once
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/ops/function.rs:231
  15: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:704
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  17: test::run_test::run_test_inner::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panicking.rs:272
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panic.rs:394
             at src/libtest/lib.rs:1468
```

**Comment by LucioFranco** [comment]
@bittrance Thanks for looking into this! I think the move to `mpsc::channel` is a good one actually. Since we want to test topology, not the TCP source/sink.

I do believe in general our topology tests require a major refactor since they are some of our original tests they are quite old.

Overall, with this PR I think this is fine to merge, since anyways we will have to attempt to fix the topology tests in general soon.

**Comment by bittrance** [comment]
@LucioFranco Very good. I took the liberty of replacing my original test (`topology_replace_source_and_sink`) with your `topology_replace_source_transform_and_sink` since it is a superset.

**Comment by LucioFranco** [comment]
@bittrance I'm still seeing the new test case fail every once and while? I know we talked about updating the topology to use channels instead, I was curious if you made any progress on that? I'm not sure if this failing of the replace test is due to a bug within the topology or something weird OS level going on.

**Comment by LucioFranco** [comment]
@bittrance I checked this change locally and it looks good! thanks!

**Pull request merged**
