### PR TITLE
chore(operations): Check kube and docker code

### PR DESCRIPTION
**Pull request by LucioFranco**
this should allow code check to also check our feature flagged tests.

Signed-off-by: Lucio Franco <luciofranco14@gmail.com>

### CODE REVIEW

**Comment by binarylogic** [comment]
Anyway this could just be the default vs having to whitelist all features?

**Comment by LucioFranco** [comment]
@binarylogic we have default stuff that require docker and/or kube behind feature flags so its easy to run the majority of our test suite via `cargo test` without needing to stand up docker. I use this a lot.

**Comment by LucioFranco** [comment]
So its catching the errors that were live on master, so I think this should be good to go.

**Comment by a-rodin** [comment]
Does it make sense to also update `test-docker` service in `docker-compose.yml` or add a new job `test-kubernetes` to `docker-compose.yml` and `tests/Makefile`?

**Pull request merged**
