### PR TITLE
chore: Use a forked version of leveldb-sys

### LINKED ISSUE #7514: Fork leveldb to apply lower mmap limit
While investigating #7246 and other issues, we've identified that leveldb will mmap up to 1000 files at 4 MB per file. This commonly results in users running into OOM issues using disk buffers.

Unfortunately, this value is not configurable so, to modify it, we have to fork `leveldb-sys` to change it here:

https://github.com/skade/leveldb-sys/blob/c5383aaf9e264041c951e9a2aa7381613d0d0dba/deps/leveldb-1.22/util/env_posix.cc#L46

### PR DESCRIPTION
**Pull request by blt**
The forked version of leveldb-sys patched in here limits leveldb to a maximum of
10 mmap'ed LDB files, reducing the total memory burden of vector. Upstream
leveldb will map 1000 files, so there's quite a difference in memory
usage. Unfortunately this 10 is not configurable.

At the moment the fork is under my personal Github account. I think we ought to
fork to timberio -- we have an archived version -- and pin the patch to a SHA. I
don't have enough juice in the Github org to achieve this.

Resolves #7514

Signed-off-by: Brian L. Troutwine <brian@troutwine.us>

### CODE REVIEW

**Review by jszwedko — COMMENTED** [review]
Nice, thank you!

I unarchived https://github.com/timberio/leveldb-sys and made sure everyone has access. I think you should be able to switch it over there if you like.

This changed `Cargo.lock` much more than I anticipated. Did you mean to upgrade all of those packages? The Tokio 1.6 upgrade #7477 is currently blocked on a test failure (which I also see on this PR).

**Comment by blt** [comment]
> thinking this is still modifying Cargo.lock much more than I would expect for this change.

I ended up needing to run `cargo update` when introducing the patch. That's where most of the lockfile churn comes from.

Now that you mention it, let me see if I can't avoid running `cargo update`. I think I see a way.

**Comment by blt** [comment]
@jszwedko ah, hmm. No dice. When adding the patch I am forced to run `cargo update`. I'd be game to run `cargo update` in another PR and rebase this one after that.

**Comment by jszwedko** [comment]
I think you could just do `cargo update -p leveldb-sys`?

**Comment by jszwedko** [comment]
@blt I think I did it in fdc7891

**Review by jszwedko — APPROVED** [review]

**Pull request merged**
