### PR TITLE
docs: Update metric docs according to new data model

### PR DESCRIPTION
**Pull request by loony-bean**
Follow up of #1217

### CODE REVIEW

**Comment by binarylogic** [comment]
Thanks! Do you know if [this page](https://vector.dev/docs/about/data-model/metric) will change at all?

**Comment by loony-bean** [comment]
> Thanks! Do you know if [this page](https://vector.dev/docs/about/data-model/metric) will change at all?

Oh right. There are [few more](https://github.com/timberio/vector/search?l=Markdown&q=%22val%22) places I need to update.

**Comment by binarylogic** [comment]
Ok. You should be able to update the metric fields via the `metric_fields.toml` file:

https://github.com/timberio/vector/blob/master/.meta/metric_fields.toml

**Comment by loony-bean** [comment]
@binarylogic JFYI I've tried to update the model doc, but the [result](https://deploy-preview-1268--vector-project.netlify.com/docs/about/data-model/metric) still has some issues.

1. The examples in the # Schema lack some nesting. E.g. there is no `tags` field, but the `host` is inlined into the dict.
2. Value fields should have `struct` type, but I thought it would be easier to describe them as `map`. Unfortunately, the examples section is truncated, and information there is not accurate.
3. The SVG was not updated.

I'd go on fixing all these, but I'd like to ask if you think it's something I could easily do and not interfere with any other parts of docs?

**Comment by binarylogic** [comment]
Thanks. I'll review and see if I can take it to the finish line.

**Comment by loony-bean** [comment]
@binarylogic I was thinking if we could get this merged and create a separate issue for what's left?

**Comment by binarylogic** [comment]
@loony-bean I just pushed some changes. This should be good to go. Could you review the `metrics_fields.toml` file and make sure my descriptions are accurate? If not, feel free to change them. Once doen go ahead and merge.

**Comment by loony-bean** [comment]
@binarylogic Thanks for helping!

**Pull request merged**
