### PR TITLE
enhancement(lua transform): Switch from rlua to mlua

### PR DESCRIPTION
**Pull request by khvzak**
`mlua` supports Lua 5.1 - 5.4 (5.4.3 is the latest) and provides API similar to `rlua`.
You can easily switch to LuaJIT (for example) by changing `lua54` feature flag to `luajit`.

Besides, `mlua` supports async/await, optional `Send` and serialization.

Regarding performance and memory usage, `mlua` is more gently to GC compared to `rlua`. For example, `rlua` on **each** Rust function call [creates a userdata object just in case](https://github.com/amethyst/rlua/blob/master/src/util.rs#L375), to use it for errors handling. 
`mlua` instead [reuses](https://github.com/khvzak/mlua/blob/v0.6.1/src/lua.rs#L2318) previously created and unsed objects.

This PR also addresses #7177

### CODE REVIEW

**Comment by khvzak** [comment]
I noticed a performance regression and need to check the code.

As I see, vector's transforms-lua code is a bit suboptimal because it creates a new Lua function every time when execute `transform()` which is pretty heavy operation.
`mlua` is optimized for executing functions rather than creation of objects. 

Seems `send` feature flag is not needed because I don't see `Send` requirements and maybe `scope` could be removed.

**Comment by jszwedko** [comment]
Thanks for this @khvzak ! Is it ready for review? Or are you still digging into the performance issues.

**Comment by khvzak** [comment]
@jszwedko I'm still investigating the performance regression. Eventually want to make even faster than before.

**Comment by khvzak** [comment]
@jszwedko 
The PR is ready for review.
I made some improvements to mlua (performance) and will release new version (0.6.2) before merging to master.

**Comment by jszwedko** [comment]
Thanks @khvzak ! I'll make sure this gets a look next week.

**Review by bruceg — APPROVED** [review]
Thanks for this work @khvzak. This looks pretty straightforward, mostly just conversion of conventions. I am a little concerned that the benchmarks are showing a small regression, but it may be balanced by a small improvement in other benchmarks. See https://github.com/timberio/vector/pull/8055/checks?check_run_id=3032384009#step:17:35 Is any of that expected?

**Comment by khvzak** [comment]
@bruceg 
Thanks for reviewing!
I don't get performance regressions when testing locally on macos (comparing with the master branch).
Will check on linux and fix.

**Comment by khvzak** [comment]
@jszwedko could you run the workflow please to get latest benchmarking results?

**Comment by khvzak** [comment]
I just published mlua v0.6.2 and updated version here.
I think this PR is ready to be merged.

By the way, I noticed about 8-10% performance regression in Lua 5.4 (compared to 5.3) in UserData creation in mlua internal benchmarks. But this depends on Lua version only.
Also, If you willing to switch to luajit, please let me know. I might need to make a few changes. 
Vector uses `__pairs` metamethod in Lua v1 that is support in luajit only in lua5.2 compatibility mode.

**Review by jszwedko — APPROVED** [review]
Awesome, thanks @khvzak . This looks good to me. I see the regressions are no longer present. Thanks for digging into them.

**Comment by jszwedko** [comment]
I marked this to be merged. Thanks for the contribution @khvzak !

**Pull request merged**
