### PR TITLE
chore(operations): Dynamically derive the list of paths to create at target

### PR DESCRIPTION
**Pull request by MOZGIII**

### CODE REVIEW

**Comment by bednar** [comment]
Hi @MOZGIII,

is there any workaround for MacOS? 

Because a default bash doesn't have a `mapfile`:

```
make generate
/Users/bednar/Developer/bonitoo/vector/scripts/run.sh generate
scripts/prepare-target-dir.sh: line 15: mapfile: command not found
make: *** [generate] Error 127
```

Regards

**Comment by MOZGIII** [comment]
A workaround is to `brew install bash`. Though, this is probably a good idea to revisit this: for people without bash it's an annoying blocker.

**Comment by bednar** [comment]
Yeah, installing `bash` is workaround... I am a little bit scared 😄 because new macOS has a `zsh` as a default shell

**Comment by binarylogic** [comment]
https://github.com/timberio/vector/pull/2539 should fix this

**Comment by bednar** [comment]
@binarylogic thanks

**Pull request merged**
