### PR TITLE
fix(tests): Added vendor-openssl to the azure_log_monitor feature

### LINKED ISSUE #4616: Errors in azure_monitor_logs sink when running check components
@nazar554 Just spotted these. Could you please take a look?

Thanks!

```
+ cargo check --tests --no-default-features --features sinks-azure_monitor_logs
    Checking vector v0.11.0 (/home/james/src/vector)
error[E0599]: no method named `sign_oneshot_to_vec` found for struct `openssl::sign::Signer<'_>` in the current scope
   --> src/sinks/azure_monitor_logs.rs:272:32
    |
272 |         let signature = signer.sign_oneshot_to_vec(string_to_hash.as_bytes())?;
    |                                ^^^^^^^^^^^^^^^^^^^ method not found in `openssl::sign::Signer<'_>`

error[E0277]: the size for values of type `[u8]` cannot be known at compilation time
   --> src/sinks/azure_monitor_logs.rs:272:13
    |
272 |         let signature = signer.sign_oneshot_to_vec(string_to_hash.as_bytes())?;
    |             ^^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `[u8]`
    = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
    = note: all local variables must have a statically known size
    = help: unsized locals are gated as an unstable feature

error[E0277]: the size for values of type `[u8]` cannot be known at compilation time
   --> src/sinks/azure_monitor_logs.rs:272:25
    |
272 |         let signature = signer.sign_oneshot_to_vec(string_to_hash.as_bytes())?;
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `[u8]`
    = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
    = note: all local variables must have a statically known size
    = help: unsized locals are gated as an unstable feature

error[E0277]: the size for values of type `[u8]` cannot be known at compilation time
   --> src/sinks/azure_monitor_logs.rs:272:78
    |
272 |         let signature = signer.sign_oneshot_to_vec(string_to_hash.as_bytes())?;
    |                                                                              ^ doesn't have a size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `[u8]`
    = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
    = note: required by `config::_::_serde::export::Err`

error: aborting due to 4 previous errors

Some errors have detailed explanations: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `vector`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error[E0599]: no method named `sign_oneshot_to_vec` found for struct `openssl::sign::Signer<'_>` in the current scope
   --> src/sinks/azure_monitor_logs.rs:272:32
    |
272 |         let signature = signer.sign_oneshot_to_vec(string_to_hash.as_bytes())?;
    |                                ^^^^^^^^^^^^^^^^^^^ method not found in `openssl::sign::Signer<'_>`

error[E0277]: the size for values of type `[u8]` cannot be known at compilation time
   --> src/sinks/azure_monitor_logs.rs:272:13
    |
272 |         let signature = signer.sign_oneshot_to_vec(string_to_hash.as_bytes())?;
    |             ^^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `[u8]`
    = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
    = note: all local variables must have a statically known size
    = help: unsized locals are gated as an unstable feature

error[E0277]: the size for values of type `[u8]` cannot be known at compilation time
   --> src/sinks/azure_monitor_logs.rs:272:25
    |
272 |         let signature = signer.sign_oneshot_to_vec(string_to_hash.as_bytes())?;
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `[u8]`
    = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
    = note: all local variables must have a statically known size
    = help: unsized locals are gated as an unstable feature

error[E0277]: the size for values of type `[u8]` cannot be known at compilation time
   --> src/sinks/azure_monitor_logs.rs:272:78
    |
272 |         let signature = signer.sign_oneshot_to_vec(string_to_hash.as_bytes())?;
    |                                                                              ^ doesn't have a size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `[u8]`
    = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
    = note: required by `config::_::_serde::export::Err`

error: aborting due to 4 previous errors

Some errors have detailed explanations: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
error: build failed
+ exit 255
xargs: sh: exited with status 255; aborting
make: *** [check-component-features] Error 124
```

### PR DESCRIPTION
**Pull request by jamtur01**
Closes #4616 

Signed-off-by: James Turnbull <james@lovedthanlost.net>

### CODE REVIEW

**Review by jszwedko — COMMENTED** [review]
@Hoverbear will probably have a more informed opinion, but I was thinking we might want to instead add some of these `vendor-*` features specifically to the component check in `./scripts/check-component-features` as I believe we want to leave the `vendor-*` features as opt-in. I believe this change would make vendoring openssl mandatory for `sinks-azure_monitor_logs`.

Albeit, adding them as "default features" in component check script, ala `--no-default-features --features sinks-azure_monitor_logs,vendor-openssl`, I think, would result in it building them even if the particular component doesn't need openssl. This seems fine though, if unoptimal, for the purpose of the checks.

**Comment by jamtur01** [comment]
I considered that option but the script is pretty basic and I didn't want to include everything for every check - I'll leave open for @Hoverbear to comment.

**Comment by nazar554** [comment]
There is also an option to use `sign_to_vec` instead of `sign_oneshot_to_vec` which is available in both OpenSSL 1.0 and 1.1, can provide a PR if needed

**Comment by jamtur01** [comment]
@nazar554 That's probably simplest I think - PR appreciated. Thanks @nazar554!

**Comment by nazar554** [comment]
Done, you can check #4623

**Comment by jamtur01** [comment]
Closing in favor #4623.

**Pull request closed without merging**
