### PR TITLE
chore: Teach `Event` what its size is

### LINKED ISSUE #8272: `Event` should know how big it is
Consider that in #8263 I've [demonstrated](https://github.com/timberio/vector/issues/8263#issuecomment-879417074) that the byte size measurement of the blackhole sink is a non-trivial cost center for vector. The `Event` should evolve a `len` or `byte_size` or similar method that tallies up the in-memory byte size of the `Event`. This implies we'd need to maintain this value as we manipulate the event.

### PR DESCRIPTION
**Pull request by blt**
This commit introduces the `ByteSizeOf` trait into vector-core and implements
this for the `Event` type, focused specifically on the `LogEvent` side of that
structure in testing. This allows us to determine how big `Event` is in memory
without necessarily serializing it. The current implementation for `Event`
trawls through any collections to get the size of the structure but there's no
reason if we need constant time access why this can't be a continually
maintained value.

This has bearing on issue #8263, both in the recognition that the blackhole sink
is slow because of serialization to get byte size and in a similar constraint on
the datadog logs sink for similar reasons. 

Resolves #8272

Signed-off-by: Brian L. Troutwine <brian@troutwine.us>

### CODE REVIEW

**Review by tobz — APPROVED** [review]
I like it.  Great way to enforce proper accounting for event sizing via the type system.

**Comment by blt** [comment]
Cool. I intend to follow this up with a derive macro since the manual implementation requires you to know what counts as allocated versus not, but I'm glad the basic idea lands.

**Review by jszwedko — COMMENTED** [review]
Nice! Very happy to see this. I think we could use this to drive `bytes_in_total` and `bytes_out_toal` for transforms.

**Comment by blt** [comment]
That is absolutely the plan. :)

**Comment by jszwedko** [comment]
😄 I opened https://github.com/timberio/vector/issues/8405 to track that since I couldn't find an issue for it.

**Pull request merged**
