### PR TITLE
perf(tests): Enable optimizations for benchmarks

### LINKED ISSUE #1798: Set Rust flag `codegen-units` to 1 for release Vector builds
The results of tests performed by @bruceg in https://github.com/timberio/vector/issues/309#issuecomment-586505606 show that `codegen-units=1` Rust flag can reduce Vector binary size by 13%.

I think it is worth to add support for setting it to `scripts/build-archive.sh` script and enable it by default for release archives.

### LINKED ISSUE #2326: Enable optimizations for benchmarks
Currently running `cargo bench` uses uses debug builds for benchmarking:

https://github.com/timberio/vector/blob/fb8ae10f193c1990259500941ddd90f01472063e/Cargo.toml#L12-L13

In order to ensure that we benchmark the same kind of generated code which is used in production builds, it is necessary to use release builds with LTO and `codegen-units=1` for the `bench` profile.

### PR DESCRIPTION
**Pull request by a-rodin**
Closes #2326.
Closes #1798.

### CODE REVIEW

**Comment by LucioFranco** [comment]
do you have any bench numbers for this?

**Comment by binarylogic** [comment]
I've updated the issue to close #1798 as well.

**Comment by Hoverbear** [comment]
Luke noted in https://github.com/timberio/vector/issues/2326#issuecomment-613579312 `debug` is on intentionally for profiling reasons.

**Comment by binarylogic** [comment]
@a-rodin is this still relevant given the comments?

**Comment by binarylogic** [comment]
@a-rodin mind chiming in here?

**Comment by binarylogic** [comment]
@Hoverbear should we close this?

**Comment by Hoverbear** [comment]
CLosing...

**Pull request closed without merging**
