### PR TITLE
enhancement(kafka sink): allow send metrics to kafka

### LINKED ISSUE #5341: Allow sending metrics via the Kafka sink & source
As noted on [HN](https://news.ycombinator.com/item?id=25280311), we don't currently allow you to send metrics directly via the Kafka sink. There's no technical reason to disallow this, especially now that the text and JSON encoding formats of metrics are better defined and already being used in other sinks.

### PR DESCRIPTION
**Pull request by fanatid**
Closes #5341. This PR only about sending metrics to kafka.

### CODE REVIEW

**Review by jszwedko — COMMENTED** [review]
I think you need to update the `input_type` on `impl SinkConfig for KafkaSinkConfig` to `DataType::Any`.

Also, I'm not super familiar with Kafka, but I think users will probably want to set the topic key field for metrics too, no? Users may opt to set it to a static key or template it based on metric tags.

**Comment by fanatid** [comment]
> `DataType::Any`
I had this in plans but forgot to change =(

Was not sure about key, but static / template based on tags is a good idea, will add it!

**Comment by fanatid** [comment]
@jszwedko instead static / template I implement value from tags by key

**Comment by binarylogic** [comment]
@fanatid doesn't this close #5341?

**Comment by fanatid** [comment]
For close #5341 we also need need parse metrics in kafka source (but instead of changing kafka source I think it would be better use remap for parsing metrics).

**Comment by binarylogic** [comment]
@fanatid we are holding off the `kafka` source work for now. #5341 only addresses the `kafka` sink, which it appears to be covered in this PR.

For the `kafka` source, we'll likely want to wait on #5124 before proceeding. We currently solve this with Protobufs, but only for direct Vector to Vector communication (`vector` source and sink). Persisting the data onto Kafka introduces other concerns that we'll need to consider before proceeding. Like backward compatibility and so on.

**Pull request merged**
