### PR TITLE
chore: remove unused code

### PR DESCRIPTION
**Pull request by tshepang**
I don't know why so much code had to go... I just followed build warnings and errors.

### CODE REVIEW

**Comment by blt** [comment]
I'm all for removing code. That said, I'm curious @tshepang what OS you use and what compiler warning/errors you're referring to, so I can understand more of the motivation for this change? The problem this runs into is that a goodly chunk of the code you've removed is live on Windows so moving forward with this would be less a removal process and more flagging off code for non-Windows builds.

**Comment by tshepang** [comment]
It's Linux. I guess if it fails on Windows, it's missing some cfg flags (so the code does not run on Linux)?

**Comment by blt** [comment]
> It's Linux. 

How are you compiling vector? I work on Linux and a simple `cargo build` doesn't turn up any warnings. We also recently flagged on warnings as errors -- see #7733 -- so I want to make sure we aren't missing something. 

> I guess if it fails on Windows, it's missing some cfg flags (so that the code does not get built on Linux)?

Yep. Straight removal is not appropriate but flagging code off to only compile on Windows would be.

**Comment by tshepang** [comment]
```
❯ cargo check
warning: field is never read: `name`
   --> src/service.rs:130:5
    |
130 |     pub name: OsString,
    |     ^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

warning: field is never read: `display_name`
   --> src/service.rs:131:5
    |
131 |     pub display_name: OsString,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: field is never read: `description`
   --> src/service.rs:132:5
    |
132 |     pub description: OsString,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^

warning: field is never read: `executable_path`
   --> src/service.rs:134:5
    |
134 |     pub executable_path: std::path::PathBuf,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: field is never read: `launch_arguments`
   --> src/service.rs:135:5
    |
135 |     pub launch_arguments: Vec<OsString>,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by jszwedko** [comment]
@tshepang interesting, I don't see the same on Amazon Linux 2 when running `cargo check`. Could you provide `cargo --version`?

**Comment by jszwedko** [comment]
Thanks for reporting this @tshepang . I see that the nightly toolchain does flag this. I opened https://github.com/timberio/vector/pull/7994 to fix that.

**Pull request closed without merging**
