### PR TITLE
fix(kubernetes platform): Adhere to ct linting rules

### PR DESCRIPTION
**Pull request by langecode**
Running [chart testing](https://github.com/helm/chart-testing) against the Helm charts had a few minor issues - below is the output. This PR fixes this allowing the charts to successfully pass linting.

```
➜  vector git:(master) ✗ docker run -it --rm -v $(pwd):/src quay.io/helmpack/chart-testing:v3.3.1 sh -c "cd /src; ct lint --chart-dirs distribution/helm --all --validate-maintainers=false"
Linting charts...
Version increment checking disabled.

------------------------------------------------------------------------------------------------------------------------
 Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
 vector => (version: "0.0.0", path: "distribution/helm/vector")
 vector-agent => (version: "0.0.0", path: "distribution/helm/vector-agent")
 vector-aggregator => (version: "0.0.0", path: "distribution/helm/vector-aggregator")
 vector-shared => (version: "0.1.0", path: "distribution/helm/vector-shared")
------------------------------------------------------------------------------------------------------------------------

Saving 2 charts
Deleting outdated charts
walk.go:74: found symbolic link in path: /src/distribution/helm/vector/charts/vector-agent resolves to /src/distribution/helm/vector-agent
walk.go:74: found symbolic link in path: /src/distribution/helm/vector/charts/vector-agent/charts/vector-shared resolves to /src/distribution/helm/vector-shared
walk.go:74: found symbolic link in path: /src/distribution/helm/vector/charts/vector-aggregator resolves to /src/distribution/helm/vector-aggregator
walk.go:74: found symbolic link in path: /src/distribution/helm/vector/charts/vector-aggregator/charts/vector-shared resolves to /src/distribution/helm/vector-shared
walk.go:74: found symbolic link in path: /src/distribution/helm/vector-agent/charts/vector-shared resolves to /src/distribution/helm/vector-shared
walk.go:74: found symbolic link in path: /src/distribution/helm/vector-aggregator/charts/vector-shared resolves to /src/distribution/helm/vector-shared
Linting chart 'vector => (version: "0.0.0", path: "distribution/helm/vector")'
Validating /src/distribution/helm/vector/Chart.yaml...
Validation success! 👍
distribution/helm/vector/Chart.yaml
  6:18      error    too few spaces before comment  (comments)
  7:21      error    too few spaces before comment  (comments)

Saving 1 charts
Deleting outdated charts
walk.go:74: found symbolic link in path: /src/distribution/helm/vector-agent/charts/vector-shared resolves to /src/distribution/helm/vector-shared
Linting chart 'vector-agent => (version: "0.0.0", path: "distribution/helm/vector-agent")'
Validating /src/distribution/helm/vector-agent/Chart.yaml...
Validation success! 👍
distribution/helm/vector-agent/Chart.yaml
  6:18      error    too few spaces before comment  (comments)
  7:21      error    too few spaces before comment  (comments)

Saving 1 charts
Deleting outdated charts
walk.go:74: found symbolic link in path: /src/distribution/helm/vector-aggregator/charts/vector-shared resolves to /src/distribution/helm/vector-shared
Linting chart 'vector-aggregator => (version: "0.0.0", path: "distribution/helm/vector-aggregator")'
Validating /src/distribution/helm/vector-aggregator/Chart.yaml...
Validation success! 👍
distribution/helm/vector-aggregator/Chart.yaml
  6:18      error    too few spaces before comment  (comments)
  7:21      error    too few spaces before comment  (comments)

Linting chart 'vector-shared => (version: "0.1.0", path: "distribution/helm/vector-shared")'
Validating /src/distribution/helm/vector-shared/Chart.yaml...
Validation success! 👍
[Errno 2] No such file or directory: 'distribution/helm/vector-shared/values.yaml'
------------------------------------------------------------------------------------------------------------------------
 ✖︎ vector => (version: "0.0.0", path: "distribution/helm/vector") > Error waiting for process: exit status 1
 ✖︎ vector-agent => (version: "0.0.0", path: "distribution/helm/vector-agent") > Error waiting for process: exit status 1
 ✖︎ vector-aggregator => (version: "0.0.0", path: "distribution/helm/vector-aggregator") > Error waiting for process: exit status 1
 ✖︎ vector-shared => (version: "0.1.0", path: "distribution/helm/vector-shared") > Error waiting for process: exit status 255
------------------------------------------------------------------------------------------------------------------------
Error: Error linting charts: Error processing charts
Error linting charts: Error processing charts
```

### CODE REVIEW

**Comment by MOZGIII** [comment]
Thanks for the PR! I didn't realize `ct` had extra rules compared to the usual `helm lint`.
We already have a linting setup for the charts, just not with the `ct` but with `helm lint`.

The findings of this tool are not too useful though:
- the two spaces before comments rule seems bizarre, there is no real reason for it to exist;
- the missing `values.yaml` in the `vector-shared` is actually *supposed to be absent*, since it's a library chart; I wonder why the `ct` tool insists it should be present - this might be confusing.

That said, I guess we could easily add the `ct` to our CI suite if it is deemed useful. @eeyun what do you think?

**Comment by langecode** [comment]
Yeah, I agree with your comments.

ct runs more than Helm lint, though. I think the concrete rule with two spaces is for readability when a comment is put after a yaml property.

As for the values.yaml I did not realize that this was never supposed to be in a library chart. It seems ct should consider the "type" in Chart.yaml - I take a look at ct.

**Comment by langecode** [comment]
..just ran it because we use it in other places. However, it strikes me there is actually something more `ct` can do. It can do multiple lint runs by placing putting `*-values.yaml` files into a `ci` directory in the chart. Thus it would be possible to make sure a chart renders, e.g., with and without the vector source enabled.

**Comment by eeyun** [comment]
@langecode thanks so much for the PR!

@MOZGIII if the helm community is by-and-large congregating behind chart-test then its probably not a bad idea for us to do so as well and yeah I guess I would be :+1: on getting it into the CI suite.

**Comment by MOZGIII** [comment]
> ..just ran it because we use it in other places. However, it strikes me there is actually something more `ct` can do. It can do multiple lint runs by placing putting `*-values.yaml` files into a `ci` directory in the chart. Thus it would be possible to make sure a chart renders, e.g., with and without the vector source enabled.

It's something we're currently solving as via snapshot testing at https://github.com/timberio/vector/pull/5673

**Comment by MOZGIII** [comment]
> @langecode thanks so much for the PR!
> 
> @MOZGIII if the helm community is by-and-large congregating behind chart-test then its probably not a bad idea for us to do so as well and yeah I guess I would be 👍 on getting it into the CI suite.

My original rationale for sticking with `helm lint` was that `ct` is more suited for pile-of-helm-chars repos, rather than a monorepo with both charts and something else. But I guess it's a minor issue, let's include it!

I'm going to merge this PR as-is for now, and we can add CI handling for this later to keep the `ct` check as an invariant.

**Review by MOZGIII — APPROVED** [review]

**Pull request merged**
