### PR TITLE
fix(cli): watch-config cannot use an env var, it's not compatible with bool flags

### PR DESCRIPTION
**Pull request by jeromegn**
It turns out using an `env` fallback on a bool flag will require a value for it.

Here's the output I get without this change:

```
error: The argument '--watch-config <watch-config>' requires a value but none was supplied

USAGE:
    vector --color <color> --config <config>... --log-format <log-format> --verbose --watch-config <watch-config>

For more information try --help
```

I believe this is caused by: https://github.com/TeXitoi/structopt/issues/428

### CODE REVIEW

**Comment by jamtur01** [comment]
Hi @jeromegn Can I please get you to sign your commits so our DCO passes? (See https://github.com/timberio/vector/blob/master/CONTRIBUTING.md#signing-off for details) Thanks!

**Comment by jeromegn** [comment]
My bad, I skimmed the contributing guidelines.

Just force pushed a signed commit.

**Review by jszwedko — COMMENTED** [review]
Thanks @jeromegn !

I agree that we should remove it from `structopt` given the referenced issue.

What would you think of maintaining support for the environment variable by applying it in https://github.com/timberio/vector/blob/75c23c42ba8ea46b94f4c5a52a280ced57f5f160/src/app.rs#L54 ? It will likely require making `watch_config` an `Option<bool>`.

I do see that referenced clap issue in https://github.com/TeXitoi/structopt/issues/428, https://github.com/clap-rs/clap/issues/1476, was resolved so maybe structopt will support it natively soon.

**Comment by jeromegn** [comment]
As you probably saw in the issue, this won't be possible until a major release of structopt? If I understand correctly.

I'm fine adding back an env var, I might not have time to do it for a while though.

**Comment by jszwedko** [comment]
:+1: I did see the comment https://github.com/TeXitoi/structopt/issues/428#issuecomment-754087460

I think it'd be nice to still maintain the environment variable even if it requires doing it manually for now.

**Comment by jszwedko** [comment]
I took another look at this and I'm not seeing an easy way to handle it right now without https://github.com/TeXitoi/structopt/issues/428 being resolved. Changing it to take an `Option<bool>` to add env var support  manually results in it wanting a value again even though it is a flag.

I'll close this out for now, but hopefully we can revisit in the future when `structopt` is updated.

**Pull request closed without merging**
