### PR TITLE
chore(observability): Enable API by default

### PR DESCRIPTION
**Pull request by leebenson**
Small PR on the road to #5083. Enables the API by default. This was already bound to 127.0.0.1:8686 by default, so it should be relatively safe.

Renames `bind` -> `address` to follow the precedent set elsewhere in the config.

### CODE REVIEW

**Comment by leebenson** [comment]
cc @lucperkins for #5072 if this gets merged

**Comment by leebenson** [comment]
One breaking change this would introduce, of course, is that 8686 would suddenly be bound where it wasn't before. Currently that results in a hard crash. The default JMX port is 8686, FWIW.

Is there another behaviour we'd prefer?

Other options:

- Don't crash. Just say we couldn't start the API. Pros: Not breaking. Cons: Non-deterministic save for reading logs.
- Choose another free/random port. Pros: The API still starts. Cons: We have no idea where (unless reading logs.)

**Review by jamtur01 — APPROVED** [review]
LGTM

**Comment by jszwedko** [comment]
This ship may have sailed, but my preference is still no default binding to the network :smile: 

I think:

* It is more surprising than not to find an observability agent like vector opening a network port when not configured to given it isn't required for normal operation. I'm imagining users coming from fluentbit, fluentd, beats, etc. where monitoring endpoints must be enabled (to my knowledge)
* It exposes, albeit not terribly sensitive at the moment, information to any process or user on the machine. Once we add sampling of events, this could expose more sensitive information; once we add config mutations, probably more

The downside, as I understand it, is that `vector top` won't work out-of-the-box. For this, I'd prefer the socket approach mentioned by #5083. If we don't end up going the socket route for whatever reason, `vector top` could be specific about its suggestion of enabling the HTTP API if it doesn't find anything at the default port.

**Comment by leebenson** [comment]
> This ship may have sailed, but my preference is still no default binding to the network 😄

I don't think the ship has sailed, but I think the biggest sticking point is the UX around unblocking the GraphQL API, playground and (soon), the web UI.

We can get `vector top` to work out-the-box with a socket, since we're in control of both the server and client. But I don't know of a good way to unblock the other features that generally are consumed via a browser. At least not without introducing a local proxy and requiring an explicit setting that would make it clear to the user that we're opening a port.

Maybe that's fine, and `vector top` alone is worth the workaround, and everything else needs to set explicitly. But it feels to me like vector top is really just a stepping stone to the full web UI, so I'd rather avoid making special provisions for it if we can. 

There's some complexity in juggling unix sockets, setting file permissions, adapting to Windows, etc. And some edge cases that are easy to run into -- like, if one user spawns `vector` and the .sock file doesn't get cleaned up, and another user later does the same and hits permission errors from the first run. There's workarounds, but it's a lot of work just to make `vector top` work out the box in one very specific scenario (i.e. running `vector top` on the same system that has compatible permissions with a running `vector`). The playground, API, remote `vector top` viewing and the web UI will all still need explicit permissions in this paradigm.

Given this, I'd rather definitively fall on either side of:

1. Enable nothing. Keep the explicit `api.enabled = true` setting, and stick to the network.
2. Enable everything, a la this PR -- but make it as safe as we can, and be as clear as we can (in docs, etc) that a port is being opened.

I think a lot of this is perception. If users are likely to be spooked by opening _any_ port -- even one bound to `127.0.0.1` -- then I'd absolutely keep it turned off. I don't know where to draw the line between perception and feature convenience here.

**Comment by binarylogic** [comment]
I can update the docs to include it, so it's not a big deal either way. If this compromises security it should be off by default. If we're talking about imaginary operator preferences then I would like to keep it on since the UX for `vector top` and other tools will be clunky. Tools that are of significant value to the user and us an organization.

**Comment by leebenson** [comment]
> If this compromises security it should be off by default

@jamtur01, @Hoverbear might want to weigh in, here. What's the threat level binding to `127.0.0.1`?

I know if _something else_ on the system is compromised and can execute arbitrary HTTP requests to a local port there's a possibility of an attack, but in practice it's not much difference to accessing a local file socket, save for file permissions.

There's also the issue of opening a port that may already be taken, but that feels like a problem domain that's shared by _any_ tool that opens a port, so I'm not sure that's a big enough issue alone. [I suggested some options here](https://github.com/timberio/vector/pull/5114#issuecomment-730467138).

Is this a problem? Or is it perception?

**Comment by tyrken** [comment]
Sorry to barge in (as a hopelessly biased sample-of-one example of your user-base who happened to be browsing wondering when 0.11 will come), but I'd vote on the side of caution.  While some of your users might be happy at "it just works" us more senior/old-timers would be fairly surprised at a logging agent opening an unexpected port, even on a UNIX socket.

Make it as easy as possible to enable (command-line arg, env-var, config file and helm chart options, log entry notice suggesting it as it starts up), put in some help text from `vector top` when it can't connect, but don't enable it by default.  I'd doubt you'll lose sales over this either way & willing to be overruled, but...

**Comment by leebenson** [comment]
@tyrken, thanks so much for weighing in. Great to hear from a user on this. @binarylogic, over to you.

**Comment by binarylogic** [comment]
Off by default it is. I'll just include in our docs so users can opt-in if they'd like. Can you make sure the error messages for `vector top` are clear and instruct the user how to enable the API?

**Comment by leebenson** [comment]
I'll close this, to keep the current behaviour of disabling by default.

Currently, the error message a user will seeing when running `vector top` without a backing Vector instance is:

```
Vector API server not reachable. Have you enabled the API?
```

We could certainly augment that. Do you have a preference? I'm thinking one of:

```
Vector API server not reachable. Have you enabled the API?
Visit https://vector.dev/<api_docs> for help.
```

Or, perhaps more directly:

```
Vector API server not reachable. Have you enabled the API?

To enable the API, add the following to your `vector.toml` config file:

[api]
  enabled = true
```

**Comment by binarylogic** [comment]
I prefer the last example.

**Comment by leebenson** [comment]
Cool, thanks both -- on it 👍

**Pull request closed without merging**
