### PR TITLE
chore(kubernetes_logs source): Document minimum required version for Kubernetes

### LINKED ISSUE #8738: Better document MSKV for `kubernetes_logs` source
Today it's only mentioned at the bottom of the docs: https://vector.dev/docs/reference/configuration/sources/kubernetes_logs/#testing-reliability

Other components have a `requirements` section that more explicitly state things like this: https://vector.dev/docs/reference/configuration/sinks/clickhouse/#requirements

### PR DESCRIPTION
**Pull request by spencergilbert**
Signed-off-by: Spencer Gilbert <spencer.gilbert@datadoghq.com>

Closes #8738

https://deploy-preview-8744--vector-project.netlify.app/docs/reference/configuration/sources/kubernetes_logs/

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]

**Comment by binarylogic** [comment]
Isn't the source of truth here?

https://github.com/timberio/vector/blob/master/website/cue/reference/services/kubernetes.cue#L7

**Comment by spencergilbert** [comment]
> Isn't the source of truth here?
> 
> https://github.com/timberio/vector/blob/master/website/cue/reference/services/kubernetes.cue#L7

🤔  is that specific to the `kubernetes_logs` source or more general? ie the support for running vector on kubernetes (via helm) is different than supported versions for the logs source.

**Comment by binarylogic** [comment]
It was meant to be all of Kubernetes. We should have one version we support for the platform and that's it. All components should support that version or we should raise the version to the lowest common version.

**Comment by spencergilbert** [comment]
@binarylogic @jszwedko updated to be driven off the `service.kubernetes.version` value

**Review by jszwedko — APPROVED** [review]
Ideally the component pages would automatically display this information, but I see it is currently lacking so 👍

**Pull request merged**
