### PR TITLE
chore: Update toolchain to 1.46

### PR DESCRIPTION
**Pull request by jamtur01**
Signed-off-by: James Turnbull <james@lovedthanlost.net>

### CODE REVIEW

**Comment by binarylogic** [comment]
Godspeed

**Comment by jamtur01** [comment]
LOL. We'll see how bad it is. :)

**Comment by jszwedko** [comment]
We should make sure to test out the nightly build process with this PR too. You can kick it off manually from: https://github.com/timberio/vector/actions?query=workflow%3Anightly

**Comment by jamtur01** [comment]
@jszwedko Thanks - yeah that's next.

**Comment by Hoverbear** [comment]
@jamtur01 You'll need to upgrade to llvm10 first. :( Thsi is what #3657 will do for you, please be patient. :)

**Comment by jamtur01** [comment]
@Hoverbear Thanks. I was curious about any other fixes and what else might fail too.

**Comment by Hoverbear** [comment]
@jamtur01 Yeah! Please feel free to push on this, but please don't merge this without a release update!

**Comment by jamtur01** [comment]
Closing for now. Will reopen when llvm is higher.

**Pull request closed without merging**
