### PR TITLE
fix(file source): Read empty lines

### PR DESCRIPTION
**Pull request by jszwedko**
The file source currently skips empty lines, but I can't think of
a reason we should do that. At least not by default.

Fixes: #8363

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Review by lukesteensen — APPROVED** [review]
Seems reasonable to me! Might be worth adding a simple test if we want to ensure this remains the behavior moving forward.

**Comment by jszwedko** [comment]
👍 test added in 93a093c

**Review by bruceg — COMMENTED** [review]
The code is straightforward enough, but I wonder if this shouldn't have a configuration option. It is a change in behavior that could be surprising to some users.

**Comment by jszwedko** [comment]
True, it is a behavior change, but I think the current behavior is a bug. Granted all bugs become features in time 😄

**Comment by spencergilbert** [comment]
Compromise and note it in the release notes?

**Pull request merged**
