### PR TITLE
chore(operations): Move over homebrew/s3 release jobs

### PR DESCRIPTION
**Pull request by Hoverbear**
This PR goes ahead and creates an entirely new workflow for releases that only trigger on release tags. It seemed to be intended from https://github.com/timberio/vector/issues/2797 and I think that it makes sense.

In the future we can adopt more distinction between "Nightly jobs, such as audits/fuzzing/prop-testing/benching" and "release tasks, such as publishing artifacts, images, releases, and binaries". For now, they are coarsely similar.

This PR is **incomplete** as it depends on a `BRADY_BOT_TOKEN` set in the https://github.com/timberio/vector/settings/secrets to publish to the homebrew tap.

Please note I haven't tested this, I wasn't able to find any sort of check/dry run options and I'm not entirely comfortable with just running random release scripts and seeing what happens.

### CODE REVIEW

**Comment by Hoverbear** [comment]
@binarylogic this could use your eyes and maybe you could help me with that token?

**Comment by vector-vic** [comment]
Brady was let go from Timber and replaced by me. I'll Slack you my GH token.

**Comment by Hoverbear** [comment]
Dog gone it!

**Comment by Hoverbear** [comment]
So this should work, with the caveat that I can't really test this, so we're kind of just winging it.

**Comment by binarylogic** [comment]
https://github.com/timberio/vector/issues/2961 should be a good opportunity to test this :)

**Comment by Hoverbear** [comment]
Let's see how it goes

**Pull request merged**
