### PR TITLE
chore: Remove unused features

### PR DESCRIPTION
**Pull request by blt**
While I work on #7072 I need to consider where the division lines in
this project are. This commit is a consequence of me taking a look through the
project's Cargo.toml.

Some unused dependencies have been removed, down from 894 linked crates to 828.

Signed-off-by: Brian L. Troutwine <brian@troutwine.us>

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
👍 for being specific!

It does look like we are missing one needed feature (see CI check failure):

```
src/kubernetes/stream.rs#L84
no function or associated item named `wrap_stream` found for struct `hyper::Body` in the current scope
```

**Comment by blt** [comment]
> 👍 for being specific!
> 
> It does look like we are missing one needed feature (see CI check failure):
> 
> ```
> src/kubernetes/stream.rs#L84
> no function or associated item named `wrap_stream` found for struct `hyper::Body` in the current scope
> ```

That’s very fixable.

**Comment by blt** [comment]
@jszwedko FYI it looks like the homebrew pull for coreutils is returning 403. Assuming everything else passes I'll restart that job later.

**Comment by blt** [comment]
Ah, I see you've addressed this in #7095. Always one step ahead of things, @jszwedko.

**Comment by blt** [comment]
Discovered as a part of the work for #7027.

**Pull request merged**
