### PR TITLE
chore(kubernetes): Adds schema for helm values.json

### PR DESCRIPTION
**Pull request by eeyun**
@MOZGIII this is gonna need a thorough review. But this is as close as I could refine it without some extra input. Somewhat tedious but hopefully its close!

Signed-off-by: Ian Henry <ianjhenry00@gmail.com>

### CODE REVIEW

**Comment by MOZGIII** [comment]
Can we explore the possibility of sharing and reusing the bits of the schemas across charts?
It currently covers the `vector-agent` chart, but it and `vector-aggregator` both reuse some includes from `vector-shared`:

https://github.com/timberio/vector/blob/a894cf7cc5370f0d7176dc11a7b93838a045a2c9/distribution/helm/vector-agent/templates/podmonitor.yaml#L1

https://github.com/timberio/vector/blob/a894cf7cc5370f0d7176dc11a7b93838a045a2c9/distribution/helm/vector-aggregator/templates/podmonitor.yaml#L1

Those literally use the same configuration values that come from the `vector-shared` definition:
https://github.com/timberio/vector/blob/a894cf7cc5370f0d7176dc11a7b93838a045a2c9/distribution/helm/vector-shared/templates/_metrics.tpl#L72-L110

So for cases like this, it would make sense to share the config bits for values schema - so that it easier to maintain.
I.e. the idea is to match the schema organization with the implementation's internal organization.

**Comment by eeyun** [comment]
@MOZGIII do you have any suggestions for how you'd like to accomplish that? I'd also like to avoid duplicating these if possible but aside from writing another script to template these (which _might_ be a complex task) I'm not entirely certain how we'd achieve this.

**Comment by MOZGIII** [comment]
> @MOZGIII do you have any suggestions for how you'd like to accomplish that? I'd also like to avoid duplicating these if possible but aside from writing another script to template these (which _might_ be a complex task) I'm not entirely certain how we'd achieve this.

I only have some rough ideas in mind, not sure if they're going to work with Helm. Let me try a couple of things first, and I'll get back to you with something.

**Comment by MOZGIII** [comment]
Even though the schema is there, I don't think it will be maintainable. Let's put this on hold for now, and continue with adding the Helm chart values to the cue for documentation purposes (https://github.com/timberio/vector/issues/5036). My hope is once that is done, we can leverage the cue data to derive the schemas automatically. This would be way better than maintaining the schemas and the cue files separately, plus we can do fancy stuff with the cue files to aid with defining things.
In case it doesn't look better, we can get back to this implementation and proceed with it.

**Comment by binarylogic** [comment]
@eeyun @MOZGIII is this related to an issue? Just curious if we had a discussion about this approach before doing it and then abandoning it?

**Comment by eeyun** [comment]
Closing as won't complete superseded by #5036.

**Pull request closed without merging**
