### PR TITLE
chore: Extract global allocator into a crate

### LINKED ISSUE #6163: Make sure we are actually using jemalloc as the global allocator for benches
We think we are currently running the benches with the default allocator. We should bench with jemalloc given that is the most common allocator we distribute vector with.

### PR DESCRIPTION
**Pull request by MOZGIII**
This PR extracts the global allocator directive into a dedicated crate, and introduces a more error-resistant logic picking the global allocator via features.
For instance, now users will be alerted and the compile will fail if the global allocator was not picked sanely (either explicitly via feature flag, ~or via default autodetection~) - thus ensuring that occasional `--no-default-features` won't mess up the global allocator silently.

Closes #6163.

To do:
- [x] make all CI flows pass

### CODE REVIEW

**Review by jszwedko — COMMENTED** [review]
This is looking good! I like the reorganization and the use of `cfg` to control the default allocator.

**Comment by MOZGIII** [comment]
> This is looking good! I like the reorganization and the use of `cfg` to control the default allocator.

I've just changed it back to requiring explicit allocator pick be passed from the outside. I decided to go with it because it:
- simplifies the mental model a lot
- work better with already established logic at `Cargo.toml` - after some thinking, I realized this is effectively the ultimate approach we'll get to either way after some further iterations, so I figured we just have to use it; it's not immediately obvious this approach is optimal, it's rooted in the present shortcomings of the cargo and surrounding tooling

**Review by lukesteensen — COMMENTED** [review]
Could you expand a bit on the problem that's being solved here? It's not entirely clear to me why we need to do any of this.

**Comment by MOZGIII** [comment]
> Could you expand a bit on the problem that's being solved here? It's not entirely clear to me why we need to do any of this.

Sure!

We have the following goals:
- ensure the allocator is always set for each of the build targets, and that we never miss setting it; you'd think it's already solved, but what I discovered is there are some cases when we are falling back to the system allocator silently - it will be much easier to maintain if we get an explicit error if neither the system, nor jemalloc allocator is picked intentionally
- prepare the place at where we can define the allocators to be used by vector that is also suitable for writing some standalone benches - so we can share this code with benches without linking the whole `vector` crate

**Comment by MOZGIII** [comment]
I'm realizing this might take some time to get a consensus on this PR, so I extracted part of this PR that addresses just the corrections of the allocator picks at #6195 - which we can hopefully merge sooner.
This one is still useful because it helps to avoid issues like the one #6195 fixes in the future.

**Comment by lukesteensen** [comment]
> ensure the allocator is always set for each of the build targets, and that we never miss setting it; you'd think it's already solved, but what I discovered is there are some cases when we are falling back to the system allocator silently - it will be much easier to maintain if we get an explicit error if neither the system, nor jemalloc allocator is picked intentionally

I'm not entirely convinced this is a problem. The way that any rust program works is that you use the system allocator unless it's overriden to use something else. That seems fine to me? We definitely should ensure that our benchmarks are using right set of features to match our production builds, but that doesn't feel like something that's worth building a whole new crate and changing the way allocators are set. 

I get that this enables more decoupled and complex allocator options, but I just don't think that's something that's worth adding a whole new crate and unfamiliar layer on top of `#[global_allocator]`. If we needed to support a whole bunch of different allocators or had an expectation that we'd be changing them often, then I'd likely feel differently. But realistically we just need them to match our production builds. If we want to evaluate new allocators, that's easy enough to do as a one-off task locally and doesn't need to be automated. Maybe someday, but I think there are currently much better ways to spend our benchmarking efforts.

**Comment by MOZGIII** [comment]
> a whole new crate and unfamiliar layer on top of `#[global_allocator]`

I thought about it more, and I think it is justified in the end. What we get from this new crate is:
1. It itself is tested.
2. It makes allocator usage rules stricter for all of the consumers.
3. It isn't a large change (out of 500 added lines, 350 is the license and a significant part of the rest are tests), I expect maintenance to be minimal since the crate exposes no API at all.
4. If everything is fine - this approach is transparent to the devs and users, it should only intervene if an issue is detected.

> If we needed to support a whole bunch of different allocators or had an expectation that we'd be changing them often, then I'd likely feel differently. But realistically we just need them to match our production builds. If we want to evaluate new allocators, that's easy enough to do as a one-off task locally and doesn't need to be automated.

Agreed. However, this PR is useful as-is already, without even considering further work of adding more allocators. Checking an allocator manually is indeed very easy. This change facilitates it, but it's not a primary goal really - just another benefit if we end up reacting to use it sometime later.

> Maybe someday, but I think there are currently much better ways to spend our benchmarking efforts.

I agree, there's better value in other things currently than adding more allocators. We only aimed to solve the uncertainty about the global_allocator being set everywhere as of now.

Comparing this PR and #6195 - I think the difference is this PR is a continuous fix for the problem, and the #6195 is a one-time thing.

> doesn't feel like something that's worth building a whole new crate and changing the way allocators are set.

This could technically be implemented in the same `vector` crate, so if this being a separate crate is a significant part of why you don't like it - I could try moving this back into `vector` crate - albeit there are some downsides with this. The main value for this implementation being at a separate crate is that it allows comprehensive testing.
The way the allocators are set is not that different - the only new thing - and, essentially, the core of the change - is that instead of letting the system silently fallback to the system allocator we require people to state it explicitly. It can be as compact as 5 lines of code (if we're not counting the crate wrapping, comments and tests).


I do understand your hesitation, so I tried to provide some arguments on both why this change is something we need, and why it is not really that bad. If you're still not convinced it's something that we should have - I think it won't be mergeable in any form (no consensus), but if the implementation is what's problematic, not the core idea - I'd be happy to do a couple more iterations.

**Comment by jszwedko** [comment]
@lukesteensen do you mind giving this another look? I think the real advantage is ensuring the use of the allocator everywhere and I also view the overhead as minimal and unlikely to change much after its introduction. I'm happy to talk about this in real-time too.

**Review by lukesteensen — COMMENTED** [review]
I gave this another look and I still think I'm mildly against it, but am happy to defer to those working more closely on the benchmarks if they feel it's solving a real problem.

My reasons are roughly as follows:

1. This is one more non-standard thing for new contributors to bump into around our feature "system", which is already quite complex as it is.
2. The value of strictness is mostly around things we expect to change at least somewhat frequently, and I don't think our choice of allocator falls into that category.
3. Dedicated criterion benchmark targets are not somewhere I necessarily expect to see allocator workloads representative of real world use, which reduces the potential value here a bit.

**Comment by jszwedko** [comment]
@blt do you mind taking a look at this?

It is similar to https://github.com/timberio/vector/pull/6195 but that PR didn't end up being sufficient.

I can definitely understand the concerns in https://github.com/timberio/vector/pull/6181#pullrequestreview-599133682 . My thought is that we just try it and see. We can always swap it back later if it turns out to be a problem. I like the explicitness of which allocator is used where rather than defaulting to the system allocator unintentionally.

**Review by blt — APPROVED** [review]
I'm for this. Similar reasoning to #6195.

**Pull request merged**
