### PR TITLE
chore(elasticsearch sink)!: Nest the AWS endpoint/region options under `aws`

### PR DESCRIPTION
**Pull request by bruceg**
References #1608 

This has no documentation changes, as they are hard coded into the generate script. Some thought will need to be given to how to rework that to allow for the nesting.

### CODE REVIEW

**Comment by binarylogic** [comment]
Thanks! I can work on the docs. To clarify:

1. If `host` is set that overrides everything.
2. Then if `aws.region` is set that will automatically populate `hostname`.
3. And if `aws.endpoint` is set that will set `hostname`? It seems like `aws.endpoint` is not necessary, correct?

Just making sure I understand everything.

**Comment by bruceg** [comment]
1. If `auth` is unset or set to `"aws"` then `host` is used.
2. Else exactly one of `aws.region` and `aws.endpoint` must be set, and they are handled the same as in other AWS sinks:
  a. If `aws.region` is set it will set an automatic host URL.
  b. Else `aws.endpoint` will be used as the host URL.

**Comment by binarylogic** [comment]
> If auth is unset or set to "aws" then host is used.

Did you mean "not set to aws"?

**Comment by bruceg** [comment]
> Did you mean "not set to aws"?

I actually meant "set to basic".

**Comment by binarylogic** [comment]
Hm, are additional requests made for the auth process that would require the `aws.*` options?

In my opinion, there is no need to even have the `aws.region` or `aws.endpoint` options since both can be covered with the `host` option. AWS provides a full hostname for their ES clusters, so I'd rather remove the `aws.*` options entirely and _just_ require the `host` option. What do you think?

**Comment by bruceg** [comment]
It is possible to remove the `aws.*` options as you say. However, all the other AWS sinks use the `region` config magic so it was used here as well for consistency.

**Comment by binarylogic** [comment]
Let's remove them for this sink. I think it makes less sense in this context since it is not an AWS specific sink. As long as the `host` option can properly serve AWS then that should simplify things.

**Comment by bruceg** [comment]
I opened a new PR #1703 for dropping the AWS options.

**Comment by binarylogic** [comment]
@bruceg I need to make the doc changes before we do this. I'm working on it.

**Comment by binarylogic** [comment]
Sorry, wrong PR. We should close this one.

**Pull request closed without merging**
