### PR TITLE
fix(config): Allow global schema to reload

### PR DESCRIPTION
**Pull request by LucioFranco**
This is a follow up to @Hoverbear's work. Initially, our global schema didn't support reloading. This adds arc_swap to allow us to modify the global state. This is far from ideal, though I think for now its fine to add this. I think follow up work should think about threading the global schema as that will be much more performant and easier to reason about but at the cost that its much more verbose.

Benches against (a7aa9e):

```
pipe                    time:   [210.20 ms 213.76 ms 216.95 ms]
                        thrpt:  [43.958 MiB/s 44.614 MiB/s 45.371 MiB/s]
                 change:
                        time:   [+7.5374% +10.131% +13.221%] (p = 0.00 < 0.05)
                        thrpt:  [-11.677% -9.1991% -7.0091%]
                        Performance has regressed.
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high mild

Benchmarking pipe_with_tiny_lines: Warming up for 3.0000 s
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 9.6s.
pipe_with_tiny_lines    time:   [168.35 ms 171.84 ms 175.12 ms]
                        thrpt:  [557.64 KiB/s 568.31 KiB/s 580.09 KiB/s]
                 change:
                        time:   [+11.510% +17.617% +23.748%] (p = 0.00 < 0.05)
                        thrpt:  [-19.190% -14.978% -10.322%]
                        Performance has regressed.
Found 3 outliers among 10 measurements (30.00%)
  2 (20.00%) low severe
  1 (10.00%) high severe

Benchmarking pipe_with_huge_lines: Warming up for 3.0000 s
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 40.5s.
pipe_with_huge_lines    time:   [696.91 ms 705.45 ms 711.90 ms]
                        thrpt:  [267.92 MiB/s 270.37 MiB/s 273.68 MiB/s]
                 change:
                        time:   [-2.5229% -0.3197% +1.7888%] (p = 0.78 > 0.05)
                        thrpt:  [-1.7574% +0.3208% +2.5882%]
                        No change in performance detected.

Benchmarking pipe_with_many_writers: Warming up for 3.0000 s
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 16.7s.
pipe_with_many_writers  time:   [302.42 ms 303.68 ms 304.96 ms]
                        thrpt:  [31.272 MiB/s 31.404 MiB/s 31.535 MiB/s]
                 change:
                        time:   [-0.3803% +0.7764% +1.9409%] (p = 0.24 > 0.05)
                        thrpt:  [-1.9040% -0.7704% +0.3818%]
                        No change in performance detected.

Benchmarking interconnected: Warming up for 3.0000 s
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 15.4s.
interconnected          time:   [275.49 ms 278.60 ms 281.94 ms]
                        thrpt:  [67.652 MiB/s 68.462 MiB/s 69.235 MiB/s]
                 change:
                        time:   [+21.873% +23.896% +26.087%] (p = 0.00 < 0.05)
                        thrpt:  [-20.690% -19.287% -17.947%]
                        Performance has regressed.
Found 2 outliers among 10 measurements (20.00%)
  1 (10.00%) low severe
  1 (10.00%) high severe

Benchmarking transforms: Warming up for 3.0000 s
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 22.4s.
transforms              time:   [395.25 ms 400.08 ms 404.63 ms]
                        thrpt:  [25.926 MiB/s 26.221 MiB/s 26.541 MiB/s]
                 change:
                        time:   [+0.5271% +2.0635% +3.7876%] (p = 0.03 < 0.05)
                        thrpt:  [-3.6494% -2.0218% -0.5243%]
                        Change within noise threshold.
```

Showing between 10-20% decrease in performance, though I would take this with a grain of salt since my machine is somewhat noisy right now. I think there is potential to make this more performant, and we may just want to thread it through the build step if we'd like to make this faster. I also think we usually hit rate limits before hitting our max so this decrease in performance is not the worst thing in the world.

Signed-off-by: Lucio Franco <luciofranco14@gmail.com>

### CODE REVIEW

**Comment by LucioFranco** [comment]
I'd like to also note that this + BTree within events + tokio 0.2 should still be faster than the current master.

**Comment by binarylogic** [comment]
I don’t have enough context, but I’m curious what @Hoverbear thinks.

**Comment by binarylogic** [comment]
Also, can we add a test verifying this behavior so we don’t regress?

**Comment by a-rodin** [comment]
The code looks great to me, although I agree with https://github.com/timberio/vector/pull/1860#issuecomment-588544299 that the tests would be helpful.

**Comment by LucioFranco** [comment]
Yeah, I am kinda leaning here that we just invest into the work to pass the schema down via our config builder traits.

**Comment by Hoverbear** [comment]
OK. 👍

**Comment by binarylogic** [comment]
Ok, closing this based on the discussion.

**Pull request closed without merging**
