### PR TITLE
enhancement(javascript): Add Fastclick support

### PR DESCRIPTION
**Pull request by lucperkins**
This PR adds [FastClick](https://github.com/ftlabs/fastclick) support to the website. The purpose of FastClick is to eliminate delays that arise in response to click events.

### CODE REVIEW

**Comment by zsherman** [comment]
Tested it, but I'm not sure it's actually working—I'm not seeing any prefetching actually happening in the browser.

**Comment by lucperkins** [comment]
@zsherman Have you tried on mobile? That appears to be the target of the lib:

> FastClick is a simple, easy-to-use library for eliminating the 300ms delay between a physical tap and the firing of a click event on mobile browsers

**Comment by zsherman** [comment]
Hmm ok, it's possible I was thinking of a different library which would prefetch the html on hover before loading the page...

**Comment by lucperkins** [comment]
Closing this for now, as this doesn't appear to be useful for the site. We can revisit at any point in the future.

**Pull request closed without merging**
