### PR TITLE
chore: Adding initial tracing RFC

### PR DESCRIPTION
**Pull request by jamtur01**
Draft RFC. Will be adding to this as we go.

[Rendered](https://github.com/timberio/vector/blob/tracing_rfc/rfcs/2020-09-22-4063-tracing_rfc_building_blocks.md)

### CODE REVIEW

**Comment by jamtur01** [comment]
@JeanMertz @lukesteensen @MOZGIII I have a skeleton in place and I'd welcome ideas on next steps.

**Review by lukesteensen — COMMENTED** [review]
This looks like a good start! The biggest question in my mind is how we represent traces in our data model. Our event model is quite flexible and can easily hold spans with a trace ID field. But I can also see how'd it be confusing not to differentiate between log events and trace events since not all logs are valid traces(?).

I like the simplicity of "just" adding sources and sinks for traces and treating them otherwise as simple events, but I don't want to set up users for failure if we allow them to mix and match logs and traces in ways we should tell them won't work.

**Comment by jamtur01** [comment]
@lukesteensen This has been one of my concerns too. I've looked at the log and metric's models and I could see we might add traces sort of side-loaded in but I think we want a first-class abstraction, independent of log events.

**Comment by binarylogic** [comment]
Thanks @lukesteensen. 

> but I don't want to set up users for failure if we allow them to mix and match logs and traces in ways we should tell them won't work.

This is why I like adding a strict tracing type. It guarnatees that data will be interopable between various tracing source and sinks. Event if the model is simple it establishes a strict contract.

**Comment by lukesteensen** [comment]
So that brings up the question of conversions. Will we have a `log_to_trace` transform? What would that look like? Should we allow transforms and sinks that accept logs to also accept traces? Not every log is a valid trace span but it does seem like every trace span could be a valid log.

**Comment by MOZGIII** [comment]
> OpenTelmetry supports traces, metrics, and potentially logs. Do we want to support all incoming? Does this mean three sources?

It depends on the implementation details.
- if the implementation can work more effectively if the sources are combined into one (i.e. it will use a single stream vs three streams) it makes sense to implement as a single source;
- if the ordering of the items that we get from the server matters - we should also go with a single source, to allow making sure the data of different is synchronized and doesn't interleave (unlikely it matters);
- otherwise, I'd assume separate sources are better - it's easier to combine data streams than split them in our topology configuration mechanism.

**Comment by jamtur01** [comment]
@bruceg I am putting this on your plate for the next sprint. I've made a very basic first cut but the data model piece needs someone closer to the code than me.

**Comment by binarylogic** [comment]
Closing this for now since we are tabling tracing support for the near-term. We can, and should, revive this RFC when we get to tracing.

**Comment by hdost** [comment]
@binarylogic Is this something that won't be there for 1.0 then?

**Comment by binarylogic** [comment]
@hdost it absolutely will. We still have work to do with logs and metrics and want to ship a complete product with those data types first. Tracing is still very much on our roadmap.

**Pull request closed without merging**
