### PR TITLE
chore: Added support for the ci-condition: skip label

### PR DESCRIPTION
**Pull request by jamtur01**
As GitHub Actions doesn't support skipping whole workflows and you can't set
job defaults we need to specify the skip on every job.

Signed-off-by: James Turnbull <james@lovedthanlost.net>

### CODE REVIEW

**Review by MOZGIII — APPROVED** [review]
This is great!

**Comment by binarylogic** [comment]
Sure. We have `ci-condition: *` tags. So maybe a `ci-condition: skip` tag?

**Comment by jamtur01** [comment]
@Hoverbear The big challenge with tags is the way GitHub Actions works with tags - it's not good at refreshing tags in Actions from what I can find. I'll take a poke at it and see what we can do and then do some more testing.

**Comment by Hoverbear** [comment]
@jamtur01 Ok. I'm fine with this as is, was just trying to save us some work later.

**Comment by jamtur01** [comment]
Okay - I've migrated this to using labels.

**Pull request merged**
