### PR TITLE
chore(dependencies): Configure dependabot to use correct issue names

### PR DESCRIPTION
**Pull request by Hoverbear**
This PR also reduces the number of times dependabot checks down to weekly.

### CODE REVIEW

**Comment by Hoverbear** [comment]
@binarylogic Bit of an issue here:

image

Checked at https://dependabot.com/docs/config-file/validator/

We'd need to use a shorter label prefix. :(

**Comment by binarylogic** [comment]
`chore(deps)` is fine. Can you update it in the `semantic.yml` file as well?

**Comment by Hoverbear** [comment]
Yup!

**Comment by Hoverbear** [comment]
@binarylogic I updated it, before I merge just wanted to make sure there isn't something else to be done -- I know they have hooks into GA etc.

**Pull request merged**
