### PR TITLE
chore: Add LogEvent::new

### PR DESCRIPTION
**Pull request by MOZGIII**
This is an internal life quality improvement, allows us to get rid of doing `Event::new_empty_log().into_log()`.

### CODE REVIEW

**Comment by a-rodin** [comment]
Could it make sense to also replace `Event::new_empty_log().into_log()` by `LogEvent::new()` throughout the codebase?

**Comment by MOZGIII** [comment]
Definitely! But let's do it in another PR, there might be non-trivial transformations required, and it'll slow down the adoption. While if we just merge this and convert the rest later - it'll be already usable in the new code.
Plus, the concurrent PRs can't use this yet, and this is another reason why it'd be good to delay codebase-wide change a bit.

**Comment by Hoverbear** [comment]
Would it not still be `Log(LogEvent::new())`? This PR would ideally migrate our existing code, or at least demonstrate usage once.

**Comment by MOZGIII** [comment]
`Event::new_empty_log().into_log()` => `LogEvent::new()`

`Event::new_empty_log()` is still there, and you can now additionally do `Event::Log(LogEvent::new())` if you want to...

**Comment by MOZGIII** [comment]
Converted some trivial code to use new notation to provide usage examples! :smile:

**Comment by MOZGIII** [comment]
```rust
$ cargo check
    Finished dev [unoptimized + debuginfo] target(s) in 0.32s
```
Hmm, apparently `cargo check` without args is not good for doing what I expect it'd do...

**Pull request merged**
