### PR TITLE
feat(kafka sink): Add support for TLS (SSL)

### LINKED ISSUE #838: Add SSL to kafka_sink
Other loggers allow you to ship logs to kafka utilizing SSL or Kerberos.  having this feature would allow customers to keep their data secure during transport.

https://www.elastic.co/guide/en/logstash/current/plugins-outputs-kafka.html#plugins-outputs-kafka-security_protocol

https://nxlog.co/documentation/nxlog-user-guide/om_kafka.html

https://docs.fluentd.org/v/0.12/output/kafka

### PR DESCRIPTION
**Pull request by bruceg**
Closes #838 

This has conflicts with the master branch, but I cannot rebuild the docs with current master, so merging will have to wait until that is fixed.

### CODE REVIEW

**Comment by bruceg** [comment]
The tests were working before I submitted this PR, but aren't now. I'm investigating what's going on.

**Comment by bruceg** [comment]
Ok, tests appear to all be passing except for the musl build. This should be ready for review (no actual code changes since I issued the PR FWIW)

**Comment by LucioFranco** [comment]
@a-rodin The current CI error relates to #915 and your pending change I believe.

**Comment by LucioFranco** [comment]
Ok this should now pass the musl build with the latest musl builder. I've just verified that this branch does indeed pass. I think this means we can merge this!

**Comment by binarylogic** [comment]
👍 docs look great. Glad we got this resolved.

**Pull request merged**
