### PR TITLE
chore(ci): Wait for ES to start up for Kinesis Firehose tests

### PR DESCRIPTION
**Pull request by jszwedko**
Opening as a draft to see what CI does with this as I'm having some issues reproducing locally.

### CODE REVIEW

**Comment by jszwedko** [comment]
Ci run: https://github.com/timberio/vector/actions/runs/322229802

**Comment by jszwedko** [comment]
Pushed another commit that:

* Switches to the `localstack-full` image that bundles in Elasticsearch rather than lazily loading it. Lazily loading it (during the test execution) seemed to take roughly 90s on my machine. I think the trade-off of the larger image is worth it and matches what we were doing before the localstack upgrade. This did seem to require a longer up-front loading period so I bumped the sleep from 5 -> 10s.
* Adds a check to the test to ensure that ES is healthy before running the rest of the test

**Comment by jszwedko** [comment]
New test run: https://github.com/timberio/vector/actions/runs/322636747

**Review by fanatid — APPROVED** [review]

**Comment by jszwedko** [comment]
One more run (post-refactor): https://github.com/timberio/vector/actions/runs/322802190

**Pull request merged**
