### PR TITLE
fix(css website): Code block formatting

### PR DESCRIPTION
**Pull request by DavidWeid**
## What does this PR do?
- Updates headers to not be `display: flex` so that nested blocks, such as `code` or `em`, have spacing around them
  - Positions svg anchor '#' absolute to maintain centering

- Updates `code` blocks that don't have `class="language-toml"`
  - Blocks have a background for better visibility and identification
  - Blocks that are links or within a link are colored as a link
  - Blocks that are not links are not colored as a link
  - Hovering a link that contains a block changes the color of the nested block similar to the link

## Pages to checkout in the preview:
Header with a nested italicized element:
- https://deploy-preview-8786--vector-project.netlify.app/docs/about/under-the-hood/architecture/data-model/#why-not-just-events

Header with a nested code block:
- https://deploy-preview-8786--vector-project.netlify.app/highlights/2021-07-14-0-15-upgrade-guide/#second

Page with lots of links, links with code blocks, code block links, and code blocks (4 cases)
- https://deploy-preview-8786--vector-project.netlify.app/docs/administration/monitoring/

Other code blocks that are in their own container should be unaffected (ex TOML, YAML, JSON code example boxes)
- https://deploy-preview-8786--vector-project.netlify.app/docs/reference/configuration/sources/docker_logs/#configuration

### Notes
Check pages in both `light` and `dark` theme

### CODE REVIEW

**Comment by spencergilbert** [comment]
This looks to have had some unexpected regressions:

Like this [alias section that is a diff](https://deploy-preview-8786--vector-project.netlify.app/docs/reference/configuration/sources/docker_logs/#alias) or generally the [config examples in yaml or json](https://deploy-preview-8786--vector-project.netlify.app/docs/reference/configuration/sources/docker_logs/#configuration)

**Comment by DavidWeid** [comment]
Thanks for the review! Looks like there's a pattern here that can be used

**Comment by lucperkins** [comment]
@spencergilbert @DavidWeid FYI the alias section is actually meant to be a diff, as you can see from the [production site](https://vector.dev/docs/reference/configuration/sources/docker_logs/#alias). Regardless of whether presenting it that way is *good idea*, it's not a regression :smile:

**Comment by lucperkins** [comment]
Heck yes! The inline code snippets are looking much better 😍

**Review by nsollecito — APPROVED** [review]

**Pull request merged**
