### PR TITLE
enhancement(aws_s3 sink): Increase rate limit

### LINKED ISSUE #2156: Raise default `aws_s3` `request.rate_limit_num` to 3500
We had a user bump into AWS s3 rate limits. Given [the AWS docs on S3 rates](https://docs.aws.amazon.com/AmazonS3/latest/dev/optimizing-performance.html), we should raise the `aws_s3` `request.rate_limit_num` to 3500:

> For example, your application can achieve at least 3,500 PUT/COPY/POST/DELETE or 5,500 GET/HEAD requests per second per prefix in a bucket. There are no limits to the number of prefixes in a bucket.

Ref https://github.com/timberio/vector/issues/1858

### PR DESCRIPTION
**Pull request by LucioFranco**
I've upped the rate limit to 3,500 which should match the lower bound of s3's rate limits. I've also bumped in_flight_limit to match since I suspect we will either hit one or the other.

cc @lukesteensen any thoughts on why we shouldn't raise the in_flight as well?

Closes #2156

Signed-off-by: Lucio Franco <luciofranco14@gmail.com>

### CODE REVIEW

**Comment by LucioFranco** [comment]
@lukesteensen are you saying we should bump the rate limit to 100 instead of 3.5k? I think reduce the in_flight makes sense maybe something like 50?

**Comment by lukesteensen** [comment]
> are you saying we should bump the rate limit to 100 instead of 3.5k? I think reduce the in_flight makes sense maybe something like 50?

Reducing in flight to 50 seems fine with me. I did mean rate limit to 100, but I'm not attached to that specific number. Going all the way to 3.5k just doesn't seem terribly useful, since it's extremely unlikely anyone will want to do that out of a single process and it won't actually match the AWS limit when added up over multiple processes. Maybe something like 250 or 500? That's still a ton of S3 requests for one process.

**Comment by LucioFranco** [comment]
@lukesteensen that seems fair but this seems so deployment oriented, I wonder if it just makes more sense to make evident that you can tune these knobs. Instead of providing a higher rate limit?

I'll bump it to the numbers you suggested.

**Comment by LucioFranco** [comment]
>  I think the goal here is to avoid being an unnecessary throttle on performance out of the box.

right, the issue is that this depends so much on how you deploy it, like do you have each agent ship to a different path in the bucket? How many parallel agents are shipping to the same spot etc. Might be good to have some sort of guide.

**Pull request merged**
