### PR TITLE
fix(datadog_agent source): Fix field naming for agent payloads

### PR DESCRIPTION
**Pull request by jszwedko**
https://github.com/DataDog/datadog-agent/blob/a33248c2bc125920a9577af1e16f12298875a4ad/pkg/logs/processor/json.go#L24-L32

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]
assuming it passes the previously failing tests :)

**Review by blt — CHANGES_REQUESTED** [review]
Hitting request changes to block the PR. With this change in place are we expecting that the datadog agent will send a JSON blob with `ddsource` and `ddtags` fields?

**Comment by jszwedko** [comment]
> Hitting request changes to block the PR. With this change in place are we expecting that the datadog agent will send a JSON blob with ddsource and ddtags fields?

@blt that is correct. See https://github.com/DataDog/datadog-agent/blob/a33248c2bc125920a9577af1e16f12298875a4ad/pkg/logs/processor/json.go#L24-L32 (note the `json` annotations)

**Review by blt — APPROVED** [review]
Rescinding my 'requests changes'. I don't read Go too well.

**Comment by jszwedko** [comment]
😄 it's definitely not super apparent. I do like Rust's annotations better.

**Comment by jszwedko** [comment]
Just noting that I'm keeping the field names the same rather then, for example, mapping to `source` internally to ensure they pass through correctly if this is subsequently sent to a `datadog_logs` sink.

**Comment by binarylogic** [comment]
Schemas!

**Pull request merged**
