### PR TITLE
chore(platforms): Migrate some PR checks to Github Actions from Circle

### PR DESCRIPTION
**Pull request by Hoverbear**
General larger scope notes for this work are here: https://www.notion.so/hoverbear/Vector-CI-Improvements-1e43b3bc1616429cad7fd5aa5d238828

This does a barebones, ultra-dirty hacky migration to Github Actions to unblock us.

### CODE REVIEW

**Comment by Hoverbear** [comment]
I'm headed to bed, if someone knows how to fix or improve this PR please feel free to just start committing. :) Otherwise I'll finish this up tomorrow/Saturday.

**Comment by Hoverbear** [comment]
Okay, this is dirty and needs a lot of cleaning and has a lot of improving to do, but I think this can pass and unblock us at least for now.

**Comment by binarylogic** [comment]
🥁

**Comment by Hoverbear** [comment]
Just wait for this to failcascade :)

**Comment by binarylogic** [comment]
@lukesteensen you just jinxed the whole thing. It hasn't fully passed yet.

**Comment by lukesteensen** [comment]
image

**Comment by binarylogic** [comment]
Given that the `check-component-features` check takes multiple hours we should disable it for the time being. We need to figure out a faster way to test this. I hope that we can improve compilation times with some form of caching (#1591) that will resolve this.

**Comment by Hoverbear** [comment]
@binarylogic I'd like to chunk out our test so we have a bunch of runners doing a feature each and they all share a "base vector build" cache to keep them fast, that'll require a bit of poking though.

**Comment by MOZGIII** [comment]
I like how this ended up. This is different from what was discussed and planned initially (a single super-big step with `make test` inside), but I feel like in the end doing it this way is a better trade-off. Pretty much we swap portability with clarity as we have a lot more configs yet a lot more distinct failure indicators (a lot of `jobs`). Nice work!

**Comment by Hoverbear** [comment]
I'm really excited to see if we can get this to generate via `make generate` or something to reduce the maintenance burden :)

**Pull request merged**
