### PR TITLE
enhancement(sinks): change compression to none by default

### LINKED ISSUE #2954: Change compression option by default to `none`
Compression in sinks should be disabled by default.

Currently `gzip` by default in 2 sinks:

- [ ] clickhouse
- [ ] aws s3

See https://github.com/timberio/vector/pull/2953#issuecomment-653902858

### PR DESCRIPTION
**Pull request by fanatid**
Simple, but breaking change.

Close #2954

### CODE REVIEW

**Comment by binarylogic** [comment]
@bruceg @lukesteensen, I'm curious if you think this change makes sense. Context on this change starts [here](https://github.com/timberio/vector/pull/2953#issuecomment-653897820).

**Comment by binarylogic** [comment]
@kirillt let's wait on merging this. I'd like to get consensus that this is worth a breaking change before doing so.

**Comment by bruceg** [comment]
I don't have a strong opinion on this one neither, except that it seems a pointless potentially breaking change (it might not actually break working configs) unless the current defaults are causing problems for people.

**Comment by binarylogic** [comment]
I agree. Let's close this and revisit it if we encounter problems.

**Pull request closed without merging**
