### PR TITLE
chore(testing): Discriminant nested events semantics

### LINKED ISSUE #1806: Add test to ensure discriminant works with the new Value::Map variant
With the addition of the `Value::Map` and `Value::Array` at #1662, the `hash` implementation used for `Value` in the `Discriminant` has two new cases.
While `Value::Array` is trivial as the ordering of the arrays is well-defined, and generally the arrays with different element order are considered different items, the `Value::Map`, brings up some questions.

Does the order of the fields in the map important for the purposes of discriminant comparison?
How at all should maps be compared for the purposes of the discriminant?
Would it be a good idea to compare maps by their content, or maybe we can conclude that no map is equal to each other and call it a day? Since we should be able to compare deeply nested fields - there might not be a need to compare bare map objects at all - only their subfields.
If the map fields are compared, do we consider maps equal if there is an exact match? If there’s no match?

Those questions have to be addressed, and the relevant tests have to be added to the code, for ensuring that the implementation works as expected.

Related to #1662

### PR DESCRIPTION
**Pull request by MOZGIII**
Test cases for nested events support at discriminant.

Relevant to #1662, see https://github.com/timberio/vector/pull/1662#discussion_r380306776
Closes #1806.
 
I list the commit messages to better explain the purpose and logic.

#### Add two new tests for discriminant: map_values_key_order and map_values_matter

These are designed to help with ensuring the nested fields are properly
supported.
The design is as follows:
- The `map_values_key_order` test checks that the discriminant for two
  values with different key order still produce the same discriminant;
  this will pass without nested fields support (i.e. on current master),
  but not because it correctly distinguishes the streams - but because the
  map values are not considered for comparison at all. For the purpose of
  the discriminant, events are the same because no fields contributed to
  the calculation. The invariant is still checked and passes. But to ensure
  the actual correctness, the second test - `map_values_matter` - is
  added.
- The `map_values_matter` test checks that nested fields do actually
  contribute to the discriminant calculation.

#### Add another case for the `map_values_matter` test

This ensures the Map values are not confused with other variants, and also
validates another edge case that has to be properly supported for proper
nested field implementation - that `Value::Map` values are not ignored.

- rename `map_values_matter` to `map_values_matter_1`
- add `map_values_matter_2`

### CODE REVIEW

**Comment by MOZGIII** [comment]
@binarylogic the tests currently fail as `master` doesn't support nested values (i.e. this is by design).
Please see this comment: https://github.com/timberio/vector/pull/1662#discussion_r380323299
I don't think merging this to `master` would be a good idea - we'll then have a broken `master`. I think the best way is to cherry-pick these to #1662.

**Comment by binarylogic** [comment]
Ah ok. Yeah, do whatever you think is best.

**Comment by MOZGIII** [comment]
@a-rodin could you take over this and pull this in it into your branch when you'll be working on nested events support at discriminant?

**Comment by MOZGIII** [comment]
Superseded by #1936

**Pull request closed without merging**
