### PR TITLE
chore(ci): Add back in package verification jobs

### PR DESCRIPTION
**Pull request by jamtur01**
Signed-off-by: James Turnbull <james@lovedthanlost.net>

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
Looks good!

There seems like quite a bit of duplication between the `nightly` and `release` workflows that could probably be eliminated, but that seems outside the scope of this PR.

**Comment by jamtur01** [comment]
I duplicated it because the artifacts created in the work flow are what we're testing. I wasn't sure how pulling the jobs out to a separate workflow would work in that context.

**Comment by jszwedko** [comment]
:+1: that's fine. We can refactor later. I am using https://github.com/dawidd6/action-download-artifact to pull artifacts from different workflow runs in the benchmark workflow.

**Comment by jamtur01** [comment]
Oh interesting. I didn't know about that one. I'll take a look. Thanks!

**Pull request merged**
