### PR TITLE
chore(deps): Upgrade async-graphql

### PR DESCRIPTION
**Pull request by jszwedko**
It was pinned in https://github.com/timberio/vector/pull/6217 because it
was believed it required Tokio 1.0 but I'm not actually seeing this.

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Comment by jszwedko** [comment]
Unfortunately this didn't actually help with https://github.com/timberio/vector/issues/6584 like I thought it would.

**Comment by jszwedko** [comment]
Bump @leebenson

**Comment by leebenson** [comment]
I thought this was blocked on #6383, but I could be wrong. There was an issue with context in #6610 that required an interim downgrade, which is how I spotted the warp incompatibility originally. In any case, I'll test this with #6610.

**Comment by jszwedko** [comment]
@leebenson you're right 😅 I'm not sure how I got confused here but this definitely requires Warp 0.3 which requires Tokio 1.0.

**Pull request closed without merging**
