### PR TITLE
chore(ci): Add self-hosted Windows runner

### PR DESCRIPTION
**Pull request by jamtur01**
Adds a standalone Windows runner to get the Windows CI tests running again.

Signed-off-by: James Turnbull <james@lovedthanlost.net>

### CODE REVIEW

**Comment by binarylogic** [comment]
Impressed

**Comment by jszwedko** [comment]
Wow, look at that. Builds in 15 minutes even! Thank you!

I'd love to get some docs around managing the self-hosted runner if we are going to continue to manage it manually.

**Comment by jamtur01** [comment]
@jszwedko The docs are "Ummm. WTF? Let me run this weird PowerShell script..." but yes that's on my list for today.

**Comment by jszwedko** [comment]
:smile: thank you!

**Pull request merged**
