### PR TITLE
chore(external docs): Remove .meta folder

### PR DESCRIPTION
**Pull request by binarylogic**
The `.meta` files have been moved to the `vector-website` repo as a temporary holdover (https://github.com/timberio/vector-website/pull/130) until we can complete the new `docs/**/*.cue` files. This will prevent confusion as to which files to update. Everything in the `vector` repo should focus on the `docs/**/*.cue` from here on out.

### CODE REVIEW

**Comment by binarylogic** [comment]
@jamtur01 it seems like the failure here is unrelated? `make check-markdown` fails on `master` as well for me.

**Comment by jamtur01** [comment]
It's unrelated. I'll fix that right now. It looks like a path changed when we moved this job to a container.

**Comment by fanatid** [comment]
Unfortunately, this PR not completely remove `.meta` folder. https://github.com/timberio/vector/pull/3552 introduced file `.meta/transforms/metric_to_log.toml.erb`.

**Comment by binarylogic** [comment]
Will fix!

**Pull request merged**
