### PR TITLE
fix(enriching): Usable in Test

### PR DESCRIPTION
**Pull request by dbcfd**
Makes enrichment tables usable in test.

### CODE REVIEW

**Comment by dbcfd** [comment]
@StephenWakely fixes issue mentioned in https://github.com/timberio/vector/issues/8815

**Review by StephenWakely — CHANGES_REQUESTED** [review]
This is awesome. Thanks for submitting this.

Codewise, this is perfect. I really like how extracting out the loading of the enrichment tables into a separate function makes the code much cleaner than it was.

There's just a couple of minor changes needed to get CI to go green and we should be good to merge.

1.  Move the parens in the PR title around so it says: `fix(enriching): Usable In test`.
2. Run `src/config/unit_test.rs` through rustfmt.

Thanks once again! It's really exciting seeing this work get into peoples hands.

**Comment by dbcfd** [comment]
@StephenWakely This should be good to go.

**Review by StephenWakely — APPROVED** [review]
Much appreciated. Thankyou!

**Pull request merged**
