### PR TITLE
fix(deps): Upgrade reqwest in k8s-e2e-tests

### PR DESCRIPTION
**Pull request by jszwedko**
To use Tokio 1.0

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Comment by jszwedko** [comment]
I kicked off an integration test build here: https://github.com/timberio/vector/actions/runs/712155959

**Review by lukesteensen — APPROVED** [review]

**Comment by jszwedko** [comment]
k8s tests: https://github.com/timberio/vector/actions/runs/712229067

**Comment by jszwedko** [comment]
The integration kafka tests failed, but they pass locally for me. I do see them failing on master too though: https://github.com/timberio/vector/runs/2254956119

**Comment by jszwedko** [comment]
Well the k8s tests pass here now at least. I'm still looking into the Kafka failure, but I'll open a separate PR for that.

**Pull request merged**
