### PR TITLE
chore(ci): Fix make check-examples CI check

### LINKED ISSUE #4755: `make check-examples` is broken
```
cargo run -- validate --topology --deny-warnings ./config/examples/*.toml
    Finished dev [unoptimized + debuginfo] target(s) in 0.44s
     Running `target/debug/vector validate --topology --deny-warnings ./config/examples/docs_example.toml ./config/examples/environment_variables.toml ./config/examples/es_s3_hybrid.toml ./config/examples/file_to_cloudwatch_metrics.toml ./config/examples/file_to_prometheus.toml ./config/examples/prometheus_to_console.toml ./config/examples/stdio.toml ./config/examples/wrapped_json.toml`
error: Found argument '--topology' which wasn't expected, or isn't valid in this context

USAGE:
    vector validate [FLAGS] [paths]...

For more information try --help
make: *** [check-examples] Error 1
```

cc/ @JeanMertz

### PR DESCRIPTION
**Pull request by jamtur01**
Signed-off-by: James Turnbull <james@lovedthanlost.net>

Closes #4755.

### CODE REVIEW

**Comment by binarylogic** [comment]
Why did this suddenly break? Or was it always broken?

**Comment by jamtur01** [comment]
Always broken from what I can git blame - at least since we moved to Github Actions.

**Comment by binarylogic** [comment]
@jamtur01 does this actually fix the issue or just remove the check? Should we, instead, fix the configuration examples that are incomplete?

**Comment by jamtur01** [comment]
@binarylogic This fixes the check but not the examples. I am waiting for @JeanMertz to be back to discuss the examples themselves.

**Pull request closed without merging**
