### PR TITLE
feat(remap transform): Add new remap functions

### LINKED ISSUE #3737: New `merge` remap function
The `merge` remap function would merge 2 objects together.

## Examples

For all examples we'll use this event:

```js
{
  // ...
  "parent1": {
    "key1": "val1",
    "child": {
      "grandchild1": "val1"
    }
  },
  "parent2": {
    "key2", "val2",
    "child": {
      "grandchild2": "val2"
    }
  }
  // ...
}
```

### Shallow merge

```
merge(.parent1, .parent2)
del(.parent2)
```

Results in:

```js
{
  // ...
  "parent1": {
    "key1": "val1",
    "key2", "val2",
    "child": {
      "grandchild2": "val2"
    }
  }
  // ...
}
```

### Deep merge

```
merge(.parent1, .parent2, deep=true)
del(.parent2)
```

Results in:

```js
{
  // ...
  "parent1": {
    "key1": "val1",
    "key2", "val2",
    "child": {
      "grandchild1": "val1"
      "grandchild2": "val2"
    }
  }
  // ...
}
```

### Root

For clarity, users can merge with the root object with the `.` path:

```
merge(., .parent2)
del(.parent2)
```

### LINKED ISSUE #3738: New `parse_json` remap function
We need a remap function that makes it easy to parse JSON within a field's value. Combining this function with other instructions will allow users to assign the result to a field, merge it with an existing field, and more.

## Examples

For all examples we'll use this event:

```js
{
  // ...
  "message": "{\"key\": \"val\"}",
  "attributes": {
    "existing": "value"
  }
  // ...
}
```

### Assignment

It should be possible to parse the `message` key and assign it to another key:

```
.attributes = parse_json(.message)
```

This would result in:

```js
{
  // ...
  "message": "{\"key\": \"val\"}",
  "attributes": {
    "key": "val"
  },
  // ...
}
```

Notice that we replaced the `"attributes"` key entirely.

### Merging

It should be possible to parse the `message` key and combine it with the `merge` function (#3737):

```
merge(.attributes, parse_json(.message))
```

This would result in:

```js
{
  // ...
  "message": "{\"key\": \"val\"}",
  "attributes": {
    "existing": "value",
    "key": "val"
  },
  // ...
}
```

### LINKED ISSUE #3745: New `split` remap function
The `split` remap function splits a string with the provided pattern

## Example

Given this event for all examples:

```js
{
  "message": "This is a long string"
}
```

### Default

By default, the `split` function splits on all occurences of the passed pattern:

```
.message = split(.message, / /)
```

Would result in:

```js
{
  "message": ["This", "is", "a", "long", "string"]
}
```

### Limit

Users can optionally supply a limit, to limit the number of items:

```
.message = split(.message, / /, 2)
```

Would result in:

```js
{
  "message": ["This", "is a long string"]
}
```

### LINKED ISSUE #3746: New `strip_whitespace` remap function
The `strip_whitespace` remap function strips leading and trailing whitespace

## Example

Given this event:

```js
{
  "message": "\t\tThis string has whitespace around it    "
}
```

And this remap instruction set:

```
.message = strip_whitespace(.message)
```

Would result in:

```js
{
  "message": "This string has whitespace around it"
}
```

## Requirements

- [ ] Strips leading _and_ trailing whitespace.
- [ ] Splits on all whitespace as defined by [Unicode whitespace character](https://en.wikipedia.org/wiki/Unicode_character_property#Whitespace).

### LINKED ISSUE #3750: New `replace` remap function
The `replace` remap function replaces all occurrences of a string.

## Examples

Given the following event:

```js
{
  "message": "I like apples and bananas"
}
```

### String literal

And the following remap instruction set:

```
.message = replace(.message, "a", "o")
```

Would produce:

```js
{
  "message": "I like opples and bononos"
}
```

### Regex

And the following remap instruction set:

```
.message = replace(.message, /a/, "o")
```

Would produce:

```js
{
  "message": "I like opples and bononos"
}
```

### LINKED ISSUE #3751: New `truncate` remap function
The `truncate` function truncates a string to the provided length.

## Example

Given the following event:

```js
{
  "message": "Supercalifragilisticexpialidocious"
}
```

### Default

And the following remap instruction set:

```
.message = truncate(.message, 5)
```

Would result in:

```js
{
  "message": "Super"
}
```

### Ellipsis

And the following remap instruction set:

```
.message = truncate(.message, 5, true)
```

Would result in:

```js
{
  "message": "Super..."
}
```

Or, if the limit exceeds the length of the string, then no `...` is added:

```
.message = truncate(.message, 9999999, true)
```

Would result in:

```js
{
  "message": "Supercalifragilisticexpialidocious"
}
```

### LINKED ISSUE #3752: New `flatten` remap function
The `flatten` remap function flattens an array into a single-depth array.

### Arrays

Given the following event:

```js
{
  "array": [1 [2, [3, 4, 5]], 6]
}
```

And the following remap instruction set:

```
.array = flatten(.array)
```

Would produce:

```js
{
  "array": [1 2, 3, 4, 5, 6]
}
```

### Objects

Given the following event:

```js
{
  "object": {
    "parent": {
      "child1": 1,
      "child2", 2,
    },
    "key": "val"
  }
}
```

And the following remap instruction set:

```
.object = flatten(.object)
```

Would produce:

```js
{
  "object": {
    "parent.child1": 1
    "parent.child2": 2,
    "key": "val"
  }
}
```

### PR DESCRIPTION
**Pull request by FungusHumungus**
- [x] Add `strip_whitespace` remap function. Closes #3746
- [x] Add `truncate` remap function. Closes #3751 
- [x] Add `parse_json` remap function. Closes #3738 
- [x] Add `merge` remap function. Closes #3737 
- [ ] Add `flatten` remap function. Closes #3752 
- [ ] Add `replace` remap function. Closes #3750 
- [ ] Add `split` remap function. Closes #3745

### CODE REVIEW

**Comment by FungusHumungus** [comment]
Note, this function will return the parameter untouched if it doesn't resolve to a String. Is that the thing to do, or would it be better to error?

**Comment by JeanMertz** [comment]
> Note, this function will return the parameter untouched if it doesn't resolve to a String. Is that the thing to do, or would it be better to error?

I've swapped the functions I worked on in https://github.com/timberio/vector/pull/3767 to explicitly error. This was described as a requirement for one of the functions. I think it makes sense to do the same here as well.

cc @binarylogic

**Comment by FungusHumungus** [comment]
I have added the truncate function into this pull request. It probably makes more sense than a separate pull request per function.

I have updated the functions to error if they don't recieve a valid unicode string.

The truncate function has raised another question. For this function, I have made it so that the limit parameter can be `query_arithmetic`. This means this value doesn't need to be hardcoded, it can be calculated from other fields. The ellipsis parameter currently has to be a boolean, either `true` or `false` and cannot be calculated - inline with how the other functions (`to_string` et al..) currently work.

I'm not 100% sure of what the best approach is here? We should probably be consistent for every function and parameters. I prefer the first approach for all parameters as it allows for greater flexibility, but not completely sure what the spec is.

**Comment by JeanMertz** [comment]
> I'm not 100% sure of what the best approach is here?

My preference (and what I've done so far) is to always accept `query_arithmetic` if possible.

I feel like we can improve that at some point to either accept a `path`, or one or more concrete types, but not every type. That way, the function can already error on startup if a function accepts either a path or a string, but is given an integer.

We'd still need runtime checks for when a path returns a non-string value, of course, but it would reduce the runtime failure conditions.

Until then though, I think accepting `query_arithmetic` as much as possible where it makes sense, is the way to go.

**Comment by JeanMertz** [comment]
@FungusHumungus would you be ok changing the base branch to https://github.com/timberio/vector/pull/3767, and merge it into that PR once you're done here? It seems like we're doing some duplicative work, especially in the pest file.

I also opted to no longer add new functions to that PR, I think it would be good to do the same thing here, so that we can iterate independently of each other going forward without creating too many merge conflicts.

**Comment by FungusHumungus** [comment]
@JeanMertz Ok, I have changed the base branch and have a load of conflicts, I can sort those out in a little bit. 

I'm a little unsure about how to merge it into that PR. Is that just a case of hitting the "Squash and merge" below?

**Comment by JeanMertz** [comment]
> I'm a little unsure about how to merge it into that PR. Is that just a case of hitting the "Squash and merge" below?

Yep, that'll work 👍

**Comment by FungusHumungus** [comment]
@JeanMertz Ok, I have rebased onto your PR and fixed the conflicts. Would now be a good time to squash it into yours? I'm a bit wary of trashing your PR if something goes wrong!

**Comment by JeanMertz** [comment]
Don't worry @FungusHumungus, you can just merge it into my branch without issues.

**Comment by FungusHumungus** [comment]
Ok, it is done.

For the rest of the functions I am working on, do you know where I should be pushing them to? Shall I create a new pull request or carry on pushing them here?

**Comment by JeanMertz** [comment]
Best to create a new branch. My PR has been approved as well, so I'll merge it soon, so we can create individual PRs with master as their base branch.

The next PR that will cause merge conflicts will probably be https://github.com/timberio/vector/pull/3927, but we'll deal with that once that PR is in a good enough state.

**Pull request merged**
