### PR TITLE
fix(observability): Regularize internal event messages

### LINKED ISSUE #3546: Regularize the internal event messages
The messages in `src/internal_events` do not all follow the pattern set out in https://github.com/timberio/vector/blob/master/rfcs/2020-03-17-2064-event-driven-observability.md

I added a script in [the regularize-internal-event-messages branch](https://github.com/timberio/vector/tree/regularize-internal-event-messages) that may be useful for identifying which messages need fixing and may be added to the CI pipeline after they are all fixed.

### PR DESCRIPTION
**Pull request by ktff**
Closes  #3546

Regularizes messages to adhere to uppercase and dot format, and runs the script, that @bruceg created, that checks for these rules, during CI `Checks` job.

### CODE REVIEW

**Comment by binarylogic** [comment]
Thanks. How does this close the linked issue?

**Comment by ktff** [comment]
@binarylogic somehow I linked wrong issue, changed to #3546.

**Review by JeanMertz — APPROVED** [review]
nice!

**Review by Hoverbear — APPROVED** [review]

**Review by jamtur01 — APPROVED** [review]
LGTM.

**Pull request merged**
