### PR TITLE
chore(ci): Run all benchmark suites in CI

### PR DESCRIPTION
**Pull request by jszwedko**
We previously couldn't run the wasm one because building it caused
memory pressure issues, but I'm hoping this won't be the case on the
self-hosted runners. We will see with this PR :)

The remap ones were left out when they were added. I think I may reorganize the suite some more soon.

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Review by Hoverbear — APPROVED** [review]

**Review by bruceg — APPROVED** [review]

**Review by jamtur01 — APPROVED** [review]
LGTM

**Comment by jszwedko** [comment]
Noting that I discovered that including the wasm benches (which rebuild the wasm outputs) cause `cargo bench` to rebuild. I'd like to resolve this before merging as it adds another 30 minutes to CI time.

**Comment by jszwedko** [comment]
@bruceg do you mind taking a look at a commit I pushed: https://github.com/timberio/vector/pull/5892/commits/4b5ccc909d64158e0bd3e3c9d65712a7e9d71430 ?

The issue I was trying to resolve is that rebuilding the wasm modules (which happens as part of `make bench-all`) seems to invalidate some sort of cache that causes `make bench-all` to recompile even though it was previously built with `--no-run`. This commit seems to fix the issue by having the wasm modules just build in their own `target/` directories, but I'm curious if this would be considered best practice or if there is another way I could approach this issue.

**Comment by Hoverbear** [comment]
@jszwedko You might need to add some things to `.gitignore` for this? The sub-`target` folders?

**Comment by jszwedko** [comment]
> @jszwedko You might need to add some things to `.gitignore` for this? The sub-`target` folders?

I discovered it was actually already in there :smile:

https://github.com/timberio/vector/blob/15d3db09bc94f154a7dffefdb31e6c640a9a51a1/.gitignore#L15

**Comment by bruceg** [comment]
> I'm curious if this would be considered best practice or if there is another way I could approach this issue.

I don't know what else to suggest. `cargo` is pretty opaque about why it chooses to rebuild or not.

**Comment by jszwedko** [comment]
> > I'm curious if this would be considered best practice or if there is another way I could approach this issue.
> 
> I don't know what else to suggest. `cargo` is pretty opaque about why it chooses to rebuild or not.

:+1: I just wanted to make sure I wasn't missing anything. I'll merge this approach then.

**Comment by jszwedko** [comment]
Failing CI check is fixed on master.

**Pull request merged**
