### PR TITLE
enhancement(http sink): Add all HTTP methods

### PR DESCRIPTION
**Pull request by yurihq**
Signed-off-by: Georgy Chirkov <yo@yo.qa>

Added all HTTP methods for http sink.

### CODE REVIEW

**Comment by binarylogic** [comment]
Thanks, @yura-415, could you provide context on why you need this change? Typically sink-level requests in Vector would be "change" requests (POST/PUT).

**Comment by yura-415** [comment]
Our particular use-case included sending DELETE requests to proprietary Elastic App Search Document API.

Generally any REST API would include DELETE routes for removal operations.

PATCH in this context too seems useful.

Other methods such as OPTIONS, TRACE could also be used in some rare cases.

In my opinion limiting standard HTTP method vocabulary seems unnecessary.

**Review by bruceg — APPROVED** [review]
The only one of these that really makes sense to add is for PATCH. However, technically, any of these may include data, though it's against the spec for this data to have meaning. If this provides compatibility with some oddly designed proprietary endpoint, I guess it has some value.

**Review by pablosichert — APPROVED** [review]
I've seen enough APIs with either very unconventional use or misuse of HTTP verbs to warrant this change.

Just hoping this isn't abused so that the vector instance is one of _those_ APIs 😄

**Comment by jszwedko** [comment]
Thanks again for this @yurihq !

**Pull request merged**
