### PR TITLE
chore: Resolve `--no-default-features --features api` build failure

### LINKED ISSUE #7222: Check build fails with flags `--no-default-features --features api`
While working on #7200 I ran `cargo hack check --feature-powerset --clean-per-run` and found that the build string in the issue title causes a build failure. 

```
error[E0432]: unresolved import `crate::sources::host_metrics`
 --> src/api/schema/metrics/host.rs:3:21
  |
3 | use crate::sources::host_metrics::HostMetricsConfig;
  |                     ^^^^^^^^^^^^ could not find `host_metrics` in `sources`

error[E0432]: unresolved import `uuid`
  --> src/api/tap.rs:16:5
   |
16 | use uuid::Uuid;
   |     ^^^^ use of undeclared crate or module `uuid`

error[E0433]: failed to resolve: could not find `host_metrics` in `sources`
   --> src/api/schema/metrics/host.rs:265:23
    |
265 |         Self(sources::host_metrics::HostMetricsConfig::default())
    |                       ^^^^^^^^^^^^ could not find `host_metrics` in `sources`

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `vector`

To learn more, run the command again with --verbose.
```

### PR DESCRIPTION
**Pull request by blt**
This commit resolves #7222 by looping in the features required by `api` to
compile correctly. I am open to the notion that we may want to do this in the
other direction, not exposing any information about host metrics in our API
unless `sources-host_metrics` is flagged on.

Signed-off-by: Brian L. Troutwine <brian@troutwine.us>

### CODE REVIEW

**Comment by jszwedko** [comment]
> I am open to the notion that we may want to do this in the
> other direction, not exposing any information about host metrics in our API
> unless `sources-host_metrics` is flagged on.

I am also a fan of this.

**Review by pablosichert — COMMENTED** [review]
Second that. Would rather add config guards around the code that uses `sources-host_metrics` related imports in the API.

**Comment by blt** [comment]
@jszwedko @pablosichert heard. @leebenson you still game to take over #7222?

**Comment by leebenson** [comment]
Yup, leave it with me. I think toggling support per availability of the host_metrics source makes sense 👍🏻

**Comment by leebenson** [comment]
Reassigned #7222. Will close this and separately PR with the feature toggle.

**Comment by blt** [comment]
Much obliged @leebenson.

**Pull request closed without merging**
