### PR TITLE
chore(ci): Add S3 redirects for old artifact names

### PR DESCRIPTION
**Pull request by jszwedko**
This reverts commit 96e445fa190d3ec39b6a09dbb8104f5c828facce.

Reopening https://github.com/timberio/vector/pull/5988 since it wasn't
quite working yet I reverted it in
https://github.com/timberio/vector/pull/6038 .

Opening as draft until I can fix https://github.com/timberio/vector/runs/1684050334?check_suite_focus=true

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Comment by jszwedko** [comment]
Kicked off new nightly: https://github.com/timberio/vector/actions/runs/488901888

**Comment by jszwedko** [comment]
Once more: https://github.com/timberio/vector/actions/runs/489145316

**Comment by jszwedko** [comment]
This is working now :smile:

**Review by jamtur01 — APPROVED** [review]
Cool. :)

**Pull request merged**
