### PR TITLE
feat(journald source)!: Switch from libsystemd to piping journalctl

### PR DESCRIPTION
**Pull request by bruceg**
In some configurations, loading libsystemd at run time in order to access journald files is not possible even when the library is present. This reworks the journald source to use a pipe to journalctl for the data source.

Closes issue #1473

### CODE REVIEW

**Comment by binarylogic** [comment]
@a-rodin would you mind reviewing this? I think you're the best person given your involvement in the issue up to this point.

**Comment by a-rodin** [comment]
This looks great!

Two questions:

1. What would happen if `journalctl` process exists for some reason? Should it be restarted in that case?
2. Would it make sense to expose the name of `journalctl` executable as an advanced option? I see that the path of it can be set using `PATH`, but should we expose it in case if someone has a system where the name is different? Also, it might be an option to set read it from a special environment variable instead.

**Comment by bruceg** [comment]
1. If `journalctl` exits, it will likely be handled like an EOF. Yes, we should probably deal with exiting and restart `journalctl`.
2. Yes, it would make sense to expose the path. I'll add a config for that.

**Comment by bruceg** [comment]
I've added a `journalctl_path` option, so that part is done.

Restarting journalctl runs into a number of boundary conditions that are now all caught when the source is created but would have to be moved into the future. In particular, what to do if the executable doesn't exist or Vector doesn't have permission to execute it? It would be good to have a health check function for sources like sinks do (which could run `journalctl --list-boots` or whatever to verify), but that's a lot more work than this PR.

**Comment by a-rodin** [comment]
> In particular, what to do if the executable doesn't exist or Vector doesn't have permission to execute it?

I think it would be enough to print an error in this case. I guess the most frequent reason for `journalctl` to exit might be OOM in case of too strict `ulimit` settings, so just restarting might be fine.

> It would be good to have a health check function for sources like sinks do (which could run journalctl --list-boots or whatever to verify), but that's a lot more work than this PR.

That sounds interesting, we may need a separate issue for this. However, I'm somewhat concerned about having too many periodically running healthchecks, especially invoking new processes, as they create additional CPU load even when no data is flowing to Vector.

I was thinking about just triggering restart when it becomes impossible to read from the pipe because it is closed.

**Comment by bruceg** [comment]
> That sounds interesting, we may need a separate issue for this. However, I'm somewhat concerned about having too many periodically running healthchecks, especially invoking new processes, as they create additional CPU load even when no data is flowing to Vector.

I was thinking more of a one-time health check to run before the source starts to ensure appropriate conditions can be met to start the source. In this case, to verify `journalctl` can be executed.

> I was thinking about just triggering restart when it becomes impossible to read from the pipe because it is closed.

Right, the question is how to differentiate that from being unable to execute `journalctl` or some other issue that happens right at startup (permissions, corruption, etc). If we restart immediately on EOF, it can lead to heavy CPU use. A simple delay can solve this, but may lead to input delays.

**Pull request merged**
