### PR TITLE
chore(ci): Enable finer-grained constraints in running check jobs

### PR DESCRIPTION
**Pull request by jamtur01**
This PR uses constraints to skip steps in the linting job if the relevant files haven't changed.

Relates to #4295.

Signed-off-by: James Turnbull <james@lovedthanlost.net>

### CODE REVIEW

**Review by binarylogic — APPROVED** [review]

**Comment by jamtur01** [comment]
bors merge

**Comment by jamtur01** [comment]
bors merge

**Comment by jamtur01** [comment]
bors merge

**Comment by jamtur01** [comment]
bors merge

**Comment by jamtur01** [comment]
I am merging this manually because you can't run a new workflow added via staging when you want to run it in staging. bors all the way down.

**Pull request merged**
