### PR TITLE
chore(kafka sink): use signal instead timeout

### PR DESCRIPTION
**Pull request by fanatid**
Improvement of #4846, details: https://github.com/timberio/vector/pull/4846#discussion_r516955267

### CODE REVIEW

**Review by lukesteensen — COMMENTED** [review]
This looks good but I think it could be even simpler with [`tokio::sync::Notify`](https://docs.rs/tokio/0.2.23/tokio/sync/struct.Notify.html) instead of `tokio::sync::watch`.

**Comment by fanatid** [comment]
Changed, thanks for suggestion!

**Review by lukesteensen — APPROVED** [review]
Looks good to me!

**Comment by binarylogic** [comment]
Noting, it appears that this change was the cause of a significant performance decrease as reported by a Vector user. We have yet to verify this, but I wanted to bring it to your attention @fanatid. We will need to investigate this.

**Pull request merged**
