### PR TITLE
chore(setup): Add apt-get upgrade to Debian image to catch any newer packages

### PR DESCRIPTION
**Pull request by jamtur01**
Signed-off-by: James Turnbull <james@lovedthanlost.net>

### CODE REVIEW

**Comment by binarylogic** [comment]
Isn't this discouraged for users that want to build on top of this image? Was this causing problems before?

**Comment by jamtur01** [comment]
@binarylogic I've always done it? Is there some history here?

**Comment by binarylogic** [comment]
Yes, their recommendations are a little vague: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run. I think it's ok for packages we depend on, but it can be surprising if users are building on top of the Vector image.

> Avoid RUN apt-get upgrade and dist-upgrade, as many of the “essential” packages from the parent images cannot upgrade inside an unprivileged container. If a package contained in the parent image is out-of-date, contact its maintainers. If you know there is a particular package, foo, that needs to be updated, use apt-get install -y foo to update automatically.

**Comment by jamtur01** [comment]
@binarylogic I am a bit meh on that. I get dist-upgrade but apt upgrade, that feels like "this is a workaround for a docker problem".

**Comment by binarylogic** [comment]
Yeah, I'm curious what @Hoverbear thinks. I'm good either way.

**Review by Hoverbear — COMMENTED** [review]
This isn't harmful, and there isn't a problem with doing this that I could see which @jamtur01 and @binarylogic have not already mentioned. I think this is fine to merge, but I also don't really see a benefit here.

I do note this will probably inflate the image size, which many people find undesirable. Since it's preferable if people choose the glibc based debian image over the alpine, this is undesirable for us.

(Recall that many people are mistakenly under the impression that smaller image sizes are somehow better.)

Which all kind of begets the question: Why exactly are packaging with distros to begin with? We don't need to do this. Musl can be build from scratch and we can drop in the needed config file skeleton... Glibc needs a few more dylib deps (we can find them with `ldd`). I think the most we might need is a few other binaries like journald? Do the distroless images solve this already?

**Comment by jamtur01** [comment]
Closing this as it doesn't add to our existing solution. We'll address container scanning in other ways.

**Pull request closed without merging**
