### PR TITLE
fix(aws_kinesis_firehose sink): Fix `aws_kinesis_firehose` sink healthcheck

### PR DESCRIPTION
**Pull request by a-rodin**
The current healthcheck uses `list_delivery_streams` method with `exclusive_start_delivery_stream_name` parameter set to the name of the current stream. The response from AWS returns streams with names after the given stream name, so it leads to errors like 

```
 22 16:29:36.082 ERROR vector::topology::builder: Healthcheck: Failed Reason: Stream names do not match, got other-independent-stream, expected my-log-stream
```

The problem was reported [in the chat](https://gitter.im/timberio-vector/community?at=5e287be73b40ea043c82daaa).

This PR replaces the method used for healthcheck with `describe_delivery_stream`.

### CODE REVIEW

**Comment by binarylogic** [comment]
Is https://github.com/timberio/vector/issues/622 related?

**Comment by binarylogic** [comment]
Also, to add more context to health checks, we had a rather large discussion about this a while back. It prompted adding [this section](https://github.com/timberio/vector/blob/master/CONTRIBUTING.md#guidelines-for-writing-healthchecks) to our contributing guide. I'm wondering if we should reapproach health checks in general across our sinks. AKA add a project to our roadmap to readdress this.

**Comment by lukesteensen** [comment]
This does seem very similar to #622. Before we add a healthcheck project to the roadmap, we should spend a little time thinking about what we'd do with such a project. A lot of what we've found is that they're fundamentally quite limited, so I'm not sure what we'd do to improve the situation.

**Comment by a-rodin** [comment]
> Is #622 related?
> This does seem very similar to #622.

Should we port the same changes to `aws_kinesis` sink before the next release?

> Also, to add more context to health checks, we had a rather large discussion about this a while back. It prompted adding this section to our contributing guide. I'm wondering if we should reapproach health checks in general across our sinks. AKA add a project to our roadmap to readdress this.

It might be somewhat related to @bruceg's idea about also adding health checks for some sources: https://github.com/timberio/vector/pull/1526#issuecomment-575386309.

**Comment by lukesteensen** [comment]
> Should we port the same changes to `aws_kinesis` sink before the next release?

It probably doesn't need to block a release, but we should apply the same change there.

> It might be somewhat related to @bruceg's idea about also adding health checks for some sources: [#1526 (comment)](https://github.com/timberio/vector/pull/1526#issuecomment-575386309).

Yeah, that's an interesting idea. It would be nice to find a way to make them fully opt-in, so we don't need to change existing sources that don't need them.

**Pull request merged**
