### PR TITLE
chore: Remove sleep from simple_checkpoint

### LINKED ISSUE #8278: Remove sleep from simple_checkpoint e2e test
Now that #7898 is closed we should be able to remove/reduce the sleep in the e2e kubernetes tests to reduce testing time

### PR DESCRIPTION
**Pull request by spencergilbert**
Signed-off-by: Spencer Gilbert <spencer.gilbert@datadoghq.com>

Closes #8278

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
🚀 assuming the tests pass

**Comment by spencergilbert** [comment]
> 🚀 assuming the tests pass

I ran them a bunch locally - should be fine, though the minikube driver does seem to cause failures (podman and kvm fail much more often than docker)

**Review by StephenWakely — APPROVED** [review]
That sleep looks like a fudge to get the tests pass that could be hiding an issue in Vector. If the tests fail without it, we should look into fixing Vector.

**Comment by spencergilbert** [comment]
> That sleep looks like a fudge to get the tests pass that could be hiding an issue in Vector. If the tests fail without it, we should look into fixing Vector.

It was, if you check out the linked issue we weren't totally flushing checkpoints on shutdown. Should be solved now 👍

**Pull request merged**
