### PR TITLE
chore(remap): Improve the `Display` performance of `Kind`

### PR DESCRIPTION
**Pull request by blt**
According to the `coz` profiling done in https://github.com/timberio/vector/pull/6868#issuecomment-806040265 the `Display` implementation of `Kind` has an outsized impact on overall throughput, at least in the test setup. Micro-benchmarks have been introduced in this commit. Baseline: 

```
➜  compiler git:(blt-kind_quoted) ✗ cargo criterion kind
    Finished bench [optimized + debuginfo] target(s) in 0.14s
vrl_compiler::value::kind::display/"string"
                        time:   [98.154 ns 98.528 ns 98.918 ns]
                        change: [+1.2007% +1.8956% +2.5809%] (p = 0.00 < 0.05)
                        Performance has regressed.
vrl_compiler::value::kind::display/"array"
                        time:   [94.712 ns 94.971 ns 95.233 ns]
                        change: [-2.9792% -2.2242% -1.4878%] (p = 0.00 < 0.05)
                        Performance has improved.
vrl_compiler::value::kind::display/"regex"
                        time:   [94.924 ns 95.151 ns 95.373 ns]
                        change: [+0.2264% +0.9399% +1.6341%] (p = 0.01 < 0.05)
                        Change within noise threshold.
vrl_compiler::value::kind::display/"null"
                        time:   [97.718 ns 98.008 ns 98.320 ns]
                        change: [+0.9283% +1.6573% +2.3350%] (p = 0.00 < 0.05)
                        Change within noise threshold.
```

final commit

```
➜  compiler git:(blt-kind_quoted) ✗ cargo criterion kind
   Compiling vrl-compiler v0.1.0 (/home/blt/projects/com/datadog/vector/lib/vrl/compiler)
    Finished bench [optimized + debuginfo] target(s) in 15.24s
vrl_compiler::value::kind::display/"string"
                        time:   [44.235 ns 44.499 ns 44.782 ns]
                        change: [-12.217% -11.272% -10.344%] (p = 0.00 < 0.05)
                        Performance has improved.
vrl_compiler::value::kind::display/"array"
                        time:   [45.765 ns 46.129 ns 46.505 ns]
                        change: [-5.5479% -4.5953% -3.6834%] (p = 0.00 < 0.05)
                        Performance has improved.
vrl_compiler::value::kind::display/"regex"
                        time:   [45.769 ns 46.100 ns 46.457 ns]
                        change: [-11.310% -10.460% -9.5413%] (p = 0.00 < 0.05)
                        Performance has improved.
vrl_compiler::value::kind::display/"null"
                        time:   [45.919 ns 46.219 ns 46.519 ns]
                        change: [-10.718% -9.8956% -9.0978%] (p = 0.00 < 0.05)
                        Performance has improved.
```

Full-up release from master:

```
Performance counter stats for 'bash -c flog --format json --number 100000 | ./target/release/vector -qq --config vector-nohop.toml' (10 runs):

         11,123.80 msec task-clock                #    3.394 CPUs utilized            ( +-  2.13% )
           285,670      context-switches          #    0.026 M/sec                    ( +-  3.82% )
               373      cpu-migrations            #    0.034 K/sec                    ( +-  6.35% )
             9,036      page-faults               #    0.812 K/sec                    ( +-  0.42% )
    33,976,770,388      cycles                    #    3.054 GHz                      ( +-  1.78% )  (83.18%)
     1,401,074,998      stalled-cycles-frontend   #    4.12% frontend cycles idle     ( +-  4.65% )  (83.47%)
    15,583,691,225      stalled-cycles-backend    #   45.87% backend cycles idle      ( +-  2.23% )  (83.23%)
    40,733,133,240      instructions              #    1.20  insn per cycle
                                                  #    0.38  stalled cycles per insn  ( +-  0.60% )  (83.30%)
     7,682,658,252      branches                  #  690.651 M/sec                    ( +-  0.68% )  (83.30%)
        50,740,890      branch-misses             #    0.66% of all branches          ( +-  1.97% )  (83.52%)

            3.2771 +- 0.0469 seconds time elapsed  ( +-  1.43% )
```

Full-up results from this PR:

```
Performance counter stats for 'bash -c flog --format json --number 100000 | ./target/release/vector -qq --config vector-nohop.toml' (10 runs):

         11,016.83 msec task-clock                #    3.463 CPUs utilized            ( +-  1.03% )
           262,678      context-switches          #    0.024 M/sec                    ( +-  3.95% )
               406      cpu-migrations            #    0.037 K/sec                    ( +-  7.96% )
             8,949      page-faults               #    0.812 K/sec                    ( +-  0.37% )
    33,078,990,129      cycles                    #    3.003 GHz                      ( +-  1.85% )  (83.36%)
     1,350,443,611      stalled-cycles-frontend   #    4.08% frontend cycles idle     ( +-  5.02% )  (83.28%)
    15,194,401,728      stalled-cycles-backend    #   45.93% backend cycles idle      ( +-  2.51% )  (83.36%)
    40,703,130,455      instructions              #    1.23  insn per cycle
                                                  #    0.37  stalled cycles per insn  ( +-  0.62% )  (83.34%)
     7,667,870,489      branches                  #  696.014 M/sec                    ( +-  0.63% )  (83.39%)
        50,060,285      branch-misses             #    0.65% of all branches          ( +-  1.79% )  (83.27%)

            3.1815 +- 0.0289 seconds time elapsed  ( +-  0.91% )
```

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
Interesting! I would not have thought that this code path would be hit often. Do you know what paths in your experiment are hitting it?

I am wondering if there is any magic we can do to ensure the two string representations don't drift (I guess we could write a test at least). I'd also drop a comment in there as someone running across it is likely to wonder why we just didn't do `format!(r#""{}""#, self.as_str())`.

**Comment by blt** [comment]
@jszwedko good point about the comment. I'll add one. 

Regarding the path, couldn't tell you. `coz` just suggests lines that could profit overall throughput but there's no information about what paths were hit in the program that led to that conclusion.

**Comment by jszwedko** [comment]
> @jszwedko good point about the comment. I'll add one.
> 
> Regarding the path, couldn't tell you. `coz` just suggests lines that could profit overall throughput but there's no information about what paths were hit in the program that led to that conclusion.

👍 I just wasn't sure if you had a hunch or might be able to tell using a "traditional profiler". The reason I'm wondering is perhaps whatever it is might be able to avoid calling `quoted()` at all. I might have guessed we'd only see that called for debug or error output.

Interestingly, the observed speed up here of roughly 3% does not match coz's prediction of a 50% total speed-up based on the roughly 10% improvement to the line speed. It's first data point is at 25% line speed up though so my guess is the "line fitting" isn't reflective of reality for 10%. Or there is something else going on.

**Comment by blt** [comment]
> +1 I just wasn't sure if you had a hunch or might be able to tell using a "traditional profiler". The reason I'm wondering is perhaps whatever it is might be able to avoid calling quoted() at all. I might have guessed we'd only see that called for debug or error output.

No, I wish. It'd be fantastically useful if we could get that information, I do agree. I think the challenge with call graph analysis like that is it's just very, very expensive for large programs. 

> Interestingly, the observed speed up here of roughly 3% does not match coz's prediction of a 50% total speed-up based on the roughly 10% improvement to the line speed. It's first data point is at 25% line speed up though so my guess is the "line fitting" isn't reflective of reality for 10%. Or there is something else going on.

Indeed. I was disappointed by the all-up results, but them's the breaks. It's entirely possible that the path didn't trigger as much in subsequent runs or by optimizing this one hotspot we traded for another. I'd like to do a tear down of `coz` here soon. I wonder if we didn't have enough points available for this path to really draw a good conclusion.

**Comment by JeanMertz** [comment]
This is definitely interesting and curious.

@blt it would be good to have a chat sometime this week, so that I get a better understanding of what is actually being benchmarked in https://github.com/timberio/vector/pull/6868.

Some early notes:

- `Kind`'s string representation is/should (as @jszwedko pointed out) only used for debug purposes and generating compiler (or runtime, if opted into by the program) error messages.
- Compiler performance has never been a major priority for the project, given that it isn't a hot path (only runs once at boot). Instead, our time was spent on runtime performance (and everything else to get v1 out the door).
- Given this, I can see four things going on here:
   1. `kind.quoted()` (or any function this uses, such as `kind.to_string()`, etc) somehow leaked into a VRL runtime hot-path.
   2. We're somehow compiling the program more than once after Vector booted, which would be a severe problem.
   3. Running the benchmarks results in runtime type errors that trigger the error-path which heavily uses this function.
   4. The benchmarks are focussing on compiler performance, which might show localized performance issues that don't have a significant impact on actual usage.

If (1) is the case, then we should track that down. I would be shocked if (2) was true, but it's still worth making sure this isn't the case. I don't believe (3) or (4) are the case, but it's again worth keeping in mind.

It's also worth mentioning (since I know you've been dabbling with it lately) that the VRL CLI is a very unoptimized "hobby" project that I built in a couple of hours to make it easy to debug VRL programs, and was deemed useful enough to be shipped in 0.12 for others to use. It got _some_ love by others before we shipped it, but I would still consider it a "non-production" utility, especially when it comes to performance.

Re: getting better insights into what happens when. Another item that I never got around to due to time constraints, but that we still should do at some point, is adding more tracing/profiling to VRL itself. We've already got profiling possibilities in Vector through the `tracing` crate (among others), but nothing like that is currently available in VRL, while it would help us figure out if/when functions like these are called erroneously.

**Comment by JeanMertz** [comment]
I did a brief check on (1), but couldn't find any uses other than in error messages (but this might not have caught all possible uses):

```
% rg --no-heading --with-filename "kind\.quoted" lib/vrl/
lib/vrl/compiler/src/value/kind.rs:143:                    kinds.push(Kind::$kind.quoted())

% rg --no-heading --with-filename "kind\.to_string" lib/vrl/
lib/vrl/compiler/src/expression/function_call.rs:517:                        kind.to_string()

% rg --no-heading --with-filename "format!\(.*kind.*" lib/vrl/
lib/vrl/compiler/src/expression/predicate.rs:147:                Label::context(format!("instead it resolves to {}", kind), self.span),
lib/vrl/compiler/src/expression/not.rs:99:                    format!("this expression resolves to {}", kind),
lib/vrl/compiler/src/expression/function_call.rs:519:                        format!(r#"the exact type {}"#, kind)
lib/vrl/compiler/src/expression/function_call.rs:521:                        format!("one of {}", kind)
lib/vrl/compiler/src/expression/function_call.rs:527:                        format!("this expression resolves to {}", kind_str(got)),
lib/vrl/stdlib/src/float.rs:52:            v => Err(format!(r#"expected "float", got {}"#, v.kind()).into()),
lib/vrl/stdlib/src/timestamp.rs:52:            v => Err(format!(r#"expected "timestamp", got {}"#, v.kind()).into()),
lib/vrl/stdlib/src/to_int.rs:115:            v => Err(format!(r#"unable to coerce {} into "integer""#, v.kind()).into()),
lib/vrl/stdlib/src/to_float.rs:116:            v => Err(format!(r#"unable to coerce {} into "float""#, v.kind()).into()),
lib/vrl/stdlib/src/array.rs:52:            v => Err(format!(r#"expected "array", got {}"#, v.kind()).into()),
lib/vrl/stdlib/src/to_timestamp.rs:139:            v => return Err(format!(r#"unable to coerce {} into "timestamp""#, v.kind()).into()),
lib/vrl/stdlib/src/string.rs:52:            v => Err(format!(r#"expected "string", got {}"#, v.kind()).into()),
lib/vrl/stdlib/src/object.rs:52:            v => Err(format!(r#"expected "object", got {}"#, v.kind()).into()),
lib/vrl/stdlib/src/to_string.rs:104:            v => return Err(format!(r#"unable to coerce {} into "string""#, v.kind()).into()),
lib/vrl/stdlib/src/integer.rs:52:            v => Err(format!(r#"expected "integer", got {}"#, v.kind()).into()),
lib/vrl/stdlib/src/boolean.rs:52:            v => Err(format!(r#"expected "boolean", got {}"#, v.kind()).into()),
lib/vrl/stdlib/src/to_bool.rs:161:            v => Err(format!(r#"unable to coerce {} into "boolean""#, v.kind()).into()),
```

**Comment by blt** [comment]
> This is definitely interesting and curious.
> 
> @blt it would be good to have a chat sometime this week, so that I get a better understanding of what is actually being benchmarked in #6868.

For sure. I'll walk you through the details here so we have a common footing. 

The setup in #6868 leans very heavily on [coz](https://cacm.acm.org/magazines/2018/6/228044-coz/fulltext), a somewhat experimental profiler that collects information about the call graph, information from [perf](https://perf.wiki.kernel.org/index.php/Main_Page) and then does some statistical trickery to suggest which lines might be profitable optimized to improve total program performance. It's an interesting idea and could potentially be a profitable tool. One of the big issues with using more traditional performance tools like `perf` is that they'll tell us _what's_ hot but it's not clear if those things are actually in the critical path for the program. 

Speaking of critical path, we have to inform `coz` of what we consider critical. So https://github.com/timberio/vector/pull/6868/files#diff-c2ed445d74c832068cb0ff4ec4954447d4f13e851b5af2ca16f1cc1ca1f4efc4R63 and https://github.com/timberio/vector/pull/6868/files#diff-c2ed445d74c832068cb0ff4ec4954447d4f13e851b5af2ca16f1cc1ca1f4efc4R76 inform `coz` that any coth paths that begin and end with those two markers are responsible for the _throughput_ between those points and we'd like suggestions on what to optimize between. This point https://github.com/timberio/vector/pull/6868/files#diff-26c40348b46f3aaa346e4dfbb951db20429b4b8f187a367c68a40162f4bd8721R103 and https://github.com/timberio/vector/pull/6868/files#diff-2cb9210a92b271ac59a35deac79ad3501c3a16a90b847fa7eaa2de5825cfe22bR114 measure the throughput from an event being received on stdin and exiting the blackhole. This PR was motivated by the profile generated [here](https://github.com/timberio/vector/pull/6868#issuecomment-806040265) which does suggest more of a speedup is possible than we see in practice, as @jszwedko noted. It's possible `coz` didn't get enough data points to draw an accurate inference or the code path that experiment traveled down was exceptional. 

> Some early notes:
> 
>     * `Kind`'s string representation is/should (as @jszwedko pointed out) only used for debug purposes and generating compiler (or runtime, if opted into by the program) error messages.
> 
>     * Compiler performance has never been a major priority for the project, given that it isn't a hot path (only runs once at boot). Instead, our time was spent on runtime performance (and everything else to get v1 out the door).
> 
>     * Given this, I can see four things going on here:
>       
>       1. `kind.quoted()` (or any function this uses, such as `kind.to_string()`, etc) somehow leaked into a VRL runtime hot-path.
>       2. We're somehow compiling the program more than once after Vector booted, which would be a severe problem.
>       3. Running the benchmarks results in runtime type errors that trigger the error-path which heavily uses this function.
>       4. The benchmarks are focussing on compiler performance, which might show localized performance issues that don't have a significant impact on actual usage.
> 
> 
> If (1) is the case, then we should track that down. I would be shocked if (2) was true, but it's still worth making sure this isn't the case. I don't believe (3) or (4) are the case, but it's again worth keeping in mind.

Yep, given that this PR doesn't have that much of an effect on top-line performance I'd be willing to believe that 1 or 3 are the more likely options. 2 does not seem true from reading through the code. The experiments in this PR and in #6868 ought to be the same, so I tend to disbelieve 4. 

> It's also worth mentioning (since I know you've been dabbling with it lately) that the VRL CLI is a very unoptimized "hobby" project that I built in a couple of hours to make it easy to debug VRL programs, and was deemed useful enough to be shipped in 0.12 for others to use. It got _some_ love by others before we shipped it, but I would still consider it a "non-production" utility, especially when it comes to performance.

Yep, your points here above strike me comprehensive and I sort of quickly dropped fiddling with the CLI. The optimization possibilities that `coz` turned up here were all in the larlpop generated parser, well outside what appeared to be low-hanging fruit. 

> Re: getting better insights into what happens when. Another item that I never got around to due to time constraints, but that we still should do at some point, is adding more tracing/profiling to VRL itself. We've already got profiling possibilities in Vector through the `tracing` crate (among others), but nothing like that is currently available in VRL, while it would help us figure out if/when functions like these are called erroneously.

I'm game to talk this over if you want. I'm very pro this work, especially as we push for bigger VRL transforms in configs.

**Pull request merged**
