### PR TITLE
enhancement(internal_metrics source): Allow disabling of the host/pid keys

### PR DESCRIPTION
**Pull request by jszwedko**
Partially addresses: #8407

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Review by spencergilbert — APPROVED** [review]
Much fewer clippy complaints on this one 😄

**Comment by binarylogic** [comment]
Are these type of changes better served with the `remap` transform? My thought has always been to allow sources to emit rich data and employ `remap` to change it as you see fit. This will avoid mapping-style options in the source, which remap is designed to solve.

**Comment by jszwedko** [comment]
> Are these type of changes better served with the `remap` transform? My thought has always been to allow sources to emit rich data and employ `remap` to change it as you see fit. This will avoid mapping-style options in the source, which remap is designed to solve.

Yeah, you can use `remap` to drop the keys later, but we had user request that they be able to avoid adding them in the first place. The keys here are at least in-line with other sources we have, but I agree that we should come up with a better solution to this. I'm not sure that requiring a separate `remap` transform is the best option. We could also allow embedding VRL into `source` components or allow metadata -> field mappings to be specified in another manner.

**Comment by spencergilbert** [comment]
I similarly don't love the idea of forcing users to add `remap` to be able to configure source level options, it feels awkward to me to add a bunch of `del()` calls (either as an additional components or as part of a `source`  key)

**Comment by binarylogic** [comment]
Those are good points. It feels very duplicative in function, and I fear that we'll continue to add options for data manipulation when we have a full DSL for that. We've been down that road; using TOML to express data mapping is not a good time. I'd much rather discuss a source-level hooks concepts where users could perform their own custom mapping at the source-level using Remap.

**Comment by spencergilbert** [comment]
> Those are good points. It feels very duplicative in function, and I fear that we'll continue to add options for data manipulation when we have a full DSL for that. We've been down that road; using TOML to express data mapping is not a good time. I'd much rather discuss a source-level hooks concepts where users could perform their own custom mapping at the source-level using Remap.

It'd definitely be interesting to explore how we could "configure" sources and sinks with remap

**Comment by jszwedko** [comment]
Yeah, agreed. Apologies, I'd marked this for automerge though there was still discussion going on. I do think we should come up with a better solution to opting in and out of metadata at the source level, but this PR just uses the existing patterns we have for this so I think it shouldn't be blocked by that. I'm happy to hear other opinions though. I can revert this if needed.

**Comment by spencergilbert** [comment]
> Yeah, agreed. Apologies, I'd marked this for automerge though there was still discussion going on. I do think we should come up with a better solution to opting in and out of metadata at the source level, but this PR just uses the existing patterns we have for this so I think it shouldn't be blocked by that. I'm happy to hear other opinions though. I can revert this if needed.

FWIW, I didn't think it was worth blocking - I think there's a large body of work deciding on and defining a path forward in the grand scheme of things.

**Pull request merged**
