### PR TITLE
chore(dependencies): Finish `hyper` upgrade

### LINKED ISSUE #2117: Upgrade `hyper` for `futures` 0.3
As part of the https://github.com/timberio/vector/issues/1142, upgrade `hyper` to `v0.13`+.

---

Here's a list of dependencies that are themselves blocked on `tokio` 0.1:
- `goauth` - https://github.com/durch/rust-goauth/issues/8
- `shiplift` - https://github.com/softprops/shiplift/issues/185
- `./vector/lib/tracing-metrics` - we'll take care of it

Crates that are ready for the upgrade:
- `hyper`
- `hyper-tls`
- `hyper-openssl`
- `reqwest`
- `rusoto_*`
- `kube`
- `hyperlocal`
- `warp`

Overall, not that bad.

### PR DESCRIPTION
**Pull request by ktff**
Closes #2117 

Contains: 
* Remove `hyper` and `hyper-openssl`
* Rename `hyper-openssl08` to `hyper-openssl`
* Rename `hyper13` to `hyper`

### CODE REVIEW

**Comment by ktff** [comment]
@lukesteensen @bruceg this PR only renames two dependencies in your files so I'll remove the request for the review.

**Comment by fanatid** [comment]
Great! Do we still need `body_to_bytes`?

**Comment by ktff** [comment]
Good question. Unfortunately yes, `hyper 0.13` is using `bytes 0.5.4` while we are still mostly on `0.4.10`

**Comment by lukesteensen** [comment]
Great work @ktff (and assists from @fanatid)! Very happy to see such good progress here.

**Pull request merged**
