### PR TITLE
fix: pip3 installed binaries

### PR DESCRIPTION
**Pull request by fanatid**
Ref. https://github.com/timberio/vector/pull/3268#issuecomment-667053779

### CODE REVIEW

**Comment by binarylogic** [comment]
@Hoverbear is this the correct way to fix this? Shouldn't remarshal already be in the path?

**Comment by fanatid** [comment]
I still not sure that this is correct. Before merge CI should be green.
Log:
```
2020-07-31T09:45:09.9322796Z pip3 install jsonschema==3.2.0
2020-07-31T09:45:12.0062455Z Requirement already satisfied: jsonschema==3.2.0 in /usr/lib/python3/dist-packages (3.2.0)
2020-07-31T09:45:13.0126398Z pip3 install remarshal==0.11.2
2020-07-31T09:45:16.2636935Z Collecting remarshal==0.11.2
2020-07-31T09:45:16.3056209Z   Downloading remarshal-0.11.2-py3-none-any.whl (5.9 kB)
2020-07-31T09:45:17.3040031Z Requirement already satisfied: PyYAML>=5.1 in /usr/lib/python3/dist-packages (from remarshal==0.11.2) (5.3.1)
2020-07-31T09:45:17.3526431Z Collecting u-msgpack-python>=2.5.1
2020-07-31T09:45:17.3606877Z   Downloading u_msgpack_python-2.6.0-py2.py3-none-any.whl (9.8 kB)
2020-07-31T09:45:17.4367881Z Collecting pytoml>=0.1.11
2020-07-31T09:45:17.4453177Z   Downloading pytoml-0.1.21-py2.py3-none-any.whl (8.5 kB)
2020-07-31T09:45:17.5330511Z Collecting python-dateutil>=2.5.0
2020-07-31T09:45:17.5414428Z   Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
2020-07-31T09:45:17.6023852Z Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.5.0->remarshal==0.11.2) (1.14.0)
2020-07-31T09:45:17.7116869Z Installing collected packages: u-msgpack-python, pytoml, python-dateutil, remarshal
2020-07-31T09:45:17.7990121Z   WARNING: The scripts json2json, json2msgpack, json2toml, json2yaml, msgpack2json, msgpack2msgpack, msgpack2toml, msgpack2yaml, remarshal, toml2json, toml2msgpack, toml2toml, toml2yaml, yaml2json, yaml2msgpack, yaml2toml and yaml2yaml are installed in '/home/runner/.local/bin' which is not on PATH.
2020-07-31T09:45:17.7990593Z   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
2020-07-31T09:45:17.8036208Z Successfully installed python-dateutil-2.8.1 pytoml-0.1.21 remarshal-0.11.2 u-msgpack-python-2.6.0
```

pip install packages to user, but local binaries not in path: `are installed in '/home/runner/.local/bin' which is not on PATH.`

**Comment by Hoverbear** [comment]
@fanatid Maybe you can try https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path ?

**Comment by Hoverbear** [comment]
The other option would be to try adding it to the `env:` set.

**Comment by binarylogic** [comment]
@Hoverbear shouldn't this be in the path as part of bootstrapping and preparing our environment?

I had the same issue here:

https://github.com/timberio/vector/blob/cd5979afbed7ffdc098a13c8c48931b120ece8d3/scripts/environment/prepare.sh#L15

And you can see me using the binary here:

https://github.com/timberio/vector/blob/cd5979afbed7ffdc098a13c8c48931b120ece8d3/scripts/check-markdown.sh#L12

It would be nice if we could add this to the `.envrc` or `.profile` file (whatever is appropriate), so they are available for all environments.

**Comment by Hoverbear** [comment]
@fanatid Actually... The `prepare.sh` script can export these no? That should be enough to fix the CI and impact the docker env?

**Comment by Hoverbear** [comment]
@binarylogic I think https://github.com/timberio/vector/blob/cd5979afbed7ffdc098a13c8c48931b120ece8d3/scripts/check-markdown.sh#L12 is preferable as you don't need to worry about users having a different version globally.

**Comment by fanatid** [comment]
@Hoverbear thanks! `add-path` helped.

**Comment by Hoverbear** [comment]
That should be enough then  since our env has it already:

image

**Pull request merged**
