### PR TITLE
docs: Fix wrong example in tokenizer module (version 0.9.1)

### PR DESCRIPTION
**Pull request by xluffy**
In current version (0.9.1), some examples + options are wrong. Just fix docs.

### CODE REVIEW

**Comment by fanatid** [comment]
`tokenizer` fix looks good.
`regex` option in `regex_parser` is deprecated and replaced by `patterns`, see #2493

**Comment by xluffy** [comment]
@fanatid Hmm, I got a error with `patterns` with 0.9.1.

```
root@vg-ubuntu-18-vector:~# dpkg -l | grep vector
ii  vector                          0.9.1                               amd64        A lightweight and ultra-fast tool for building observability pipelines

root@vg-ubuntu-18-vector:~# vector --version
vector 0.9.1 (v0.9.1 x86_64-unknown-linux-musl 2020-04-30)

root@vg-ubuntu-18-vector:~# cat vector.toml
[sources.stdin_console]
  type = "stdin"

[transforms.regex_parser_logs]
  type = "regex_parser"
  inputs = ["stdin_console"]
  field = "message"
  patterns = ['^(?P<host>[\w\.]+) - (?P<user>[\w]+) (?P<bytes_in>[\d]+) \[(?P<timestamp>.*)\] "(?P<method>[\w]+) (?P<path>.*)" (?P<status>[\d]+) (?P<bytes_out>[\d]+)$']

[transforms.regex_parser_logs.types]
  bytes_in = "int"
  timestamp = "timestamp|%d/%m/%Y:%H:%M:%S %z"
  status = "int"
  bytes_out = "int"

[sinks.console_logs]
  type = "console"
  inputs = ["regex_parser_logs"]
  target = "stdout"
  encoding.codec = "json"

root@vg-ubuntu-18-vector:~# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"

root@vg-ubuntu-18-vector:~# vector --config vector.toml
Jun 02 08:02:34.642  INFO vector: Log level "info" is enabled.
Jun 02 08:02:34.642  INFO vector: Loading configs. path=["vector.toml"]
Jun 02 08:02:34.644 ERROR vector: Configuration error: "vector.toml": unknown field `patterns`, expected one of `regex`, `field`, `drop_field`, `drop_failed`, `target_field`, `overwrite_target`, `types` for key `transforms.regex_parser_logs`
```

**Comment by fanatid** [comment]
That's because https://vector.dev/ have live documentation (which updated on each commit to master). 
While #2493 was merged, this changes not included to 0.9.1 (https://github.com/timberio/vector/pull/2493/commits/f1b625bce112befef213152550480bc71edd2a9c -- no tags/branches).
Issue about live/release documentation -- #2649

**Comment by xluffy** [comment]
@fanatid Got it, Should i close this PR and create a new PR for `tokenizer`?

**Comment by fanatid** [comment]
@xluffy yes, it's will work. Also you can make force push with `tokenizer` changes only and change title.

**Comment by xluffy** [comment]
@fanatid 👍 I'm done

**Comment by fanatid** [comment]
Thanks! Can you also include [DCO](https://developercertificate.org/) signature? [CONTRIBUTING.md#signing-off](https://github.com/timberio/vector/blob/master/CONTRIBUTING.md#signing-off)

**Comment by xluffy** [comment]
fixed @fanatid

**Pull request merged**
