### PR TITLE
chore: Update arc-swap

### PR DESCRIPTION
**Pull request by MOZGIII**
This PR updated arc-swap to make cargo-deny happy.

### CODE REVIEW

**Review by fanatid — APPROVED** [review]
Thanks @MOZGIII! I think this is a more correct fix of #5461 than #5552. I'll update #5552 when this will be merged for removing warnings on advisories check.

**Review by jszwedko — APPROVED** [review]
:+1: I see there is a 1.0 version of arc-swap that we might want to try upgrading to at some point too.

**Comment by fanatid** [comment]
@jszwedko `arc-swap` is not a direct dependency, we blocked by `goauth` / `metrics-util`:
```
$ cargo tree -p arc-swap -i
arc-swap v0.4.7
├── goauth v0.8.1
│   └── vector v0.12.0 (/home/kirill/projects/vector)
└── metrics-util v0.4.0-alpha.6
    ├── metrics-tracing-context v0.1.0-alpha.3
    │   └── vector v0.12.0 (/home/kirill/projects/vector)
    └── vector v0.12.0 (/home/kirill/projects/vector)
```

**Comment by MOZGIII** [comment]
Thx for the reviews, I'll wait for the CI to pass and merge.

**Comment by jszwedko** [comment]
> @jszwedko `arc-swap` is not a direct dependency, we blocked by `goauth` / `metrics-util`:
> 
> ```
> $ cargo tree -p arc-swap -i
> arc-swap v0.4.7
> ├── goauth v0.8.1
> │   └── vector v0.12.0 (/home/kirill/projects/vector)
> └── metrics-util v0.4.0-alpha.6
>     ├── metrics-tracing-context v0.1.0-alpha.3
>     │   └── vector v0.12.0 (/home/kirill/projects/vector)
>     └── vector v0.12.0 (/home/kirill/projects/vector)
> ```

Aha, gotcha :smile:

**Comment by MOZGIII** [comment]
@jszwedko regression detected! :tada: Happy to see our benches in action!

**Comment by MOZGIII** [comment]
I'm going to merge this still, as it seems like there's nothing we can do about it now.

**Comment by jszwedko** [comment]
> @jszwedko regression detected! tada Happy to see our benches in action!

:smile: the diffs seem small enough that I'm fairly sure it is just noise. We have an open issue to get more consistent measurements, #5394 , but we'll also tune the noise parameters to avoid false positives. I wanted to collect some data on how much noise we see in GA before tuning that parameter.

**Pull request merged**
