### PR TITLE
enhancement(tests): cleanup vector dir post k8s test

### LINKED ISSUE #7544: Kubernetes tests should clean up their data directories when they finish
The tests should clean up their data directories when they finish. Currently they don't and this could cause issues if we are intending on testing on a long running cluster.

@spencergilbert has provided this yaml that should do the trick:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: data-dir-cleaner
spec:
  selector:
    matchLabels:
      name: data-dir-cleaner
  template:
    metadata:
      labels:
        name: data-dir-cleaner
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: cleaner
          image: alpine:latest
          command: ["rm"]
          args: ["-rf", "/var/lib/vector/*"]
          volumeMounts:
            - name: data-dir
              mountPath: /var/lib/vector
      volumes:
        - name: data-dir
          hostPath:
            path: /var/lib/vector
```

### PR DESCRIPTION
**Pull request by StephenWakely**
Closes #7544 

This creates a Daemonset that deletes the Vector directory. Each test deploys this post test. 

Signed-off-by: Stephen Wakely <fungus.humungus@gmail.com>

### CODE REVIEW

**Comment by spencergilbert** [comment]
I guess an alternative here could be exposing [lifecycle hooks](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/) in our helm charts, and configuring the preStop hook to do something similar as we remove the daemonset

**Comment by StephenWakely** [comment]
> I assume this passes e2e tests?

Of course!

I like the idea of lifecycle hooks though. They could come in handy in numerous other situations.

**Comment by prognant** [comment]
> > I assume this passes e2e tests?
> 
> Of course!
> 
> I like the idea of lifecycle hooks though. They could come in handy in numerous other situations.

I like that too, I think we could register the hook directly from rust code (I would guess [somewhere here](https://github.com/timberio/vector/blob/master/lib/k8s-test-framework/src/framework.rs#L21-L37)), without impacting helm charts.  WDYT ?

**Comment by spencergilbert** [comment]
> I like that too, I think we could register the hook directly from rust code (I would guess [somewhere here](https://github.com/timberio/vector/blob/master/lib/k8s-test-framework/src/framework.rs#L21-L37)), without impacting helm charts. WDYT ?

Definitely if we could, I'm not sure though - I thought we just did a `helm install` but y'all might be more familiar with this code than me

**Comment by StephenWakely** [comment]
> I like that too, I think we could register the hook directly from rust code (I would guess [somewhere here](https://github.com/timberio/vector/blob/master/lib/k8s-test-framework/src/framework.rs#L21-L37)), without impacting helm charts. WDYT ?

That function calls the [deploy-kubernetes-test.sh](https://github.com/timberio/vector/blob/master/scripts/deploy-kubernetes-test.sh) script, which essentially does a helm install.  My knowledge of Helm doesn't stretch far enough to know whether we can register hooks outside of the Helm chart. Do you have any pointers?

**Comment by spencergilbert** [comment]
> > I like that too, I think we could register the hook directly from rust code (I would guess [somewhere here](https://github.com/timberio/vector/blob/master/lib/k8s-test-framework/src/framework.rs#L21-L37)), without impacting helm charts. WDYT ?
> 
> That function calls the [deploy-kubernetes-test.sh](https://github.com/timberio/vector/blob/master/scripts/deploy-kubernetes-test.sh) script, which essentially does a helm install. My knowledge of Helm doesn't stretch far enough to know whether we can register hooks outside of the Helm chart. Do you have any pointers?

Nope - we'd need to expose it as a template-able section of the chart, it should be a pretty trivial addition - up to you if you'd prefer to "throw this work away"

**Comment by StephenWakely** [comment]
Closing this in favour of #7841 which implements the recommended lifecycle hooks (much cleaner imho).

**Pull request closed without merging**
