### PR TITLE
chore(deps): Run a blanket cargo update

### PR DESCRIPTION
**Pull request by Hoverbear**
This rather boldly just runs `cargo update` and asks "Will the tests still pass on all platforms?"

This is partially motivated by our discussion about #2840 regarding the use of the https://docs.rs/string/0.2.1/string/index.html crate. During adoption I found we still had multiple copies of the `bytes` crate in tree. (We still have one thanks to `elastic_responses`, but it's only in the dev tree)

While attempting to hack at the forest I decided to just go "Let's see what happens" and it looks like this might do a lot of good.

I updated our lucet version.

### CODE REVIEW

**Comment by Hoverbear** [comment]
Before
master-graph

After
graph

**Comment by binarylogic** [comment]
Lol at that dependency graph. Can anyone tell the difference between the before and after?

**Comment by Hoverbear** [comment]
I can! 
image

**Comment by binarylogic** [comment]
On a more serious note. What are the risks of blindly do this? Thinking specifically about the items [here](https://github.com/timberio/vector/blob/master/REVIEWING.md#dependencies).

**Comment by Hoverbear** [comment]
So this is what dependabot does one-by-one already, just all done at once!

Since this is only upgrading our existing dependencies up to their semantic-versioning-based compatible version, this should only create failures that we'd see in CI.

**Comment by Hoverbear** [comment]
Fascinating:
image

**Comment by jamtur01** [comment]
That's a surprisingly small amount of fail. 👍

**Comment by Hoverbear** [comment]
Let's see if this is enough to coax it into working.

**Comment by Hoverbear** [comment]
... Wow.

**Comment by Hoverbear** [comment]
Small hiccup: 
image

Going to roll back zstd and try more

**Comment by Hoverbear** [comment]
Okay! This is gold!

**Pull request merged**
