### PR TITLE
chore: Remove redundant sortings

### PR DESCRIPTION
**Pull request by juchiast**
Signed-off-by: Duy Do <juchiast@gmail.com>

### CODE REVIEW

**Comment by binarylogic** [comment]
Do we have tests that assert the sorting if it is required? This will ensure it does not break if the underlying data structure changes.

**Review by fanatid — APPROVED** [review]
LGTM. While keys produced by `BTreeMap` iterator sorted by key it's still would be nice to have a test.

**Review by jszwedko — APPROVED** [review]
:+1: good catches

**Comment by juchiast** [comment]
@binarylogic Added a test!

**Pull request merged**
