### PR TITLE
chore(datadog service)!: Rename `datadog_logs` source to `datadog_agent`

### PR DESCRIPTION
**Pull request by jszwedko**
We've decided to make this source specific to the agent as-per
https://github.com/timberio/vector/pull/8297#discussion_r670788059

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Review by blt — APPROVED** [review]

**Review by spencergilbert — APPROVED** [review]
Noting this will also require on Datadog's docs side

**Comment by prognant** [comment]
I can prepare the datadog docs update on monday.
Apart from that, and on top of other consideration (which I strongly agree with), I think this will enable us to be more consistent for aggregating datadog agents, as this source would then naturally evolve to support all agent traffic (log, metrics, traces, metadata, etc.), and this is way more practical to have a dedicated source to do that while keeping a datadog_logs source that would only do logs (and probably a metric source in the near future).

**Comment by blt** [comment]
@jszwedko is this PR blocked by anything, other than the semantic title ding?

**Comment by jszwedko** [comment]
@blt I was hoping to get @binarylogic and/or @lucperkins's eyes on it, but otherwise this should be good-to-go.

**Review by binarylogic — APPROVED** [review]

**Pull request merged**
