### PR TITLE
fix(sinks): address potential deadlock

### LINKED ISSUE #2577: Investigate poll_complete possible hang
This poll_complete that we have in our `BatchedHttpSink` should attempt to only return `NotReady` if `poll_complete` applies back pressure.

Reference https://github.com/timberio/vector/pull/2573#discussion_r423233151

### PR DESCRIPTION
**Pull request by lukesteensen**
Closes #2577

While likely not an issue in practice, our `start_send` implementation here was theoretically vulnerable to deadlock.

The issue would occur if the sink's slot was full and the subsequent call to `poll_complete` returned `Async::Ready`. We would then incorrectly return `NotReady` when we actually had the ability to accept the item. This is a problem because no underlying component had returned `NotReady` and our task would therefore not be registered to wake on any future notification.

### CODE REVIEW

**Comment by bruceg** [comment]
I looked at the logic, and I don't think it's actually possible to loop infinitely. Can you describe a case where it could? `poll_complete` takes the slot, which leaves it `None` which breaks the loop. The only way for the slot to be refilled there returns not ready, which also breaks the loop with a return. That said, I don't see a way for it to loop more than once, making the `while` pointless, so maybe I'm missing something too.

**Comment by Hoverbear** [comment]
That's kind of where I'm getting hung up! :thinking:

**Comment by lukesteensen** [comment]
> That said, I don't see a way for it to loop more than once, making the `while` pointless, so maybe I'm missing something too.

Yeah, it ends up just being a terse way to check the conditional twice. I agree that's confusing. How would we feel about something like this instead?

```rust
if self.slot.is_some() {
    if self.poll_complete()?.is_not_ready() {
        return Ok(AsyncSink::NotReady(item));
    }
}
assert!(self.slot.is_none(), "poll did not clear slot");
```

**Comment by lukesteensen** [comment]
The difference is really just how it handles bugs in `poll_complete`. The `while` loop will continue looping in the hope that progress is eventually made, while the assert will just panic due to the contract being violated.

**Comment by lukesteensen** [comment]
`http2.rs` doesn't exist anymore :tada:

**Pull request merged**
