### PR TITLE
chore: Adjust import of `crate::Event` to `crate::event::Event`

### PR DESCRIPTION
**Pull request by blt**
My end goal here is to move the `Event` and related types into
`vector-core`. This is possible but trickier if we maintain a top-level `Event`
import in vector and so here I've adjusted all imports of the relevant type to
`crate::event::Event`, removing the top-level `Event`.

This is all mechanical work and I have intentionally not changed any logic, in
deference to the size of this PR.

REF #7148

Signed-off-by: Brian L. Troutwine <brian@troutwine.us>

### CODE REVIEW

**Review by lukesteensen — APPROVED** [review]

**Comment by bruceg** [comment]
> This is possible but trickier if we maintain a top-level `Event`
> import in vector and so here I've adjusted all imports of the relevant type to
> `crate::event::Event`, removing the top-level `Event`.

I don't follow the logic here how not doing this step is trickier (see the previous attempt to do this same move in #3357). Could we not `pub use vector_core::Event` in `src/lib.rs` to a similar effect? Ref https://github.com/timberio/vector/blob/22d6030f4831d0d02b0468fc57f0130fb3acc2e6/src/lib.rs#L60

**Comment by StephenWakely** [comment]
I concur with Bruce, I'm not really understanding the aim of this? 

I don't necessarily object since it is nice to keep things namespaced.  Personally I'm not a particular fan of modules just reexporting, I find navigating easier if the import indicates the precise module where the type is defined. I think my preference would be for everything to ultimately `use vector-core::Event`. I'm not sure I see how this is a stepping stone towards that?

**Comment by blt** [comment]
> > This is possible but trickier if we maintain a top-level `Event`
> > import in vector and so here I've adjusted all imports of the relevant type to
> > `crate::event::Event`, removing the top-level `Event`.
> 
> I don't follow the logic here how not doing this step is trickier (see the previous attempt to do this same move in #3357). Could we not `pub use vector_core::Event` in `src/lib.rs` to a similar effect? Ref
> 
> https://github.com/timberio/vector/blob/22d6030f4831d0d02b0468fc57f0130fb3acc2e6/src/lib.rs#L60

They should be equivalent, yep, but in practice the re-export at the top of the root package throws off the bulk code movement tools in VSCode and IntelliJ. I can't say why. Possibly a rust-analyzer problem? This is not an absolutely necessary kind of change but it does mean I need to move stuff around less by hand, is what I'm getting at with the "trickier" comment.

**Comment by blt** [comment]
> I concur with Bruce, I'm not really understanding the aim of this?

Touched on that here: https://github.com/timberio/vector/pull/7200#issuecomment-824283848 

> I don't necessarily object since it is nice to keep things namespaced. Personally I'm not a particular fan of modules just reexporting, I find navigating easier if the import indicates the precise module where the type is defined. I think my preference would be for everything to ultimately `use vector-core::Event`. I'm not sure I see how this is a stepping stone towards that?

Yep, though I'd probably go in for `vector_core::event::Event` but that's for a later discussion probably. As much as possible I want to reduce the number of whole-tree changes in each PR so they're easier to review and would eventually follow up with a PR that just migrates the imports to `vector_core`, killing the top-level package re-export.

**Review by StephenWakely — APPROVED** [review]
Makes sense!

**Pull request merged**
