### PR TITLE
fix(file source): log a single warning when ignoring small files

### LINKED ISSUE #842: Add log message if file is ignored due to too little content
A follow up issue for https://github.com/timberio/vector/issues/828#issuecomment-527941051

We need to communicate to users when a file is ignored for whatever reason.

### PR DESCRIPTION
**Pull request by lukesteensen**
Closes #842

This ended up being kind of annoying. The naive solution results in spamming log messages every time we glob for new files. Rate limiting that log doesn't seem like a great solution because I don't think there's a point in reminding the user every so often that a small file is still small. This message is really targeted at people manually testing out Vector by `echo`ing to a file and then waiting for something to happen. Since that really only needs to happen once, we keep a set of files we've already warned about being too small and use that to log exactly one time when we see a small file. :man_shrugging:

### CODE REVIEW

**Comment by stormasm** [comment]
@lukesteensen thanks for adding this warning about small files...
I could not figure out why my source file was not working...

My test input file was tiny and nothing was happening...

Now that this message has been added I got insight into why it was not working.
I made my file bigger than 256 bytes and everything started working...
Thank you !

**Comment by karlseguin** [comment]
Any chance to _not_ log this for 0 byte files?

**Comment by binarylogic** [comment]
Hey @karlseguin, we certainly could. Do you mind expanding on your use case a little more? We could consider an `ignore_empty` option that would ignore empty files.

Alternatively, you could switch the fingerprinting strategy to `device_and_inode`:

```toml
[sources.file]
  type = "file"
  fingerprinting.strategy = "device_and_inode"
```

You can read more about that here:

https://docs.vector.dev/v/master/usage/configuration/sources/file#file-identification

Let me know if that helps.

**Comment by karlseguin** [comment]
I'm asking specifically about the warning. It just adds noise to our error logs when empty files get created. I realize this is a WARN, so I could just up our log level to ERROR...or I could, you know, use Vector to filter it out, but...The initial issue was:

> We need to communicate to users when a file is ignored for whatever reason.

While it might be technically correct to say that an empty file is being "ignored" (for lack of the required fingerprint bytes), since there's nothing to log, I think an warning about it being ignored is counter-productive. I think it's safe to silently ignore empty files (or drop the log level to INFO or DEBUG).

Reproduce with this vector.toml:
```
data_dir = "/tmp"

[sources.test_in]
  type = "file"
  ignore_older = 172800
  include = ["test.log"]

[sinks.text_out]
  inputs = ["test_in"]
  type = "console"
```
Then run vector:
```
./vector --config vector.toml
```

And run:
```
touch test.log
```

What do I expect to see? Nothing
What do I actually see? "WARN source{name="test_in"}:file_server: file_source::file_server: Ignoring file smaller than fingerprint_bytes file="test.log""

**Pull request merged**
