### PR TITLE
enhancement(platforms): Setup cross compiling to mips with cross (WIP)

### PR DESCRIPTION
**Pull request by nazar554**
Build with

```bash
RUSTFLAGS="-C target-feature=+xgot -C target-feature=+crt-static \
-L /usr/local/lib/gcc/mipsel-linux-muslsf/6.4.0 -L /usr/local/mipsel-linux-muslsf/lib \
-C link-arg=-Wl,-Bstatic -C link-arg=-lstdc++ -C link-arg=-lc -C link-arg=-latomic -C link-arg=-lgcc -C link-arg=-Wl,-Bdynamic \
" \
cross build --target mipsel-unknown-linux-musl --no-default-features --features "$(cat features)"
```

`features` are same as `default-musl`, except `vendor-sasl` and `sources-docker`
```
sources-file sources-generator sources-http sources-internal_metrics sources-journald sources-kafka sources-logplex sources-prometheus sources-socket sources-splunk_hec sources-statsd sources-stdin sources-syslog sources-tls sources-vector sources-kubernetes-logs transforms sinks vendor-openssl vendor-libz unix leveldb-cmake rdkafka-cmake
```

vendor-sasl: fails to build due to some unknown error, most likely it uses wrong linker (need to try setting TARGET_LD and add it to Cross.toml)

```
  = note: /usr/local/bin/../lib/gcc/mipsel-linux-muslsf/6.4.0/../../../../mipsel-linux-muslsf/bin/ld: /target/mipsel-unknown-linux-musl/debug/deps/libsasl2_sys-4a6f0408e9c9649d.rlib(client.o): Relocations in generic ELF (EM: 62)                                                                                                                                                        
          /usr/local/bin/../lib/gcc/mipsel-linux-muslsf/6.4.0/../../../../mipsel-linux-muslsf/bin/ld: /target/mipsel-unknown-linux-musl/debug/deps/libsasl2_sys-4a6f0408e9c9649d.rlib(client.o): Relocations in generic ELF (EM: 62)                                                                                                                                                        
          /target/mipsel-unknown-linux-musl/debug/deps/libsasl2_sys-4a6f0408e9c9649d.rlib: error adding symbols: File in wrong format                                                         
          collect2: error: ld returned 1 exit status
```
		 
`sources-docker`: depends on rustls & ring, fails on ring's build.rs (missing assembly crypto primitives for MIPS)

If we need to build a static binary we need `-C target-feature=+xgot`
otherwise we get errors like:
```
relocation truncated to fit: R_MIPS_GOT16 against `memcpy'
```
https://gcc.gnu.org/onlinedocs/gcc-3.4.6/gcc/MIPS-Options.html

Dynamic build links (remove `-C link-arg=-Wl,-Bstatic` and `C link-arg=-Wl,-Bdynamic`, `-C target-feature=+crt-static`)
Currently final static linking fails most likely due to https://github.com/rust-lang/rust/issues/36710
```
  = note: /usr/local/mipsel-linux-muslsf/lib/libstdc++.a(system_error.o): In function `__static_initialization_and_destruction_0':
          /tmp/tmp.YeBfj1Eiss/build/local/mipsel-linux-muslsf/obj_gcc/mipsel-linux-muslsf/libstdc++-v3/src/c++11/../../../../../src_gcc/libstdc++-v3/src/c++11/system_error.cc:70: undefined reference to `__dso_handle'
          /tmp/tmp.YeBfj1Eiss/build/local/mipsel-linux-muslsf/obj_gcc/mipsel-linux-muslsf/libstdc++-v3/src/c++11/../../../../../src_gcc/libstdc++-v3/src/c++11/system_error.cc:71: undefined reference to `__dso_handle'
          /rust/lib/rustlib/mipsel-unknown-linux-musl/lib/libstd-04d242cd37db4ff6.rlib(std-04d242cd37db4ff6.std.bp0ve1o5-cgu.0.rcgu.o):(.data._rust_extern_with_linkage___dso_handle+0x0): undefined reference to `__dso_handle'
          collect2: error: ld returned 1 exit status
```

### CODE REVIEW

**Comment by Hoverbear** [comment]
@nazar554 Since this is a musl build it'd be best if we could make this static I think!

**Comment by Hoverbear** [comment]
We've had a lot of problems with sasl as well here. Feel free to leave it off in this initial implementation, we can add it later. :)

**Comment by binarylogic** [comment]
@Hoverbear what's the status of this given the new cross changes? Should we leave open or close?

**Comment by jamtur01** [comment]
This will still fail because `ring` doesn't support mips I think?

**Comment by nazar554** [comment]
@jamtur01 Yeah, I disabled some features, so it doesn't use `rustls` & `ring`.

I'll try to do a new PR with cross CI changes

**Pull request closed without merging**
