### PR TITLE
fix(search): Safelist search widget classes from purging and inject env vars into search.tsx

### PR DESCRIPTION
**Pull request by lucperkins**
This PR fixes some aesthetic issues with the Algolia search widget caused by JavaScript-injected classes being purged by our PurgeCSS config. These classes are now safelisted. This PR also allows for dynamic injection of environment variables into the `search.tsx` logic.

### CODE REVIEW

**Comment by jszwedko** [comment]
I'm unsure if this was intentional, but this seems to have broken the actual linking part of the search results. Clicking on one of them doesn't do anything now. They do look better though.

**Comment by lucperkins** [comment]
@jszwedko I think that was due to some tinkering I was doing on the indices late last night. I've re-built them, so this should work as normal. Could you check again?

**Comment by jszwedko** [comment]
Hmm, now I'm seeing this:

Screen Shot 2021-07-09 at 1 18 52 PM

Is that expected?

**Comment by lucperkins** [comment]
@jszwedko Unfortunately this is a really tricky problem on a site where we have so many docs with highly overlapping structures and headings (particularly amongst the component docs).

**Comment by zsherman** [comment]
The solution here is just to prepend with the high level category or page, which we can do once the index structure is updated.

**Review by zsherman — APPROVED** [review]

**Pull request merged**
