### PR TITLE
enhancement(remap): Add charset parameter to encode_base64 function

### LINKED ISSUE #6011: Support character sets in the `encode_base64` Remap function
The `encode_base64` is limited and scant on details. We should allow users to specify which character set they want to use (default to `standard`) as defined [here](https://docs.rs/base64/0.13.0/base64/enum.CharacterSet.html).

We don't have to support all of these, but I can see users wanting both the `standard` and `url_safe` variants.

### PR DESCRIPTION
**Pull request by lucperkins**
Adds a `charset` parameter to the `encode_base64` function with two possible values: `standard` and `url_safe`. It's fairly trivial to add others in the future.

Closes #6011

### CODE REVIEW

**Review by jszwedko — COMMENTED** [review]
Looks good!

I think, with this addition, the function should be marked as always fallible given that users can pass invalid charsets.

**Comment by lucperkins** [comment]
@jszwedko Ah yes, you're quite right about the fallibility of the charset. I've updated that.

**Review by jszwedko — APPROVED** [review]
:partying_face:

**Comment by lucperkins** [comment]
@jszwedko Though, quite nit slash FYI: it doesn't make the function always fallible. Rather, it makes the function fallible *if* `charset` is specified. Jean's handy `merge_optional` handles that nicely.

**Pull request merged**
