### PR TITLE
fix(tests): require features for generate_configfile test

### PR DESCRIPTION
**Pull request by fanatid**
Added in #4819 

Test should not be compiled without required features.

### CODE REVIEW

**Review by jszwedko — COMMENTED** [review]
It looks like you might want to move `use tempfile::tempdir;` into `generate_configfile` to avoid the unused import for other component features..

**Comment by fanatid** [comment]
Thanks @jszwedko! Stupid CI fail from me :facepalm:

**Review by jszwedko — COMMENTED** [review]
Looks like `cleanup_configfile` might need a `cfg` block too :smile:

**Review by jszwedko — APPROVED** [review]
Looks good!

**Pull request merged**
