### PR TITLE
docs(remap): Fix 'Modify metric tags' example

### LINKED ISSUE #7881: Remap and metric event documentation issues
https://vector.dev/docs/reference/vrl/examples/#modify-metric-tags

This example doesn't actually work as the current vrl implementation requires you to access them under the `.tags` field. It should be updated to:

```rust
.tags.environment = get_env_var!("ENV") # add
.tags.hostname = del(.tags.host) # rename
del(.tags.email)
```

Additionally we added some documentation originally based off this PR: https://github.com/timberio/vector/pull/5626
However, it appears as though it was lost in some documentation shuffling. We need to document how to properly interact with metric events via remap.

### PR DESCRIPTION
**Pull request by spencergilbert**
Signed-off-by: Spencer Gilbert <spencer.gilbert@gmail.com>

Closes #7881 (partially)

There is a snippet of text referencing how remap interacts with metric events, but it's not rendered on today's website.
Do we want to edit the existing website and correct the snippet, or have an issue to ensure we document the interactions on the new website?

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
Thanks! This particular example is rendered on the website (on https://vector.dev/docs/reference/configuration/transforms/remap/#examples). Is there another snippet you are referring to that is missing?

**Comment by spencergilbert** [comment]
> Thanks! This particular example is rendered on the website (on https://vector.dev/docs/reference/configuration/transforms/remap/#examples). Is there another snippet you are referring to that is missing?

Womp - I forgot to link that bit: https://github.com/timberio/vector/blob/master/docs/reference/remap.cue#L268-L278

**Comment by jszwedko** [comment]
> https://github.com/timberio/vector/blob/master/docs/reference/remap.cue#L268-L278

Aha, I see! Yeah, I think we can just update that snippet and leave it for the site relaunch rather than fussing with the templates for the current one.

**Comment by spencergilbert** [comment]
> > https://github.com/timberio/vector/blob/master/docs/reference/remap.cue#L268-L278
> 
> Aha, I see! Yeah, I think we can just update that snippet and leave it for the site relaunch rather than fussing with the templates for the current one.

I'll update this PR and make sure the description is correct

**Review by JeanMertz — APPROVED** [review]

**Comment by spencergilbert** [comment]
@jszwedko @JeanMertz I updated the data model text - even though I don't think we're displaying it anywhere.

**Review by jszwedko — APPROVED** [review]

**Pull request merged**
