### PR TITLE
fix(security): Handle multiple (intermediate) certificates in PEM files

### LINKED ISSUE #3664: TLS certificate chain not being sent
Hey! We are using the latest 0.10.0 and again we have some TLS troubles.

We have a Lets Encrypt certificate that has an intermediary certificate before the root. Both certificates are in the .crt file, and the .key file has ofc just one key, for the server certificate and not for the intermediate cert. The server (vector in this instance) is supposed to send the full chain, but it is not sending the intermediate certificate.

Running `openssl s_connect` we learn that the problem is exactly chain validation:

```
SSL handshake has read 2009 bytes and written 413 bytes
Verification error: unable to verify the first certificate
```

So I end up having to place some proxy in front of Vector to handle the TLS part of the connection.

## How To Reproduce

* Create a cert with an intermediate CA before the root CA.
* Configure vector to use that cert using `tls.crt_file` and `tls.key_file`
* Try to connect to vector securely using i.e. OpenSSL or even curl

### PR DESCRIPTION
**Pull request by Hoverbear**
Attempts to add a reproduction case for #3664 .

It's not quite there... I'm actually finding a different error.

After starting Vector with the following config:

```toml
data_dir = "tmp"

[sources.plain]
type = "http" # required
address = "0.0.0.0:8080" # required
encoding = "text" # optional, default
tls.ca_file = "tests/data/Vector_CA.crt"
tls.crt_file = "tests/data/Chain_with_intermediate.crt"
tls.key_file = "tests/data/Crt_from_intermediate.key"
tls.enabled = true

[sinks.localhost]
inputs = ["plain"]
type = "console"
encoding = "json"
```

I sent data:

```bash
ana@autonoma:~/git/timberio/vector$ curl -k -X POST localhost:8080 -d '{json}' -H 'Content-Type: application/json' 
```

This worked.

When I poked with `openssl s_client` I noted the `Vector CA` we test with wasn't included.

```bash
ana@autonoma:~/git/timberio/vector$ openssl s_client -showcerts -connect localhost:8080 -CAfile tests/data/Crt_from_intermediate.crt 
CONNECTED(00000003)
Can't use SSL_get_servername
depth=0 C = US, ST = New York, L = Brooklyn, O = Timber.io, CN = Timber.io Test Certificate with Intermediate CA
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = US, ST = New York, L = Brooklyn, O = Timber.io, CN = Timber.io Test Certificate with Intermediate CA
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:C = US, ST = New York, L = Brooklyn, O = Timber.io, CN = Timber.io Test Certificate with Intermediate CA
   i:C = US, ST = New York, L = Brooklyn, O = Timber.io, CN = Timber.io Vector Test Intermediate CA
-----BEGIN CERTIFICATE-----
MIIFgDCCA2gCFAZvNaUvO5A6nWUjmjmS1R9x+1DfMA0GCSqGSIb3DQEBCwUAMHcx
CzAJBgNVBAYTAlVTMREwDwYDVQQIDAhOZXcgWW9yazERMA8GA1UEBwwIQnJvb2ts
eW4xEjAQBgNVBAoMCVRpbWJlci5pbzEuMCwGA1UEAwwlVGltYmVyLmlvIFZlY3Rv
ciBUZXN0IEludGVybWVkaWF0ZSBDQTAeFw0yMDA5MDIyMTM4MDJaFw00ODAxMTgy
MTM4MDJaMIGBMQswCQYDVQQGEwJVUzERMA8GA1UECAwITmV3IFlvcmsxETAPBgNV
BAcMCEJyb29rbHluMRIwEAYDVQQKDAlUaW1iZXIuaW8xODA2BgNVBAMML1RpbWJl
ci5pbyBUZXN0IENlcnRpZmljYXRlIHdpdGggSW50ZXJtZWRpYXRlIENBMIICIjAN
BgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA0OFPCw7hwYxBAZV7rltkUA0UcTkP
/mu8VG/uQBcJwz7bqZHjGJyVzuiaaeqg1DTx7CUbHwo/ZkRrB0XwsHDrJ3IrO8lg
9/TxGgMODou+mlALNo3aZPNylhZFmrWCUQTras4n3JhotfXnPlVJQcRNqRTpi8/r
TIhHXe/tlfDlRytEDN3uUwb97cDeKT0W8N+A7fuShe/W2sPusTWSDzMsFZdvgcHN
2ZiJnpu3fotESqC3Ph+EcIyXuYFSdVjSf/dO8PG2r2wNUw5Gjy31/5ePBElVtVtt
PCDeT8S4IzyA25xVJwmPQ5itIdoArNLGty/MS6iykJ3LqojA9H2k+qOLLOPRU5Yp
BTN1VBVxvzb/VMfcC6ohNQwf7hcIVSVzCEJkecz5WD7R/rYMi47eEwGLv1f+Ljzo
QtLyJrnDImeFi754SJ0lP1GXNRJKGZ94Duh43rRR5/Alyb05UB4lPPTBCYfL8ak3
LvmpqmFfc4BgxbGO5LmNzMgR7C+yY5a5C024NjEv3TvH9tM85wDngRmQIRaUxDp9
hDrROU6UwkiadyIv5/PFEjMkURyt4CDNyvv5A9dPzRTufMoa8ZLKboViPo1FvR6l
ycY5vIH0dQfOx+p41Q501yZGUAFog7JkIfeW8bqLFxda7+4UKf10M0/eZPUMO78O
vGD3nmVl04+jqsECAwEAATANBgkqhkiG9w0BAQsFAAOCAgEAsFji2oLQVgWr0Cx9
WRnNpb6R5Gqdk5erL9x4mhX16qZwXfnuUNhw1OsGvdLcU7BqEvQW4xo2sZXPcyZj
ZxA52goigYRS0u8QPLZw5tMAKYXRuMxPjdNsmdBIpPDra5VTxHlBCdfa0MuwPJyw
hA1qrlexLrK3s1sw7HVjOSt0hbi/ZQnwUSeidKHipbQm1zJr92lg6UnjJPCD5RON
BCr+xHiJJ3dpjeoJf8Pn6UqiZliij676+nOElPSraXdq9J+xyDCS12fX0jNnfcxR
lbGxM8HIixmJOygBNRaBMKraz8sYfoP2mLmG/Jp0ILNzTRW8O+4tdUDqQOhPJdql
eXl25ypDaBucdQ3Ggci0V60F+rYFzE2SeDqK4DkFbSu0a9C3MBhBF8t/bhoKkNA6
4XvXDngV811xCV08o5+DjKy04azZ9csjIgXfvmneNRoCZnm0EsNNDbPZ0oNEGhgF
6aTMcbqS4FJmzMmyTD7O+YXNwM9ZkTASUsEVnOvuggUgv70v65yxyJksjpOSWKCJ
wwkVnNMUA7F09qn1nhJlHu9Uk07cGZOkTPoUoENXlSG6WR41jFM1k+g3V3Q2SOlK
Q7M8gc9d5vm/kTG27Wmiwpaf2NPSQM11S5KtinAUd5gpJBjvS7+yxSv4GUh++MgY
jchPXSPtV9lWGQQyhQcn9QVxtJE=
-----END CERTIFICATE-----
---
Server certificate
subject=C = US, ST = New York, L = Brooklyn, O = Timber.io, CN = Timber.io Test Certificate with Intermediate CA

issuer=C = US, ST = New York, L = Brooklyn, O = Timber.io, CN = Timber.io Vector Test Intermediate CA

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 2285 bytes and written 368 bytes
Verification error: unable to verify the first certificate
---
New, TLSv1.2, Cipher is ECDHE-RSA-CHACHA20-POLY1305
Server public key is 4096 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-CHACHA20-POLY1305
    Session-ID: 26FD5B4A28E3D985611316D9762AD8FCC18175479841BE7720F322266B417B92
    Session-ID-ctx: 
    Master-Key: 75A7A773B16C0609615AC86AE68A9385495A9C99106E2C029B996D64C3FED2EB40FD52CC1A9DDEFCEBC16983D50709EE
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - 4b 77 f0 d0 61 59 23 09-e1 72 9b d2 67 e8 16 21   Kw..aY#..r..g..!
    0010 - e2 c1 e8 1a 02 52 33 b7-91 67 cf 50 0a 63 6d 11   .....R3..g.P.cm.
    0020 - 62 e6 73 fb 28 18 56 8c-72 9a f1 ca f6 aa 86 c0   b.s.(.V.r.......
    0030 - 3e 07 05 82 23 89 d8 98-4c 90 82 b3 64 8c 11 99   >...#...L...d...
    0040 - 23 3c 06 f9 3b 39 fb 2d-a6 48 3c 44 33 c8 f5 6d   #<..;9.-.H<D3..m
    0050 - e7 1b 26 64 78 64 86 67-6b 06 43 74 25 00 0f 86   ..&dxd.gk.Ct%...
    0060 - 9b c5 c0 71 03 4e a1 65-2b 85 6c 16 0f c9 1c ba   ...q.N.e+.l.....
    0070 - 03 4a b4 52 c5 be bc b8-39 a5 03 66 98 b6 e9 c8   .J.R....9..f....
    0080 - f6 0e d7 61 ae 6a 2c 53-01 ef 56 b6 07 b3 d2 ac   ...a.j,S..V.....
    0090 - 31 2a 83 b1 c0 e0 ab 82-b7 35 d8 0d 3a ec 8b 4f   1*.......5..:..O

    Start Time: 1599087313
    Timeout   : 7200 (sec)
    Verify return code: 21 (unable to verify the first certificate)
    Extended master secret: yes
---
```

Closes #3664

### CODE REVIEW

**Comment by Hoverbear** [comment]
This seems to reproduce the problem. :thinking: @bruceg Does this look like a reasonable reproduction to you?

**Comment by Hoverbear** [comment]
@suvl Thanks for that. :) You're right, seems I was a bit sleepy last day.

**Comment by Hoverbear** [comment]
@bruceg Changes look good to me.

**Review by bruceg — APPROVED** [review]

**Comment by bruceg** [comment]
Closes #3664

**Comment by Hoverbear** [comment]
LGTM

**Comment by khionu** [comment]
I ran into another issue around CAs, might be related.

```
Sep 11 16:45:51 vector-test-primary vector[1113]: Sep 11 16:45:51.716  INFO vector::topology:
 Starting sink "gcs"
Sep 11 16:45:51 vector-test-primary vector[1113]: Sep 11 16:45:51.759 ERROR vector::topology:
:builder: Healthcheck: Failed Reason: error trying to connect: the handshake failed: error:14
16F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/state
m_clnt.c:1915:: unable to get local issuer certificate
```

**Pull request merged**
