### PR TITLE
fix(aws_cloudwatch_logs sink): Allow adaptive concurrency

### LINKED ISSUE #9006: `aws_cloudwatch_logs` sink does not allow `request.concurrency = "adaptive"`
Reported by user in discord: https://discord.com/channels/742820443487993987/746070591097798688/882881430512885791

```
Sep 02 06:06:36.087 ERROR vector::cli: Configuration error. error=invalid type: string "adaptive", expected usize for key `sinks.cloudwatch_logs_central` at line 1 column 1
```

Using Vector 0.16.1.

### PR DESCRIPTION
**Pull request by jszwedko**
Fixes #9006

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

### CODE REVIEW

**Review by jszwedko — COMMENTED** [review]
I ended up changing this more than expected to match how other sinks are creating services. I'm not very familiar with tower services though so I'm curious to get your thoughts on these changes @bruceg . It's possible this sink needs more of an overhaul.

**Review by bruceg — COMMENTED** [review]
This looks relatively straightforward, but I am a little uncertain how this will play with the previous request token logic. I think it should be fine (since it's already dealing with `concurrency > 1`, but I'd like another set of eyes on this. @blt maybe?

**Comment by jszwedko** [comment]
Bump @blt when you get a sec.

**Comment by blt** [comment]
My only concern would be this now introduces an explicit bottleneck. Seems like, for the reasons @bruceg pointed out, there shouldn't be a correctness issue here but I would like to see the performance of this measured. I'm unfamiliar with cloudwatch so it's possible that we have to go through a buffer of size 1 to get tokens in the correct order, which would imply that this was broken previously?

**Comment by jszwedko** [comment]
I did some local testing with the following config:

```
[sources.stdin]
type = "stdin"

[transforms.remap]
type = "remap"
inputs = ["stdin"]
source = """
. = object!(parse_json!(.message))
"""


[sinks.sink0]
inputs = ["remap"]
group_name = "jesse-test"
stream_name = "{{ method }}"
region = "us-east-1"
type = "aws_cloudwatch_logs"
request.concurrency = 10
encoding.codec = "json"
```

And fed it with `flog -f json -l`.

Both on master and this PR I tapped out at around 15 MB/s so the impact seems negligible.

The tower service creation where I modified the buffer is actually _already_ log stream specific. I'm not entirely sure why it was architected like this, but it is one of the oldest sinks and so likely predates patterns we use elsewhere.

**Comment by jszwedko** [comment]
Notably on master, after #8884, it actually crashes now when you have `concurrency = "adaptive"` rather then the error it previously output in #9006

**Comment by blt** [comment]
> Both on master and this PR I tapped out at around 15 MB/s so the impact seems negligible.

When I run the following `flog --format json --loop | pv  > /dev/null` flog tops out at 53.5Mb/s. What's the result on your system?

**Comment by jszwedko** [comment]
> flog --format json --loop | pv > /dev/null

Good question! It appears to tap out at 30 Mbps.

**Comment by blt** [comment]
Cool, so the bottleneck is inside vector.

**Review by blt — APPROVED** [review]

**Pull request merged**
