### PR TITLE
fix: Avoid calling `peer_addr`

### LINKED ISSUE #2731: TCP source: "Socket not connected"
When using the socket source with type TCP and creating short-lived connections, vector quickly crashes with the following error: 

```
source{name=in type=socket}: vector::sources::util::tcp: failed to accept socket error=Could not get peer address: Socket not connected (os error 107)
```

I narrowed the configuration down to the following: 
```toml
[sources.in]
  address = "0.0.0.0:5514"
  mode = "tcp"
  type = "socket"

[sinks.blackhole]
  type = "blackhole"
  inputs = ["in"]
  print_amount = 1000
```

I run it as a docker image like so:
`docker run -it --network host -v $(pwd):/etc/vector/config  timberio/vector:nightly-alpine --config /etc/vector/config/config.toml`

And then I send something via netcat, directly closing the connection afterwards. Sometimes it takes a couple attempts, but it does consistently crash at some point. You should definitely be able to reproduce it with something like:
`while true; do echo "hi" | nc -c -v localhost 5514; done`

When I connect to it without the `-c` flag (i.e. keeping the connection open), everything is fine. The error appears to only happen when the connection is closed directly after sending.

Log level trace doesn't reveal any more information, btw.

### PR DESCRIPTION
**Pull request by ktff**
Ref #2731.

The issue with vector shutting down when we fail to accept `tcp` connenction was fixed with #3449. This PR addresses the source of the error which was a call to `peer_addr`. There was probably a race, between us receiving the socket and calling `peer_addr`, and other side closing the channel. Although I wasn't able to trigger this race, the PR adds a fix which completely eliminates the need for calling `peer_addr` and so eliminates any race that we can avoid.

The bug was effecting multiple sources and sinks  

### Todo

- [x] Ask for original reporters to verify that this PR fixes the issue.

### CODE REVIEW

**Review by bruceg — CHANGES_REQUESTED** [review]
Once this clears the tests (lints and component tests), looks good to go.

**Comment by ktff** [comment]
@bruceg I'm curious, why is `peer_addr` behind `#[cfg(feature = "listenfd")]`? Can we remove it now?

**Comment by bruceg** [comment]
I'm not entirely sure, those were added by @fanatid

**Review by fanatid — APPROVED** [review]
I added `#[cfg(feature = "listenfd")]` to `peer_field` because there were warnings with some features (`check-component-features` script).

`MaybeTlsIncomingStream::new` can be rewritten with [cfg-if](https://crates.io/crates/cfg-if) crate for removing duplicated code:
```rust
    pub(super) fn new(
        stream: TcpStream,
        peer_addr: SocketAddr,
        acceptor: Option<SslAcceptor>,
    ) -> Self {
        let state = match acceptor {
            Some(acceptor) => StreamState::Accepting(
                async move { tokio_openssl::accept(&acceptor, stream).await }.boxed(),
            ),
            None => StreamState::Accepted(MaybeTlsStream::Raw(stream)),
        };

        cfg_if::cfg_if! {
            if #[cfg(feature = "listenfd")] {
                Self { peer_addr, state }
            } else {
                Self { state }
            }
        }
    }
```

**Comment by ktff** [comment]
@bruceg @fanatid I think this a valid usage of conditional `#[allow(dead_code)]` so check the commit after this message. With it we can remove the specialized `new` function.

**Review by bruceg — APPROVED** [review]

**Review by fanatid — APPROVED** [review]

**Comment by ktff** [comment]
@joscha-alisch @perfectayush can you both check that this branch fixes the issue? I would like to confirm it before merging it.

**Comment by perfectayush** [comment]
@ktff I won't be able to verify for this. I was working on this in my previous organization. But I will let my colleagues who are still working on this for verification.

**Comment by joscha-alisch** [comment]
@ktff I can test soonest on Monday, currently on holidays without the machine I had those issues with.

**Comment by ktff** [comment]
@perfectayush @joscha-alisch thanks, that's great!

**Comment by ktff** [comment]
@perfectayush @joscha-alisch any success?

**Comment by perfectayush** [comment]
@ktff Sorry, my colleagues won't be able to test this anytime soon. We had implemented a workaround for this (supervisor restarts). And fixing/testing this isn't a high priority task at the moment.

**Comment by jamtur01** [comment]
@ktff You comfortable merging this without the validation?

**Comment by ktff** [comment]
@jamtur01 I am, it has worth in removing one source of errors, but I would like to keep the issue open until we hear something from @joscha-alisch

**Pull request merged**
