### PR TITLE
enhancement(config): Enabled templating of the 'index' option of the splunk_hec sink

### PR DESCRIPTION
**Pull request by benzaita**
Addresses issue #5313.

Allows using template strings in the `index` option of the `splunk_hec` sink.

This is my first stab at Vector, and a Rust project in general. So I probably got something wrong here :-) Please direct me if I need to add more tests or missed something.

### CODE REVIEW

**Comment by benzaita** [comment]
I'm not sure how [this failure](https://github.com/timberio/vector/pull/5418/checks?check_run_id=1506419808) is related to the changes. Would appreciate any pointers.

**Comment by jamtur01** [comment]
@benzaita I think it's unrelated. /cc @leebenson

**Comment by leebenson** [comment]
Re-running jobs. I suspect it's a fluke race condition with metrics init. If it happens again, I'll investigate further, but this unlikely to be related to this PR.

**Review by fanatid — APPROVED** [review]
Looks good! Thank you!

**Comment by jamtur01** [comment]
Awesome! Thanks @benzaita!

**Comment by jamtur01** [comment]
@benzaita Looks like a failed integration test: https://pipelines.actions.githubusercontent.com/mH90u5NZUbOaA8Iy93YxRewgZWsz7vVZNH8fS6w6J4u5woHDli/_apis/pipelines/1/runs/29991/signedlogcontent/30?urlExpires=2020-12-07T15%3A29%3A30.7629622Z&urlSigningMethod=HMACV1&urlSignature=2wiaN4%2F6XRk5RCnpEZr4I2XdiylsmlOd%2FwBXXEypMuI%3D - if you could take a quick look. Thanks!

**Pull request merged**
