### PR TITLE
chore(file source): Multiline config extract

### PR DESCRIPTION
**Pull request by MOZGIII**
This is a follow up from #3451, more specifically https://github.com/timberio/vector/pull/3451#pullrequestreview-467136523.

Let's discuss the proper location for the multiline config here.

### CODE REVIEW

**Comment by binarylogic** [comment]
@MOZGIII do you need a review on this?

**Comment by bruceg** [comment]
@binarylogic I think we need a discussion on this and #3357 to decide what direction we want to go with breaking Vector up with workspaces before we can complete this review.

**Comment by MOZGIII** [comment]
@binarylogic  this code change in particular was reviewed before, so I don't think it's requried. It is also quite trivial. @bruceg would you agree?

What needs a proper discussion is the approach to split vector into multiple crates. This is what @bruceg brough up in the original PR #3451 (and also at #3357). I feel like it's not a good approach to discuss this matter in the PRs like #3451 or this one, cause it sort of stalls them. It's better to have another PR that extracts the code into dedicated crate as the primary intent, like the #3357. But even then, we probably need to do some architectural preparations first.

That said, I think this one can just be merged.

**Comment by binarylogic** [comment]
Yep, @lukesteensen chimed in at https://github.com/timberio/vector/pull/3357#issuecomment-680125980, so let's follow his lead there.

**Pull request merged**
