### PR TITLE
chore: Add remap transform to semantic.yml

### LINKED ISSUE #3788: Add remap transform to the list of transforms in semantic.yml
Tiny issue. Does the remap transform need to be added to the `semantic.yml`? 

(https://github.com/timberio/vector/blob/master/.github/semantic.yml)

### PR DESCRIPTION
**Pull request by jamtur01**
Closes #3788

Signed-off-by: James Turnbull <james@lovedthanlost.net>

### CODE REVIEW

**Review by JeanMertz — CHANGES_REQUESTED** [review]
Similar to my question to @jszwedko here in https://github.com/timberio/vector/pull/3704#discussion_r486971574, I believe this file is auto-generated, so we'll need to add it somewhere else.

@binarylogic should know how this work (and I'm eager to learn as well).

**Comment by binarylogic** [comment]
Closing in favor of https://github.com/timberio/vector/commit/75487bee40d4d92e26982cfba60d0723aa2ed53b and https://github.com/timberio/vector-management/pull/11.

**Comment by binarylogic** [comment]
@JeanMertz you can do it all through [`vector-generate`](https://github.com/timberio/vector-generate). It should be as easy as:

```
cd scripts
./generate.rb
cd ../github
terraform apply
```

I've updated the [README](https://github.com/timberio/vector-management) to reflect the setup and usage steps.

**Comment by JeanMertz** [comment]
@binarylogic it looks like the `transform` (and other) scope is no longer valid. It's now named `transforms`.

Before we'd write `feat(remap transform): ...`, do you want us to use `transforms` now instead, or is this a mistake and should the domains file be updated to either rename `transforms` -> `transform`, or add `transform` (etc.) to the list of domains?

Or, should we just start writing `feat(remap): ...`?

**Comment by binarylogic** [comment]
My bad. Fixed in https://github.com/timberio/vector-management/commit/dbc7061556b7795a70660a28d5209e2f5eaf488c and https://github.com/timberio/vector/commit/ba19f2e781c67947089c14b2777f8fa9d6809e9f.

**Pull request closed without merging**
