### PR TITLE
enhancement(config): Add `source_key` and `source_type_key` to `log_scheme`

### PR DESCRIPTION
**Pull request by ktff**
Ref #2147.

Adds `log_schema.source_key` option and `log_schema.source_type_key` option with docs.

Note:
`make generate` is failing on my computer even without the changes to the docs. 

- [ ] Are these fields required?

### CODE REVIEW

**Comment by binarylogic** [comment]
>  make generate is failing on my computer even without the changes to the docs.

This should be resolved now. I had to update the Docker image for this task. Let me know if you still experience issues.

**Comment by Hoverbear** [comment]
Great start! Are you going to include the rest of #2147 or make a separate PR?

**Comment by ktff** [comment]
@Hoverbear Separate PR's, 2 most likely, one for updating the sink, and one or more for sources.

**Comment by binarylogic** [comment]
> Are these fields required?

`source_type` is required since every source should set this if the key does not already exist. `source` is optional since it sometimes is not relevant (ex: `stdin` source.

**Pull request merged**
